### ISSUE TITLE
Footer - logo margin dropped in certain scenarios

### ISSUE THREAD

**Issue by boxadesign** [ONSdigital/design-system#1024]
**Describe the bug**

![image](https://user-images.githubusercontent.com/1015442/94010945-85393380-fd9e-11ea-84a4-0c56abd9caec.png)

**Comment by trevorsaint** [comment]
@boxadesign that is interesting I don’t see this happening.

![image](https://user-images.githubusercontent.com/4989027/94041763-998f2780-fdc2-11ea-80fe-1c6788c2be0b.png)
![image](https://user-images.githubusercontent.com/4989027/94041829-ac096100-fdc2-11ea-9756-8a356b260f5d.png)
![image](https://user-images.githubusercontent.com/4989027/94041878-b88db980-fdc2-11ea-94ec-7feae47b5d45.png)

**Comment by boxadesign** [comment]
Not an issue.
