### ISSUE TITLE
Update page template languages logic.  If more than one other language, hide language toggles in masthead, and show in footer (at appropriate breakpoint)

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1058]
Update page template languages logic.  If more than one other language, hide language toggles in masthead, and show in footer (at appropriate breakpoint)

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/195#issuecomment-702602483_

**Comment by rmccar** [comment]
Fixed in #1159
