### ISSUE TITLE
Footer logo spacing issue

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1065]
Footer logo spacing issue 
![Screenshot 2020-10-05 at 16 26 09](https://user-images.githubusercontent.com/43346934/95099263-929fd780-0727-11eb-9dab-7e5650a7b9b9.png)

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/172#issuecomment-703706272_

**Comment by trevorsaint** [comment]
Hi @jrbarnes9 I’m not seeing this bug
https://ons-design-system.netlify.app/components/footer/

Everything looks fine to me. The same on my prototype running the latest design system version
https://deploy-preview-118--sdc-prototypes.netlify.app/prototypes/census-website-engage/home/
