### ISSUE TITLE
Saving the cookies form in the DS example sends you to the previous page you were on

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1089]
Saving the cookies form in the DS example sends you to the previous page you were on

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issue_comments/707807565_

**Comment by rmccar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #1089: Saving the cookies form in the DS example sends you to the previous page you were on](https://trello.com/c/H7HmGLKB/817-issue-1089-saving-the-cookies-form-in-the-ds-example-sends-you-to-the-previous-page-you-were-on)
