### ISSUE TITLE
Add warning to use footer variant when using address input with ONS Address Index API

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1112]
e.g. You should use the [footer variant with crown copyright](https://ons-design-system.netlify.app/components/footer/examples/footer-transactional-no-ogl-crest-copyright/) when using an address index API. 

We should document this on the address input component and/or addresses pattern.

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/412#issuecomment-713477098_

**Comment by jrbarnes9** [comment]
Added to content design epic: https://trello.com/c/1wBGbk9Q/569-epic-design-system-patterns-where-there-is-little-or-no-documentation-or-it-needs-a-review

**Comment by OscarJackson** [comment]
Linked to this ticket: https://trello.com/c/a4L4cFhe/664-design-system-addresses

**Comment by OscarJackson** [comment]
Updated on the address component and pattern. I'll keep this if we decide it only needs to be a component.
