### ISSUE TITLE
The blue on grey documented colour combination doesn't pass WCAG AA, as stated.

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1123]
The blue on grey documented colour combination doesn't pass WCAG AA, as stated.  

I'm not sure it's used anywhere in the DS any more, so could probably be removed or updated with the combination: FG #4263C2 on BG #F0F0F0, as used in the [featured article](https://ons-design-system.netlify.app/components/articles/examples/articles-featured/) component

<img width="299" alt="Screenshot 2020-10-22 at 16 42 50" src="https://user-images.githubusercontent.com/43346934/96896731-c5ff9780-1485-11eb-864f-493f0e6a6568.png">

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/232#issuecomment-714585081_

**Comment by trevorsaint** [comment]
This has been resolved and merged.
