### ISSUE TITLE
Footer should use a fluid layout, allowing links to wrap in a row

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1127]
Footer should use a fluid layout, allowing links to wrap in a row

From this...
![Screenshot 2020-10-27 at 08 12 31](https://user-images.githubusercontent.com/43346934/97274706-ee441900-182c-11eb-97d9-f7f7ce3d8ec0.png)

To this...
![Screenshot 2020-10-27 at 08 18 39](https://user-images.githubusercontent.com/43346934/97274784-09af2400-182d-11eb-8a37-dc482a414d4c.png)

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/172#issuecomment-717070182_

**Comment by trevorsaint** [comment]
If we remove the `flex: 0 0 auto` from the `grid__col`, our list items flow as you would expect them too.

If we can’t remove this property globally, we could have a modifier of sorts specific to footer list items.

Some adjustments need to be made with spacing and padding etc. But this will allow our items to flow naturally.

**Resulting in:**

<img width="440" alt="Screenshot 2020-10-27 at 11 21 53" src="https://user-images.githubusercontent.com/4989027/97295303-04f76980-1847-11eb-8222-a79712d7bd85.png">
