### ISSUE TITLE
Language of this download resources 'error' message should be improved.

### ISSUE THREAD

**Issue by armstrongb** [ONSdigital/design-system#1258]
https://github.com/ONSdigital/design-system/blob/c15311feb11a004f114aca7495384e8163a61e28/src/patterns/download-resources/examples/download-resources/index.njk#L491

I would suggest something like:
>There are no results to display for the filters you selected.

Currently awaiting feedback from Content Design.

**Comment by armstrongb** [comment]
From content:

> We think it’s best to take that line out completely. “No results found” is clear and doesn’t need elaboration. User has triggered the action so knows that they’ve been applying filters. It just clutters it up.
Is it possible to just remove it?

**Comment by rmccar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #1258: Language of this download resources 'error' message should be improved](https://trello.com/c/mcrh5aSz/1082-issue-1258-language-of-this-download-resources-error-message-should-be-improved)
