### ISSUE TITLE
`fieldset__legend` markup and margin still shows even when not used in macro

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1263]
`fieldset__legend` markup and margin still shows even when not used in macro

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/56#discussioncomment-234593_

**Comment by rmccar** [comment]
`Legend` param needs to be provided for radios

**Comment by jrbarnes9** [comment]
I think we should make this a condition, so radios won't render is a legend hasn't been set, unless they're using `dontWrap`. Otherwise this won't stop happening.
