### ISSUE TITLE
We need a select that does not have a set width

### ISSUE THREAD

**Issue by trevorsaint** [ONSdigital/design-system#1264]
We need a select that does not have a set width. The width should be fluid based on its contents.

Similar to languages: https://census-website-respond.netlify.app/end-to-end/languages

_Originally posted by @trevorsaint in https://github.com/ONSdigital/design-system/issues/50#issuecomment-750029537_

**Comment by jrbarnes9** [comment]
This can be achieved by using auto width utility class `ons-u-wa--`
