### ISSUE TITLE
Set page contents to be displayed right-to-left using css `direction: rtl`

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1278]
Set page contents to be displayed right-to-left using css `direction: rtl`

Originally required for the Craft Census website 'guide' template to be displayed rtl for rtl language guidance

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/195#discussioncomment-269386_

**Comment by trevorsaint** [comment]
This is a little more complicated that simply adding a CSS attribute `direction: rtl`.

We are using push classes on the grid, which obviously won’t work if you reverse the items. It would need to be a pull.

Perhaps we can have a content layout which creates the layout without the push and pull classes that does exactly the same thing, but a simple modifier class would do what we need. For example:

```
<div class="content-layout content-layout--rtl">
  <div class="content-layout__main"></div>
  <div class="content-layout__related"></div>
</div>
```

We won’t have push or pull classes, so a simple toggle of 'content-layout--rtl' would do the trick.

Might be worth a wider discussion before implementing this.

**Comment by jrbarnes9** [comment]
Could we not just switch out `.push-1@m` with `.pull-1@m`, and add `grid--reverse` for RTL templates?

**Comment by trevorsaint** [comment]
Here is another idea.

Our container will have a `.rtl` class.

Each component will have to be updated to be aware of RTL support. As the example below demonstrates:

```
.rtl .panel {
   direction: rtl;
}

.rtl .list {
   direction: rtl;
}
```

**Comment by boxadesign** [comment]
Thinking at a high level I would consider creating a separate stylesheet for this that works in the same way as our theme overrides (i.e. census.scss).

**Comment by rmccar** [comment]
I think that Matts solution is probably the simplest way of doing it and stops us having to make changes to every component

**Comment by trevorsaint** [comment]
Ok, so we create a `rtl.scss` stylesheet that handles the styling overrides.
