### ISSUE TITLE
Checkboxes

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#13]
Use this issue to discuss the [Checkboxes component in the ONS Design System](https://ons-design-system.netlify.com/components/checkboxes)

**Comment by bameyrick** [comment]
Currently there is no way to pass attributes to the checkboxes. It would be good to pass attributes to checkboxes like on inputs.

**Comment by hamishtaplin** [comment]
The examples show "select all that apply" as the `legend` whereas it should be a `.field__label`.

**Comment by jrbarnes9** [comment]
#271

**Comment by jrbarnes9** [comment]
Screen reader doesn't read out revealed text input field when selecting 'other' checkbox option.

**Comment by jrbarnes9** [comment]
> The examples show "select all that apply" as the `legend` whereas it should be a `.field__label`.

Covered in: #271

**Comment by jrbarnes9** [comment]
> Screen reader doesn't read out revealed text input field label or content when selecting 'other' checkbox option.

#272

**Comment by bameyrick** [comment]
The value parameter for the "other" text input isn't passed to the input macro so the field cannot be repopulated.

**Comment by glancyons** [comment]
The code for basic checkboxes:
https://ons-design-system.netlify.com/components/checkboxes/
 does not validate using
https://validator.w3.org/nu/

Error is:
Element p not allowed as child of element span in this context.

**Comment by jrbarnes9** [comment]
Min width of text input (19.5rem) is different to min width of checkboxes and radios (20rem)

<img width="449" alt="Screenshot 2020-09-03 at 08 26 38" src="https://user-images.githubusercontent.com/43346934/92084489-622eeb80-edbf-11ea-9d12-0ef0a69b7c66.png">
