### ISSUE TITLE
Accordions break visually if using it without show/hide buttons

### ISSUE THREAD

**Issue by trevorsaint** [ONSdigital/design-system#1300]
Accordions break visually if using it without show/hide buttons. I have removed one as an example.

<img width="783" alt="Screenshot 2021-01-18 at 11 52 10" src="https://user-images.githubusercontent.com/4989027/104912215-e73c2b00-5983-11eb-9f3b-e80caa151e78.png">

_Originally posted by @trevorsaint in https://github.com/ONSdigital/design-system/issues/81#issuecomment-762201830_

**Comment by jrbarnes9** [comment]
Buttons are now mandatory until we find evidence they are not required.
