### ISSUE TITLE
Download filter labels overlapping grid col

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1424]
Download filter labels overlapping grid col
![Screenshot 2021-03-08 at 09 16 52](https://user-images.githubusercontent.com/43346934/110300736-246d8280-7fef-11eb-8008-40c11e693e29.png)

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/888#discussioncomment-449426_

**Comment by trevorsaint** [comment]
This is due to the fact we have a `min-width` on onsCheckboxes. We don’t want this property if being used inside our filters pattern, otherwise this will happen.
