### ISSUE TITLE
Details

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#148]
Use this issue to discuss the [details component](https://ons-design-system.netlify.com/components/details) in the [ONS Design System](https://ons-design-system.netlify.com)

**Comment by bameyrick** [comment]
It isn't possible to apply custom classes to the details element.

**Comment by bameyrick** [comment]
@will-madebymoon and I think we should remove the arrow animation as it doesn't add any value.

**Comment by bameyrick** [comment]
When a user closes the details component using the inner button, the summary element should be refocused for screen readers to be able to easily move on to the next item on the page.

**Comment by bameyrick** [comment]
Buttons used in details components are type submit. These should be type button.

**Comment by jrbarnes9** [comment]
@will-madebymoon Paragraph content in an expanded details component is getting a bit lost when it's displayed inline with a lot of paragraphs in body content...
<img width="637" alt="Screenshot 2019-06-12 at 08 30 07" src="https://user-images.githubusercontent.com/43346934/59331627-4fc51f80-8cec-11e9-99b8-61f7426dc8cd.png">

Could we consider indenting it or something like e.g....
<img width="645" alt="Screenshot 2019-06-12 at 08 32 15" src="https://user-images.githubusercontent.com/43346934/59331826-c19d6900-8cec-11e9-9db3-f912226e8b28.png">

**Comment by jrbarnes9** [comment]
Details needs a default bottom margin

**Comment by bameyrick** [comment]
Maybe we should address all all of these issues when we look at spacing: https://trello.com/c/h0RbO4UV/99-spacing

**Comment by bameyrick** [comment]
Details element cannot be accessed with dragon naturally speaking as a button or as a link

**Comment by jrbarnes9** [comment]
Details chevron hidden when screen colours inverted (using v12 ZoomFusion)

**Comment by bameyrick** [comment]
Pointer events need to be turned off on all elements within the summary as GA fails to pick up click events

**Comment by jrbarnes9** [comment]
`details__title` should use a semantically appropriate heading tag (not a `<span>`)

**Comment by jrbarnes9** [comment]
Safari rendering issue: font-size rem units ignored on elements following `<details>` and `<summary>` (https://colloq.io/blog/safaris-detailssummary-rem-font-size-issue)

**Comment by glancyons** [comment]
**'Open' attribute does not validate**
`<div id="collapsible" class="collapsible js-collapsible" open data-btn-close="Hide this">`
In here: https://ons-design-system.netlify.com/components/collapsible/examples/collapsible/
In the open state.
I'm looking at the `open` attribute `...js-collapsible" open data-btn-close...` it does not validate

**Comment by jrbarnes9** [comment]
Collapsible chevron doesn't left align with other page elements when collapsed

<img width="582" alt="Screenshot 2020-09-16 at 11 59 56" src="https://user-images.githubusercontent.com/43346934/93328932-55c17e80-f814-11ea-8d4e-a9c394cf1db8.png">

**Comment by jrbarnes9** [comment]
Collapsible component no javascript fallback not working 

(Contents should display with a semantic heading above (no chevron or link style) See: #711
