### ISSUE TITLE
Remove `margin-bottom` from `fieldset__legend` if `legendIsPageTitle` is used.

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1547]
Remove `margin-bottom` from `fieldset__legend` if `legendIsPageTitle` is used.  

The `h1` already has the required margin

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/13#discussioncomment-845198_

**Comment by yatesn** [comment]
Part of spacing work - not currently a priority

**Comment by yatesn** [comment]
Fixed by #2392
