### ISSUE TITLE
Page template config needs more flexibility to allow full width components

### ISSUE THREAD

**Issue by trevorsaint** [ONSdigital/design-system#1572]
We can’t have a full width component that sits outside of the grid due to the way the page template is configured.

I was able to override the default grid output by adding the following to the pageConfig

```"pageColNumber": '12'```

**What we need**

<img width="1514" alt="extended" src="https://user-images.githubusercontent.com/4989027/122934718-b1063b80-d367-11eb-9bfc-be3f7d711054.png">

**What we get**

<img width="1464" alt="locked-inside-grid" src="https://user-images.githubusercontent.com/4989027/122934744-b794b300-d367-11eb-9adc-f36359817e63.png">

We could remove the pageConfig completely, but then we lose all of the other good things that come with it.

Ideally we want a way to remove grid usage by default, and then control items manually inside

```{% block main %}```

_Originally posted by @trevorsaint in https://github.com/ONSdigital/design-system/discussions/195#discussioncomment-904937_

**Comment by jrbarnes9** [comment]
@yatesn We had feedback from Ben Latham in the ONSDigital design-system slack channel about it not being obvious where to place full bleed components in the base page template. This ticket addresses that issue, so perhaps we could get this bumped up the backlog?

**Comment by yatesn** [comment]
Would it be helpful to put this on the community backlog as well?
