### ISSUE TITLE
Enable the list macro to call the external link macro

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1579]
Enable the list macro to call the external link macro so that external links in a bulleted list can inherit the icon and all the correct attributes.

![Screenshot 2021-06-30 at 16 19 22](https://user-images.githubusercontent.com/43346934/123987351-045b3800-d9bf-11eb-98fc-a3dbb717f217.png)

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/233#discussioncomment-943939_

**Comment by yatesn** [comment]
Double check HTML content filter in Service Manual
