### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by boxadesign** [ONSdigital/design-system#160]
Use this issue to discuss the [Header](https://ons-design-system.netlify.com/components/header) in the [ONS Design System](https://ons-design-system.netlify.com)

**Comment by bameyrick** [comment]
The header shouldn't have a margin bottom as it prevents being able to add components such as a hero banner flush to the header. This margin should be added to the [page template](#195) instead.

**Comment by bameyrick** [comment]
The reference to `/img/ons-logo-black-en.svg` needs to also have a version number parameter for usage in the [prototype kit](https://github.com/ONSdigital/prototype-kit).

**Comment by jrbarnes9** [comment]
The mobile header nav is missing `display:none` when collapsed.  You can still click the menu links when it's collapsed.

**Comment by bameyrick** [comment]
The header logo isn't rendering correctly in IE11:

<img width="443" alt="Screenshot 2019-04-18 at 15 15 04" src="https://user-images.githubusercontent.com/8447446/56368302-0de99280-61ef-11e9-8a67-ba639cd58ea9.png">

**Comment by bameyrick** [comment]
The main navigation always sets a homepage as active. This issue has been raised here: https://github.com/ONSdigital/prototype-kit/issues/10

**Comment by jrbarnes9** [comment]
No padding between title logo and menu button on mobile ~320px...

<img width="445" alt="Screenshot 2019-06-13 at 11 47 07" src="https://user-images.githubusercontent.com/43346934/59426857-29c57b00-8dd1-11e9-9480-72d415337744.png">

**Comment by bameyrick** [comment]
The logo on the internal variant of the header isn't rendering in any browser:

![Screenshot 2019-06-18 at 10 42 13](https://user-images.githubusercontent.com/8447446/59671629-e8104800-91b5-11e9-837b-e704dbfdff5a.png)

**Comment by bameyrick** [comment]
@will-madebymoon has requested the min-height of the top bar on the header to be dropped to 45px

**Comment by jrbarnes9** [comment]
Nav links are being hidden from screen readers due to `Aria-hidden=true`

**Comment by bameyrick** [comment]
Mobile navigation JavaScript has appeared to have stopped working

**Comment by jrbarnes9** [comment]
![image (3)](https://user-images.githubusercontent.com/43346934/66130264-57853880-e5e9-11e9-92a6-35337b5a74b1.png)

**Comment by jrbarnes9** [comment]
#756 When the ONS logo is wrapped in a link tag. The link class 'header__logo-link' is using 'inline-block', which causes extra padding. Changing this from 'inline-block' to 'block' should fix the issue.

**Subtle alignment problem**

![image](https://user-images.githubusercontent.com/4989027/82878638-a2b2d980-9f33-11ea-8b8a-a69cbb4751e9.png)

**Fixed using block instead of inline-block**

![image](https://user-images.githubusercontent.com/4989027/82878815-ef96b000-9f33-11ea-8f94-67b544d42945.png)

**Comment by trevorsaint** [comment]
Census logo needs to be changed to match the branding. 2021 should be white at 70% opacity.

Currently this
![image](https://user-images.githubusercontent.com/4989027/87169263-9a3a1680-c2c7-11ea-8503-b2ff3e4b7d1d.png)

Should be this
![image](https://user-images.githubusercontent.com/4989027/87169278-a3c37e80-c2c7-11ea-87bf-91d5aab7dddf.png)

**Comment by trevorsaint** [comment]
Alignment of logo and menu button in the header is incorrect.


Adding `display:block` to the SVG image will resolve this and render the header correctly.

**Before**
![before](https://user-images.githubusercontent.com/4989027/94233082-36ef7600-feff-11ea-9a7b-46ea6a37ac91.png)

**After**
![after](https://user-images.githubusercontent.com/4989027/94233103-4373ce80-feff-11ea-87d1-37a79e0a7a25.png)

This also fixes the over-spacing between the logo and the navigation when in desktop view.

**Comment by jrbarnes9** [comment]
Missing focus states on masthead and title header logos
