### ISSUE TITLE
Ensure examples are set to appropriate width

### ISSUE THREAD

**Issue by will-madebymoon** [ONSdigital/design-system#162]
When demonstrating the example should we not fix the maximum width? it's important to demonstrate that we understand the measure shouldn't be infinite. See screen grab 
<img width="1662" alt="screenshot 2019-02-13 at 09 14 17" src="https://user-images.githubusercontent.com/8184622/52701047-3811a080-2f71-11e9-905b-262897675b9d.png">

Consider...

Add on overridable max width to the example component

We should add a max width for the design system example component that can be switched off using a macro parameter

**Comment by bameyrick** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #162: The measure on examples is infinite, is this not misleading?](https://trello.com/c/2PXWs5ZZ/145-issue-162-the-measure-on-examples-is-infinite-is-this-not-misleading)

**Comment by bameyrick** [comment]
I think allowing examples to be full width is good for components such as a header and footer so maybe we should constrain the width of the example component by default and have an option to override to full width for certain components.

**Comment by jrbarnes9** [comment]
We should probably start using the grid in the patten library for content and the examples template.  Are we clear on which components should be never full width?

**Comment by bameyrick** [comment]
I think it's pretty much everything except headers, footers, timeout, and page template examples.
