### ISSUE TITLE
Input

### ISSUE THREAD

**Issue by bameyrick** [ONSdigital/design-system#163]
Use this issue to discuss the [Input Component](https://ons-design-system.netlify.com/components/input) in the [ONS Design System](https://ons-design-system.netlify.com)

**Comment by bameyrick** [comment]
Input component page needs to be updated to reference this forum issue

**Comment by bameyrick** [comment]
The `title` attribute on the input should only be applied if a prefix or suffix exists.

**Comment by bameyrick** [comment]
Inputs should be set to use Lato typeface for user input

**Comment by bameyrick** [comment]
Input width modifier doesn't work correctly when used in a `field__item`, for example the date component. Inputs will only grow as wide as their labels.

**Comment by jrbarnes9** [comment]
Use of `autocomplete` needs more work and guidance regarding its use in survey questions where the integrity of the data could suffer from pre-population

**Comment by jrbarnes9** [comment]
Inputs should have a sensible default width class (that can be overridden) for certain input types (that have a known max length e.g. postcode) so authors do not need a width each time.

**Comment by bameyrick** [comment]
Suffixed inputs should not have text right aligned as this causes issues with ZoomText.

**Comment by bameyrick** [comment]
We should hide the clear button IE11 adds to inputs as it breaks the layout of inputs with constrained widths

**Comment by bameyrick** [comment]
The input component doesn't wrap itself in a field (#35) when used in mutually exclusive (#29) mode.

**Comment by bameyrick** [comment]
The suffix/prefix text for inputs is no longer vertically centred

<img width="360" alt="Screenshot 2019-07-16 at 15 02 23" src="https://user-images.githubusercontent.com/8447446/61301000-f795a780-a7da-11e9-90e0-5e2e204b2656.png">

**Comment by jrbarnes9** [comment]
UR reports users are often blind to input hint text, especially on auto-suggest lookups.  Propose to increase font-size to base.

**Comment by jrbarnes9** [comment]
Hint text shouldn't be contained within the label.  Place outside and use `aria-describedby` (see: https://design-system.service.gov.uk/components/text-input/#hint-text)

**Comment by jrbarnes9** [comment]
Ensure input width class numerals match number of widest character

**Comment by jrbarnes9** [comment]
> Hint text shouldn't be contained within the label. Place outside and use `aria-describedby` (see: https://design-system.service.gov.uk/components/text-input/#hint-text)

Won't do this, whilst we have bounding boxes around label and hint.

**Comment by jrbarnes9** [comment]
Increase mobile number width example to `input--w-9` to cater for longest case scenario of e.g. +44 08888 888 888

**Comment by jrbarnes9** [comment]
Text input focus border styling is inconsistent across devices/browsers...
On Chroms MacOS it renders as it should...
![Screenshot 2020-11-23 at 10 29 38](https://user-images.githubusercontent.com/43346934/99951957-d05bcc80-2d76-11eb-8dfe-ac8dd0d70fb5.png)

But on Chrome Windows and Chrome Android it is rendering like...
![image](https://user-images.githubusercontent.com/43346934/99952168-24ff4780-2d77-11eb-94df-8d79bbe7e613.png)

![Screenshot_20201123-102826](https://user-images.githubusercontent.com/43346934/99952063-fbdeb700-2d76-11eb-9901-5e6f6545970b.png)
