### ISSUE TITLE
How to ask for names

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1637]
## What

Add pattern on how to ask users for names. 

## Why

This was a common and well-testing pattern used in Census 2021.  It's a core part of EQ surveys.

## Supporting material

<img width="456" alt="Screenshot 2021-08-13 at 09 10 37" src="https://user-images.githubusercontent.com/43346934/129325754-bb97ea9a-a2c4-4573-b51e-75737ce09bd1.png">

## Contacts

EQ runner team. PM - sarah.brooks@ons.gov.uk.

**Comment by yatesn** [comment]
Dependency on a review of use of mandatory fields - spike

**Comment by Majsol** [comment]
In gov.uk they ask for the users full name instead 
https://design-system.service.gov.uk/patterns/names/

**Comment by OscarJackson** [comment]
Trying to work out why we sometimes ask for first name, middle name and surname individually. 
Will then either document with single input and multiple inputs, or one or the other.

**Comment by OscarJackson** [comment]
I think we'll need 2 example components for this:
- one with a single input field for 'full name' similar to [GOV.UK ](https://design-system.service.gov.uk/patterns/names/)
- one with separate inputs for 'First name', 'Middle names' and 'Last name'
