### ISSUE TITLE
Add inline label variant to select component

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1649]
Add inline label variant to select component 

For special cases, such as 'sort by'.

Placing the label above the form control does not work in some situations. Therefore a variant will be required.

Also:
- A normal weight variant for labels would also be useful.

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/1385#discussioncomment-1201705_
![download](https://user-images.githubusercontent.com/43346934/129925640-9a9bdd87-2a2e-4156-8f75-534ed728fe97.png)

**Comment by armstrongb** [comment]
@jrbarnes9 this variant will also be required in digital publishing templates - e.g. search results 'order by' select component.
