### ISSUE TITLE
Balance spacing of date inputs

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#1663]
![image](https://user-images.githubusercontent.com/42928680/132508517-f1239c7d-c8d0-4a99-8d60-2004e6b03cdd.png)
Date inputs are not evenly spaced

**Comment by rmccar** [comment]
Think we should maybe make the gap between day and month bigger then, and/or reduce the size of the text slightly because it looks really odd as it is

**Comment by jrbarnes9** [comment]
I think the best thing we could do is add a `min-width` to the field and reduce it's right margin by half.  

So you'd get...
![Screenshot 2021-10-01 at 15 12 40](https://user-images.githubusercontent.com/43346934/135634771-595d76bf-904b-45be-8725-1e8e30dc4b6e.png)

**Comment by rmccar** [comment]
I do think that looks better, if that works when the screen size is reduced etc then I think we should go with that

**Comment by willcAND** [comment]
Agreed as team that we're happy with the current implementation.
