### ISSUE TITLE
Remove out-of-date content in /docs

### ISSUE THREAD

**Issue by bameyrick** [ONSdigital/design-system#167]
Move content out of /docs into GitHub Wiki as this seems like the most sensible place for it.

**Comment by bameyrick** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Move content out of /docs into GitHub wiki](https://trello.com/c/Jo4yfDcf/149-move-content-out-of-docs-into-github-wiki)

**Comment by daniellecorke** [comment]
This ticket is in the archived category - closing.
