### ISSUE TITLE
Gather metrics via GTM for clicks on the `<abbr>` element

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1680]
I don't think that this has been confirmed as an issue.
Suggest that if we want to check if clicking on the 'symbols' is an issue for users that we gather metrics via GTM for clicks on the `<abbr>` element.

_Originally posted by @armstrongb in https://github.com/ONSdigital/design-system/discussions/279#discussioncomment-177913_

**Comment by yatesn** [comment]
Can be closed, covered by #1604
