### ISSUE TITLE
Interviewer-led survey

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1695]
## What

Add the pattern used in Census 2021 for CCS, which uses particular notes/styles to lead a doorstep interviewer through a survey. 

We already have examples of these elements in the [question pattern](https://ons-design-system.netlify.app/patterns/question/), so this would move those examples and add documentation to create a new pattern.

## Why

It's a regular pattern for eQ that will likely be reused across multiple social surveys.

## Supporting material
See examples at: https://ons-design-system.netlify.app/patterns/question/#question-with-a-interviewer-instruction

### Content guidance
See section 13 of: https://docs.google.com/document/d/1WHCdeMXqbk5erl0RYQBymt9s19IsbvOszQmQ869WR20/edit?usp=sharing

**Comment by OscarJackson** [comment]
Hi @JNATION85, do you know what this one is about?

**Comment by OscarJackson** [comment]
I don't think it's a good idea to move these onto an individual page as I'm not sure if we want to be encouraging their use. My thinking is that if the interviewer needs instructions to help someone answer the survey, then that's a problem with the survey content. How could we expect someone to answer it on their own if even our employees need extra help?

The interviewer notes could be helpful, but not sure about the showcards. They seem to serve the same purpose as the include/excludes or the question definitions that we use in surveys anyway. If we used those instead, the interviewer would be able to tell what was in them by the title/just seeing the information panel and we wouldn't need the interviewer instruction anyway.
