### ISSUE TITLE
Console error in download resources pattern when selecting filters

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1729]
Console error in download resources pattern when selecting filters

<img width="1275" alt="Screenshot 2021-10-11 at 12 45 05" src="https://user-images.githubusercontent.com/43346934/136784853-fe132028-afc5-49b0-8204-eb36dae03139.png">

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/888#discussioncomment-1458680_

**Comment by yatesn** [comment]
Duplicate of #1664
