### ISSUE TITLE
[1 day spike] Summary macro and macro options don't match up and are confusing

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#1730]
The summary macro and/or the macro options table needs updating so that they reflect each other and also need some params renaming and potentially refactoring because they're pretty confusing. Ill try and explain it as simple as possible.
Currently:
- `row.rowTitleAttributes` doesn't exist in the macro but it is in the macro options
- `rowItem.rowTitleAttributes` doesn't exist in the macro options but it is in the macro
- the `attributes`/`rowTitleAttributes` params need renaming/refactoring because both `row` and `rowItem` use `rowTitleAttributes` and `rowItem` also uses `attributes`
- `rowItem.rowTitle` exists in the macro but not in the macro options
- `rowItem.title` doesn't exist in the macro but it is in the macro options
- the `title`/`rowTitle` attributes also need renaming/refactoring because both row and rowItem use `rowTitle`

**Comment by jrbarnes9** [comment]
@rmccar Did this all get sorted in #1859 and #1844 ?

**Comment by rmccar** [comment]
No, none of this has been sorted. This is more of a renaming/refactor of params and updating of docs

**Comment by daniellecorke** [comment]
Needs refining - discuss with Rich.

**Comment by daniellecorke** [comment]
The purpose of this ticket is to review the parameters.

**Comment by precious-onyenaucheya-ons** [comment]
Based on a review of the summary component and technical discussions with the team, the following parameter renames have been proposed:

summary.summaryTitle will be renamed to summary.title
group.groupTitle will be renamed to group.title
row.rowItems will be renamed to row.items
row.rowTitle will be renamed to row.title
rowItem.rowTitle will be renamed to item.title
rowItem.rowTitleAttributes will be renamed to item.titleAttributes
