### ISSUE TITLE
Improve docs to cover importing SCSS styles fully with potential gotchas

### ISSUE THREAD

**Issue by designorant** [ONSdigital/design-system#1750]
Following SCSS [instructions](https://ons-design-system.netlify.app/guidance/using-css-js-and-assets/#css) does not cover a couple of utilities that DS uses.

## Background

Straight of the bat we get:

```
Error: Can't find stylesheet to import.
  ╷
1 │ @import 'normalize';
  │         ^^^^^^^^^^^
  ╵
  node_modules/@ons/design-system/scss/main.scss 1:9  @import
```

This is due to DS's gulp config:

```js
const sassOptions = {
  importer: nodeSassGlobImporter(),
  includePaths: ['./node_modules/normalize-scss/sass', './node_modules/prismjs/themes'],
};
```

This forces the consumer to install `normalize-scss` locally, and set it up accordingly in their bundler. In case of Rollup with Svetle it's something like this:

```js
preprocess: sveltePreprocess({
  scss: { includePaths: [`/node_modules/@ons/design-system/`, './node_modules/normalize-scss/sass'] },
}),
```

In this case however it results in another problem:

```
Error: Can't find stylesheet to import.
  ╷
9 │ @import '../components/**/*.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules/@ons/design-system/scss/main.scss 9:9  @import
```

This is due to a lack of [`node-sass-glob-importer`](https://github.com/maoberlehner/node-sass-magic-importer/tree/master/packages/node-sass-glob-importer) on the consumer side. Not an issue with projects using Node Sass, but this is a showstopper for Dart Sass as `svelte-preprocess` does not support the `**` glob pattern.

## Proposal

I suggest to update the docs so they mention support for `node-sass` only, and a need for `normalize-scss` and `node-sass-glob-importer` configured locally. Alternatively consider dropping the above utilities at a cost of some extra elbow grease to ease adoption, and [move to Dart Sass](https://github.com/ONSdigital/design-system/issues/1749).

We've ended up _temporarily*_ importing the whole CSS file instead, along with SCSS variables so we can access the colour palette at least hence this note/issue.

<sub>*famous last words</sub>

**Comment by designorant** [comment]
Implemented in #1757. Thank you!

**Comment by designorant** [comment]
Turned out #1757 had some bugs:

Please remove the following from `main.scss` (unless I'm missing something):
```
@import '../patterns/help-users-to/see-important-information/src/_highlight';
@import '../patterns/pages/question/examples/question-anatomy/pl-question-anatomy';
@import '../foundations/layout/page-template/examples/block-areas/block-areas';
@import '../foundations/style/colours/colours';
@import '../foundations/style/icons/icon-swatch';
```

Please also kindly add `!default` to the `$static` variable so it can be overridden on import for correct font paths without recreating the whole `main.scss`:
`$static: '..' !default`

Much thanks!

**Comment by boxadesign** [comment]
I believe these extra styles were added in error as dart sass doesn't support the glob method we were using previously.

**Comment by boxadesign** [comment]
> !default

https://github.com/ONSdigital/design-system/pull/1784/files
