### ISSUE TITLE
Importing JS for a specific component seems buggy

### ISSUE THREAD

**Issue by boxadesign** [ONSdigital/design-system#1761]
Each `component.dom.js` relies on `import domready from '../../js/domready';` which isn't exported as part of the `@ons/design-system` package

**Comment by kruncher** [comment]
@boxadesign when you say seems buggy how do you mean? What is the expected and actual behaviour?

**Comment by boxadesign** [comment]
@kruncher Yeah sorry I didn't actually write the issue (but should've improved the wording). We don't add the domready.js file to the npm bundle or zip file so it errors when attempting to import that file into each _script_.dom.js file that a service will try to include.

**Comment by kruncher** [comment]
@boxadesign

- I've made a PR which aims to include 'domready.js' at least in npm releases.
- It isn't clear to me how this affects the **.zip** file since the only reference that I could find was just for zipped templates.
- Does this affect other scripts such as 'src/js/cookies-settings.dom.js'?

**Comment by designorant** [comment]
#1762 did indeed include the `domready.js` but the include path in the components hasn't been updated:

```
Failed to resolve import "../../js/domready" from "node_modules/@ons/design-system/components/collapsible/collapsible.dom.js". Does the file exist?
```

Current:
`import domready from '../../js/domready';`

Correct:
`import domready from '../../src/js/domready';`

**Comment by designorant** [comment]
@boxadesign @kruncher Please see [my comment above](https://github.com/ONSdigital/design-system/issues/1761#issuecomment-978044472). The file is there but the path is wrong (`v44.1.2`).

**Comment by designorant** [comment]
I'm afraid that despite #1798 the issue is still there in `v45.0.0`, this time the `domready.js` is nowhere to be found.
