### ISSUE TITLE
Accordion Jinja2 issue with setAttributes filter

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1786]
I have attempted to use this in my Flask app but this component unfortunately does not work in Jinja2 (3.0.3):

```jinja2.exceptions.TemplateRuntimeError: No filter named 'setAttributes' found.```

_Originally posted by @JoelClemence in https://github.com/ONSdigital/design-system/discussions/1377#discussioncomment-1716616_

**Comment by yatesn** [comment]
MS provided advice in original discussion, awaiting response from JC
