### ISSUE TITLE
Checkboxes don't work with latest template, without CSS style.

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1787]
Checkboxes don't work with latest template, without CSS style.
They also need a 'name' which is missing from example. 
So working minimum would be: 

    <div class="ons-grid__col ons-col-3@m ">
      <div class="ons-pl-grid-col">
	{{
        onsCheckboxes({
            "checkboxesLabel": "Clearing Status:",
            "dontWrap": true,
            "checkboxes": [
                {
                    "id": "clear",
                    "name": "statuses-clear",
                    "label": {
                        "text": "CLEAR"
                    },
                    "value": "clear"
                }
}}
</div>
</div>   

Can we please update example on https://ons-design-system.netlify.app/components/checkboxes/

_Originally posted by @dariusz22p in https://github.com/ONSdigital/design-system/discussions/13#discussioncomment-1716598_

**Comment by yatesn** [comment]
Initial response provided, closed until otherwise advised
