### ISSUE TITLE
Search result item

### ISSUE THREAD

**Issue by armstrongb** [ONSdigital/design-system#1797]
## What
- Type: **Component**

A new component is required for the search result items which have been evaluated as part of the on-site search project.
No existing component exists for the search items.

## Why

> Explain why you think this feature or content should be added to the ONS Design System.
>
> - What evidence do you have that your ONS service needs it?

- The user need is to facilitate improved findability of the ONS site content.
- The variants that exist are a refinement of existing historical patterns in use across the ONS website which have yet to be documented in the design system.
- Multiple rounds of user testing (Figma prototypes) of the new search design have been conducted and the designs have been approved by users each time.

## Supporting material

> Include links to any examples, research, prototypes or code that support your proposal.

Documented in **[Figma here](https://www.figma.com/file/kAyqXh8f02S0UXauLubSkF/Beta-release-reference?node-id=0%3A1)**.
![All content type results](https://user-images.githubusercontent.com/22910336/145201415-88b746df-5077-4dd8-a1cd-f59e0a89d098.png)

## Contacts

@armstrongb - interaction design
Leon Rose - user research (DST)
Gracie Lewis / Ryan Flynn - product owner (DST)

**Comment by jrbarnes9** [comment]
@armstrongb Do you want to add a ticket for a full 'search' page pattern to come after this?
