### ISSUE TITLE
Active item in the header nav shouldn't cause the subsequent nav items to shift horizontally

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1809]
The active item in the header nav should allow for the extra width of the bold font and not cause the subsequent nav items to shift horizontally.

![header-nav-issue](https://user-images.githubusercontent.com/43346934/148212415-76baa723-84bf-45b6-898b-0b687b3d1567.gif)

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/160#discussioncomment-1911508_

**Comment by willcAND** [comment]
Unable to replicate behaviour, closing
