### ISSUE TITLE
Padding adjustments

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1870]
Padding adjustments for text-underline-position

The vertical spacing needs adjusting on components which contain a link that should be vertically centred, now that we use `text-underline-position: under`. They currently appear much tighter to the bottom boundary and the link doesn't look vertically centred.

Affects:
- Accordion
- TBC...

**Comment by daniellecorke** [comment]
Unsure if this is still needed - check with Dina in backlog refinement.
