### ISSUE TITLE
Fix spacing

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1872]
**Describe the bug**
Refine and document spacing

- Sort out default margins
- More spacing above headings

**Additional context**
Links to the need for a spacing scale

**Comment by yatesn** [comment]
Part of spacing work - not currently a priority

**Comment by daniellecorke** [comment]
This ticket is duplicated in #1994 and [#1935 ](https://github.com/ONSdigital/design-system/issues/1935) - will close this ticket as work is already covered in other tickets and awaiting UCD.
