### ISSUE TITLE
Component template appearing in subnav

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1892]
https://ons-design-system.netlify.app/components/_documentation-template/

![Screenshot 2022-01-28 at 11 38 04](https://user-images.githubusercontent.com/43346934/151542099-35ef8063-da38-4565-a9f0-1c17e32f5528.png)

PR #1871 is the earliest I can see it appearing in the netlify previews: https://deploy-preview-1871--ons-design-system.netlify.app/components/pagination/

**Comment by boxadesign** [comment]
https://github.com/ONSdigital/design-system/pull/1901
