### ISSUE TITLE
Make the prototype kit better for consuming

### ISSUE THREAD

**Issue by boxadesign** [ONSdigital/design-system#1903]
We can do further refactoring of the prototype kit to make it better for maintenance and consumption. 

Currently a user would need to fork the repo which contains the core stuff that creates/builds prototypes. We can move the proto kit into a more modular place where users can create a GH project and run a single command and get they stuff they need to make protos while retaining control for the logic in the main repo.

**Comment by kruncher** [comment]
A PR has been created for this: https://github.com/ONSdigital/prototype-kit/pull/33

**Comment by kruncher** [comment]
Once the PR has been tested and reviewed a small change is required (documented in the PR description). It has been configured for testing from its feature branch which is not appropriate for the actual merged release.
