### ISSUE TITLE
Review cookie banner

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1913]
We need to review our cookie banner to ensure it's compliant with the regulations as many gov services have recently updated their banner to make sure the user can equally turn on or turn off all non-essential cookies in one click.

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/715#discussioncomment-2103264_

![Screenshot 2022-02-03 at 12 01 47](https://user-images.githubusercontent.com/43346934/152339454-552e6b4d-8efe-4ad3-8c91-92d809c052c0.png)
![Screenshot 2022-02-03 at 12 02 05](https://user-images.githubusercontent.com/43346934/152339459-2cfc250a-4e33-44f0-95d5-51d887a4228e.png)
![Screenshot 2022-02-03 at 12 02 15](https://user-images.githubusercontent.com/43346934/152339463-073c6327-5c01-41f2-a197-55fa9f7e245d.png)

**Comment by boxadesign** [comment]
On hold pending content review.

https://deploy-preview-2010--ons-design-system.netlify.app/patterns/cookies-settings/
