### ISSUE TITLE
Investigate issue with <details> and collapsible

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1921]
We should document in the collapsible component, why we don't use the `<details>` and `<summary>` elements (due to a [bug found in safari](https://github.com/ONSdigital/design-system/issues/741))

Create 2 versions of accordion

**Comment by kruncher** [comment]
This issue seems to have been resolved in the Safari web browser:
- https://bugs.webkit.org/show_bug.cgi?id=173876
- https://bugs.webkit.org/show_bug.cgi?id=177585

**Comment by kruncher** [comment]
This is being implemented in #2013
