### ISSUE TITLE
Switch font to Open Sans stylistic set 1

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1933]
This is to bring the DS inline with the brand guidelines which advises use of set 1 (rather than set 2) to include both the open 'g' and the more accessible 'I'.

See: https://ons-design.notion.site/Typography-97f2f60558f040f7899eb28e5f1b932c

**Comment by armstrongb** [comment]
May require a fresh Open Sans font and the use of `font-feature-settings: "ss02" 1;`

**Comment by yatesn** [comment]
If set that is linked is correct then this will be less work, if not, will be 2
