### ISSUE TITLE
Use of `autocomplete` needs more work and guidance regarding its use in survey questions where the integrity of the data could suffer from pre-population

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1939]
Use of `autocomplete` needs more work and guidance regarding its use in survey questions where the integrity of the data could suffer from pre-population

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/163#issuecomment-470123980_

**Comment by jrbarnes9** [comment]
Dupe of #275
