### ISSUE TITLE
Remove browser compatibility table and use the one on GDS DS

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1941]
GDS updated their browser support list twice a year. We should remove our table and link to theirs instead

https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices

Comment:
Will speak with @leonrose about getting browserstack plan upgraded to mobile automate so we can test with our new support list.

**Comment by jrbarnes9** [comment]
Resolved: https://ons-design-system.netlify.app/guidance/browser-testing/
