### ISSUE TITLE
Redo all illustrations in patterns

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1942]
Redo all illustrative (e.g. flow diagrams for patterns) used in pattern library. Ones used for iconography etc are fine.
Main example is check answers - check to see if any others

**Comment by yatesn** [comment]
Content/UxD task

**Comment by yatesn** [comment]
PNGs need updating

https://service-manual.ons.gov.uk/design-system/patterns/check-answers

**Comment by Majsol** [comment]
It is created and ready to be uploaded

**Comment by JNATION85** [comment]
Looking at the images they seem to be blurred. We need to either make sure the PNG is scaled correct or we use SVG. The original ones were SVG so could be do the same for these?

**Comment by Majsol** [comment]
The images have been changed into svg and added to cms.
