### ISSUE TITLE
Add content guide for "Writing text messages and emails"

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1943]
To add to a new pattern for the design of texts and emails.

Add content from section 14 in: https://docs.google.com/document/d/1WHCdeMXqbk5erl0RYQBymt9s19IsbvOszQmQ869WR20/edit?usp=sharing

**Comment by yatesn** [comment]
Potentially included in style.ons

**Comment by Majsol** [comment]
Oscar will get in touch with Amelia
