### ISSUE TITLE
Spike: Is there a better way of asking for percentages?

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1946]
See example screenshot from BICs survey.

Maybe sliders that work dependently?

![image](https://user-images.githubusercontent.com/97620554/152559937-59bb22eb-b904-48be-9477-af976bd02547.png)

**Comment by armstrongb** [comment]
Couple of code pens related to this from a waaaaay back: (not final solutions just ideas that were experimented with at the time this pattern first came around)
https://codepen.io/benarmstrong_ons/full/OWYLGp
https://codepen.io/benarmstrong_ons/full/JEpXbo

**Comment by OscarJackson** [comment]
This is really interesting, I like https://codepen.io/benarmstrong_ons/full/OWYLGp as it will put less strain on the user when they're entering info. We don't currently have an interaction designer on eQ, but I could run it past them and see what they say

**Comment by OscarJackson** [comment]
After speaking with eQ RAD, I've found that user research shows that users don't struggle with these.
As we already have the validation to make sure they add up to 100%, the only value would be that it tells them before they press 'continue'. So, not sure if it's worth the work at the moment. One for the future though maybe.
