### ISSUE TITLE
Spike: Improving financial inputs

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1947]
https://github.com/ONSdigital/design-system/discussions/279#discussioncomment-1822731
How can we improve financial numeric input to avoid surveys feeling like they need to put all this kind of instruction in the hint text?
<img width="606" alt="Screenshot 2021-12-16 at 12 00 20" src="https://user-images.githubusercontent.com/43346934/146368798-8e29972d-f638-4d74-bed5-61975b21db5b.png">

**Comment by jrbarnes9** [comment]
Comments from https://github.com/ONSdigital/design-system/discussions/279#discussioncomment-2113010:
Part of the historical problem is that on paper these businesses were asked to enter 56 for 56,000 as the the 000 was pre-filled values on the form. On some forms that collect larger values 000,000 was printed meaning 12 was written for £12,000,000.

The original solution for this was to ensure that all values were shown in full on the summary screen, including pence, to make clear the true value being submitted. That way anyone entering 56 as they had habitually entered rounded thousands would be shown £56.00 and given an opportunity to correct it to £56,000.

**Comment by yatesn** [comment]
Likely to need eQ input

**Comment by jrbarnes9** [comment]
Linked to https://github.com/ONSdigital/design-system/discussions/1383#discussioncomment-1356482

**Comment by OscarJackson** [comment]
There is a change coming for this. We've done some testing and it's likely the guidance text will be changed to: 'Enter a value to the nearest thousand. For example, 56,000.'

We're just clearing this with the MSO team before making the change.

**Comment by OscarJackson** [comment]
We're now proceeding with this change. 

I'm discussing with the Author team how to get this updated on their end, but I'm going to go ahead and update the documentation on the Input component.
