### ISSUE TITLE
Page template

### ISSUE THREAD

**Issue by boxadesign** [ONSdigital/design-system#195]
Use this issue to discuss the [Page template](https://ons-design-system.netlify.com/styles/page-template) in the [ONS Design System](https://ons-design-system.netlify.com)

**Comment by jrbarnes9** [comment]
The page template example with save and complete - button doesn't display in the footer < 740

**Comment by jrbarnes9** [comment]
No config for the masthead logo href in the page template

**Comment by jrbarnes9** [comment]
Width and height of svgs lost when rendered in the browser
<img width="773" alt="Screenshot 2020-02-11 at 14 13 54" src="https://user-images.githubusercontent.com/43346934/74244126-dea19600-4cd8-11ea-8306-6f6b8be50eb3.png">

**Comment by jrbarnes9** [comment]
` prePage` block should be `preMain`

**Comment by jrbarnes9** [comment]
Unlinked references in page template variable tables

**Comment by jrbarnes9** [comment]
Increase `page__main` margin-top to 2.5rem (over 740) and 1.5rem (under 740).

Spacing is currently too tight.

<img width="783" alt="Screenshot 2020-09-03 at 08 40 24" src="https://user-images.githubusercontent.com/43346934/92086466-1df11a80-edc2-11ea-9836-002637bfc142.png">

**Comment by jrbarnes9** [comment]
Save and sign out button in footer of page template example ('Customised page template') is missing exit icon

<img width="279" alt="Screenshot 2020-09-17 at 09 18 20" src="https://user-images.githubusercontent.com/43346934/93439794-e062b600-f8c6-11ea-9204-f77be5afd905.png">

**Comment by Paul-Joel** [comment]
Is there a way to provide a 'nonce' for the inline script calls without using Talisman? The existing if statements in the layout/_template.njk only allow for the talisman call to add a nonce as far as I can tell

**Comment by jrbarnes9** [comment]
Update page template languages logic.  If more than one other language, hide language toggles in masthead, and show in footer (at appropriate breakpoint)

**Comment by jrbarnes9** [comment]
Broken footer in census page template

https://ons-design-system.netlify.app/styles/page-template/examples/census/

![Screenshot 2020-12-01 at 16 59 52](https://user-images.githubusercontent.com/43346934/100771838-caa95b00-33f6-11eb-81a0-900d745e7634.png)
