### ISSUE TITLE
Add API options documentation to address input component

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1953]
No documentation?

**Comment by jrbarnes9** [comment]
https://trello.com/c/1wBGbk9Q/569-epic-design-system-patterns-where-there-is-little-or-no-documentation-or-it-needs-a-review

**Comment by OscarJackson** [comment]
Linked to this ticket https://trello.com/c/a4L4cFhe/664-design-system-addresses - would have this as you'd only use one of the variants and wouldn't use them in combination.

@JNATION85 do you have any thoughts on this?
