### ISSUE TITLE
Add documentation to addresses pattern about the use of the footer with copyright

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1959]
Add documentation to the Addresses pattern about the use of the footer variant with 'OS address data terms and conditions' when using this pattern.

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/412#issuecomment-713477098_

Linked to #1112

**Comment by jrbarnes9** [comment]
Dupe of #1112
