### ISSUE TITLE
Review and refine documentation for Images style

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1960]
https://ons-design-system.netlify.app/styles/images/

Add:
-  'when to use a caption' 
- aspect ratios
- illustrations or representative imagery
- alt text

**Comment by alessioventuriniAND** [comment]
We need to investigate if this is still needed or if it has been covered in the brand guidelines/brand-elements  under photography and illustration

**Comment by JNATION85** [comment]
This is legacy and is not needed any more. This is covered in the brand guidelines section and is also mentioned in the design system
