### ISSUE TITLE
Update "panel" component documentation

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1962]
Align to common template and add content writing guidance

**Comment by jrbarnes9** [comment]
https://trello.com/c/3SciYQDr/487-panels

**Comment by jrbarnes9** [comment]
Content design have suggested we split each panel type out into it's own component e.g.
- Error summary
- Error details
- Warning
- Information panel
- Confirmation panel

**Comment by OscarJackson** [comment]
This issue is still open as conversations are ongoing with the Ix community about whether this is a good idea.
[Panels - Content Design board Trello Ticket](https://trello.com/c/3SciYQDr/487-panels)

**Comment by Majsol** [comment]
Meet and discuss - Alessio, Joe, Precious, Oscar & Dina

**Comment by Majsol** [comment]
There are no resources to creating separate macros as Jon has suggested to investigate. However Oscar will restructure the "Panel" and add some more context around the component - and add some search terms to make it easier for the users find

**Comment by OscarJackson** [comment]
In the process of creating:
- Information panel
- success panel
- announcement panel
- error panel
- warning panel
- error summary
- error details

Bar the error components, these will be named in the style of 'panel - information' to keep them together in the side nav of the components section in the DS.

**Comment by OscarJackson** [comment]
I have now drafted these individually in the Service Manual Preview https://service-manual-en-preview-prod.gcp.onsdigital.uk/design-system/components

They all seem to display out of alphabetical order in the side menu though. @alessioventuriniAND do you know how I get them to display i alphabetical order?
