### ISSUE TITLE
Add documentation for "Table of contents" component

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1965]
https://ons-design-system.netlify.app/components/table-of-contents/

Should reference "Guide" page pattern

Navigation component required to show on guide section.

Displays top level parent and next level children. 

Current page is a string only.

Linked to #456

https://sdc-prototypes.netlify.app/prototypes/census-website/about-the-census/

![image](https://user-images.githubusercontent.com/97620554/153228653-fff25550-29b1-4902-aacb-2233c25ba360.png)

**Comment by jrbarnes9** [comment]
https://trello.com/c/qCjmKKBx/558-design-system-table-of-contents

**Comment by emilymaylawes** [comment]
@alessioventuriniAND  are you able to resolve this in the service manual? :)

https://service-manual.ons.gov.uk/design-system/patterns/guide

Content changes ready to go?
