### ISSUE TITLE
Add documentation for "Timeline" component

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1966]
https://ons-design-system.netlify.app/components/timeline/

**Comment by jrbarnes9** [comment]
https://trello.com/c/wQrcsg0d/568-design-system-timeline

**Comment by yatesn** [comment]
Oscar has drafted this - needs to be reviewed

**Comment by emilymaylawes** [comment]
Reviewed content but waiting for follow up questions

**Comment by emilymaylawes** [comment]
Draft now live as published version. Content reviewed and okay, however raises a potential enhancement to this component that may result in further content changes down the line.

**Comment by emilymaylawes** [comment]
Raised enhancement #2694
