### ISSUE TITLE
Add documentation for "Access codes" pattern

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1968]
The access codes pattern requires documentation

https://ons-design-system.netlify.app/patterns/uac/

**Comment by jrbarnes9** [comment]
Added to content design epic: https://trello.com/c/1wBGbk9Q/569-epic-design-system-patterns-where-there-is-little-or-no-documentation-or-it-needs-a-review

**Comment by daniellecorke** [comment]
This is a duplicated ticket - I will link to the other ticket for info and close this one.
