### ISSUE TITLE
Relationship pattern documentation

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1971]
Review and refine documentation

https://ons-design-system.netlify.app/patterns/relationships/

Linked to #466

https://sdc-prototypes.netlify.com/prototypes/relationships/

https://www.sketch.com/s/AYxvy

**Comment by jrbarnes9** [comment]
https://trello.com/c/1wBGbk9Q/569-epic-design-system-patterns-where-there-is-little-or-no-documentation-or-it-needs-a-review
