### ISSUE TITLE
Add documentation for "Hub and Spoke" pattern

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1977]
https://ons-design-system.netlify.app/patterns/hub-and-spoke/

Linked #350 #376

ONS-EQCensus-HubAndSpokeTemplate.sketch

To do:
- Implement Aria attributes to articulate to a respondent the different statuses of a section (Not started, Partially complete and Complete)
- Implement Aria attributes enabling a respondent to navigate to a section, link statuses (Start section, Continue with section and View answers
- Implement focus state to include the whole area so a respondent understands the whole row is clickable

Comment:
Leon Rose - Awaiting Lists to be implemented 
Will Richards - @charlottehirst1 I've moved this over to ready for dev so that @benmeyrick can implement the frontend stuff needed

**Comment by jrbarnes9** [comment]
Done as part of #1758
