### ISSUE TITLE
Create guidance sections on 'the makeup of...'

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1979]
Need guidance on the composition of a questionnaire, internal service etc.

To do:
Include guidance on making labels and legends headings in eQ guidance

**Comment by OscarJackson** [comment]
This is more of a nice but might be worth looking into after we're done with higher priority sections (community, accessibility, pattern and component docs)

Would encompass user centered survey design guidance: https://analysisfunction.civilservice.gov.uk/policy-store/a-user-centred-design-approach-to-surveys/

As well as creating a process re' patterns such as 'survey introduction page', 'survey section introduction page' etc.
