### ISSUE TITLE
Document utility classes etc.

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#1982]
Need to document all the utility style override classes.  Should these all sit in one place e.g. 'get started'? or could they be separated in to styles sections e.g. 'spacing' etc.

Comments:
seduuards - From performance testing, it was found that utility classes along with their separate media queries defined are adding too much bloat to the CSS. As discussed with @benmeyrick , we should look to remove the dependency on using utility classes and only include the minimal amount of grid classes that are needed.

**Comment by daniellecorke** [comment]
This ticket has been split into two separate tickets as linked above. Closing this ticket.
