### ISSUE TITLE
Check welsh translations in 'change language' example

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#1995]
Note: Check against https://cyfrifiad.gov.uk/ and confirm with Prysg.

-----

Hello, where do I raise any problems with the translation itself please? I can confirm the attached is incorrect and should be:

Cysylltwch a ni 
Cwcis a phreifatrwydd

Additionally the "a" in "Cysylltwch a ni" needs a circumflex which I'm not sure how to input.

<img width="250" alt="welsh translation" src="https://user-images.githubusercontent.com/46898565/154922746-3e960185-422d-4a66-a5fb-f1bdbaef2b0c.PNG">

_Originally posted by @elthorne in https://github.com/ONSdigital/design-system/discussions/1391#discussioncomment-2219182_

**Comment by armstrongb** [comment]
`â` can be input inline as (alt + a with the Welsh keyboard enabled on Mac or by holding down `a` for a couple of seconds and then hitting the appropriate number to get circumflex.
To encode it use ```&acirc;```

**Comment by jrbarnes9** [comment]
Correct translations confirmed:

> Cysylltu â ni
> 
> Cwcis ac preifatrwydd
