### ISSUE TITLE
[Bug]: Header mobile logo docs need updating

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#2026]
### What happened?

Docs don't reflect header macro

### What was the expected outcome?

![image](https://user-images.githubusercontent.com/42928680/156767406-ce598f2a-eb0a-4f2f-9ebe-bffe46ef602a.png)
![image](https://user-images.githubusercontent.com/42928680/156767441-5e0a337e-db8d-430a-ba4b-8df1b6db525a.png)
Docs need to be updated to say that the default for mobile logo is `ons-logo-stacked- + language code`

### How is this problem impacting your service?

N/A

### What list of steps can be followed to reproduce the bug or issue?

Compare docs on this page with the macro https://ons-design-system.netlify.app/components/header/

### What version of the ONS Design System are you using?

Latest

### What devices are you seeing the problem on?

- [ ] Desktop
- [ ] Mobile
- [ ] Tablet

### What operating systems are you seeing the problem on?

- [ ] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Other

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer
- [ ] Other

**Comment by jrbarnes9** [comment]
Outdated by #2491
