### ISSUE TITLE
[Feature]: Move 'link' mode of `button` component into a dedicated `link-button` component

### ISSUE THREAD

**Issue by kruncher** [ONSdigital/design-system#2048]
### What feature would you like to add to the ONS Design System?

Move the 'link' functionality from the `button` component into a new dedicated `link-button` component.

### Why should this new feature be added to the Design System?

Currently the `button` component mixes two concerns, that of outputting real buttons and that of outputting hyperlinks which look like buttons. Whilst the styling is similar, the two concepts are configured and function differently.

Having a dedicated `link-button` component will lead to:
- Two simpler macro implementations which are easier to test.
- Simplify the documentation (for example, macro parameters).

**Comment by jrbarnes9** [comment]
The main concern in doing this, is that users might not be able to find the component. If it looks like a button, they'll look under button. We'd have to refer to it in the button docs. 'Call to action' is probably the most appropriate name for it; as we were going to remove that component anyway (because it wasn't used), we could repurpose the docs for just the link/button.

**Comment by yatesn** [comment]
Wait for DAC outcome

**Comment by yatesn** [comment]
Not reported as an issue by DAC - could be tech improvement though

**Comment by boxadesign** [comment]
Having looked at this and split the two components out (https://github.com/ONSdigital/design-system/pull/2581) I feel there is too much crossover in configuration to warrant this change and it would mean any changes to one component would need to developer to be aware that this change may need to be repicated in the other version, this is the bit that i'm not happy about.

Happy to hear Lea's thoughts on this so will put on hold pending that discussion.

Logic around icon positioning, types of icons and the overall structure of each implementation is identical, its only the actual tag used (a or button) that changes and then some additional button attributes for that implementation.
