### ISSUE TITLE
[Enhancement]: Naming of the "Access Code" or "UAC" component

### ISSUE THREAD

**Issue by kruncher** [ONSdigital/design-system#2049]
### What feature would you like to add to the ONS Design System?

The naming of the component and macro should be consistent; for example, `access-code` and `onsAccessCode` or `uac` and `onsUac`. My preference would be the former since it is clear as to what this component is.

### Why should this new feature be added to the Design System?

In addition to making the component consistent with other components; this also means that the naming conventions within the component conform to the same technical standard which simplifies other tasks such as unit testing.

**Comment by jrbarnes9** [comment]
Does this even need to be its own component? Could it not just be a variant of input, and the pattern uses the input with panels etc to build up what's required?
