### ISSUE TITLE
[Bug]: The "Access Code" component does not have consistent BEM classes

### ISSUE THREAD

**Issue by kruncher** [ONSdigital/design-system#2050]
## What happened?

The `access-code` component does not markup generated output with BEM classes.

## What was the expected outcome?

The generated HTML elements should have classes that follow the BEM naming convention; for example, the root element should have the class `ons-access-code` or `ons-uac` (depending on which name we want to use for this component).

**Comment by jrbarnes9** [comment]
Does this even need to be its own component? Could it not just be a variant of input, and the pattern uses the input with panels etc to build up what's required?

**Comment by yatesn** [comment]
Closed, covered by #2074
