### ISSUE TITLE
[Feature]: Add automated tests to verify components work with the Jinja2 templating engine

### ISSUE THREAD

**Issue by kruncher** [ONSdigital/design-system#2051]
## What feature would you like to add to the ONS Design System?

Automated testing of component macros with the Jinja2 templating engine.

Whilst it might not be feasible to maintain a full Jinja2 test suite; it might be a good idea to have tests covering known issues with the Jinja2 templating engine to avoid regressions.

## Why should this new feature be added to the Design System?

The design system uses the [Nunjucks](https://mozilla.github.io/nunjucks/) templating engine which allows us to create templates that are also compatible with the Python [Jinja2](https://palletsprojects.com/p/jinja/) templating engine.

Despite it being possible to develop templates that are compatible with both templating engines, there are situations where templates do not work with Jinja2. Since we target both of these templating engines with the ONS Design System, it would be useful to have automated testing to verify that components work with Jinja2.

**Comment by alessioventuriniAND** [comment]
#3086 This is the solution we have found to the issue raised in this ticket.
