### ISSUE TITLE
Remove Python specific syntax from all occurrences of `itemsList`

### ISSUE THREAD

**Issue by kruncher** [ONSdigital/design-system#2055]
At the moment the templates include the following logic for iterating over an `itemsList`:

```nunjucks
{% for item in (params.itemsList if params.itemsList is iterable else params.itemsList.items()) %}
```

This is because with Python a dictionary value is being provided for `itemsList`:

```nunjucks
{{
  onsList({
    itemsList: someDictionary
  })
}}
```

We could reduce the complexity of our macro templates by reducing our iteration logic to the following:

```nunjucks
{% for item in params.itemsList %}
```

The user code can then add `.items()` as shown below:

```nunjucks
{{
  onsList({
    itemsList: someDictionary.items()
  })
}}
```

**Comment by kruncher** [comment]
Can we actually do this? it would require that user code be updated.

**Comment by yatesn** [comment]
@rmccar - we would like to move forward with this, can you test moving the python specific code into eQ?

**Comment by rmccar** [comment]
> @rmccar - we would like to move forward with this, can you test moving the python specific code into eQ? We will look to issue comms and discuss this in the next monthly forum

I have tested this change in eQ and it doesn't actually seem to be a breaking change for us
