### ISSUE TITLE
Content element of feedback component does not have a BEM class

### ISSUE THREAD

**Issue by kruncher** [ONSdigital/design-system#2066]
The `content` element of the feedback is output as a plain `<p>` element without any BEM class:

```html
<p>Feedback content text...</p>
```

Instead this should be:

```html
<p class="feedback__content">Feedback content text...</p>
```

Because:
- Facilitates any styling needs.
- Makes it simpler to select the output element for testing.

**Comment by willcAND** [comment]
This ticket has already been implemented, closing.



![Image](https://github.com/ONSdigital/design-system/assets/131372109/97f19f05-54a2-4e8b-b3c7-e6fed4684b28)
