### ISSUE TITLE
Naming of icons component does not match naming of `onsIcon` macro and BEM appears to be `ons-svg-icon`

### ISSUE THREAD

**Issue by kruncher** [ONSdigital/design-system#2071]
The component and macro should take one of the following forms:

- Component Name: `icon` Macro Name: `onsIcon`
- Component Name: `icons` Macro Name: `onsIcons` (doesn't really make sense)

BEM class appears to be `ons-svg-icon` rather than `ons-icon`.

**Comment by yatesn** [comment]
Maybe a breaking change

**Comment by kruncher** [comment]
Similar to #2100
