### ISSUE TITLE
Refactor the access code component

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#2074]
### What feature would you like to add to the ONS Design System?

Refactor the access code component and create a variant of the input - links to #2049

### Why should this new feature be added to the Design System?
The access code component is really just type/variant of input combined with other components - so really a pattern which could be manually built by the user.

To solve #2049

**Comment by precious-onyenaucheya-ons** [comment]
The access code component is quite complex as it adopts the use of several components as well as specific css and js classes.
So refactoring to a variant of input or pattern can't be done without changing the current implementation. This ticket will be closed for now, but will have to  rename the component from UACInput to access-code.
