### ISSUE TITLE
Allow ability to provide more than one mutually exclusive option

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#2082]
Allow having more than one mutually exclusive option. If the number of options is more than one make them radios if its only one then it will still be a checkbox

**Comment by jrbarnes9** [comment]
@rmccar  Could do with some more info here to understand the use cases, and user research etc.

**Comment by rmccar** [comment]
Heres the details from the Runner card

**Goal**
To allow the respondent to provide more than one mutually exclusive option

**Why do we want to do this?**
Often there is a need for more than one mutually exclusive answer option, such as "Don't know" and "Prefer not to say. These are mutually exclusive answer options which appear under a checkbox answer type. 

When the mutually exclusive checkbox is selected, the above checkboxes are unchecked as a result. 

**User story**
**As a** respondent
**I want** to be able to be able to give an accurate answer as to why any of the previous checkbox answers do not apply. 
**so that** I can provide accurate data.

**Hypothesis**
By adding another mutually exclusive answer option
we will be able to collect more specific information
because often there is a 'don't know' or 'prefer not to say' answer option. 

**Prototype**
https://eq-v2-prototypes.herokuapp.com/utilities-social-survey/v1/about-your-household/benefits-received

**Assumptions**
1 mutually exclusive option would be a checkbox, while multiple mutually exclusive options would need to be radios
There would be one 'OR' in between first answers and mutually exclusive options

**User research and testing**

**Related survey**
BICS, all social surveys

**Acceptance criteria (user perspective)**

GIVEN a respondent is answering a survey
WHEN any answer type is used
AND more than one mutually exclusive answer option is available
THEN the respondent will select the relevant mutually exclusive radio option 
AND the non mutually exclusive answer(s) will be unchecked

GIVEN a respondent is answering a survey
WHEN any answer type is used
AND more than one mutually exclusive answer option is available
THEN the respondent will select/enter the relevant answer option 
AND any selected mutually exclusive radio will be unselected

Number of mutually exclusive options is configurable and there is no limit
 
**Acceptance criteria (tech perspective)**

** Technical details**:

- DS component needs updating to support radio options for mutually exclusive options. (Implemented via a separate card)
- Validator to support both Checkbox/Radio for the exclusive answer.
- Make the appropriate changes to runner to support a single checkbox option or multiple radio options.
   - Ensure validation and summaries behave as expected.
   - Radio options should be cleared.
   - Ensure the submission payload is as expected.
   - New functional tests.
- communicate schema config changes to the Author team

xxx
 
**Out of scope**
Input answer with a mutually exclusive answer to the input fields: https://eq-v2-prototypes.herokuapp.com/utilities-social-survey/v1/about-your-household/contact-you
- Clearing mutually exclusive radio options when you do not have JS.

**Comment by jrbarnes9** [comment]
@rmccar Is there a UR report for this we can see?

**Comment by rmccar** [comment]
> @rmccar Is there a UR report for this we can see?

Ill send it to you
