### ISSUE TITLE
[Bug]: Outputs invalid classes when optional parameters `termCol` and `descriptionCol` are not provided to metadata component

### ISSUE THREAD

**Issue by kruncher** [ONSdigital/design-system#2084]
Either a default value should be assumed for each of these parameters when unspecified; or no column class should be output.

**Invalid Output:** `ons-col-@m`

**Comment by alec-hamilton-ons** [comment]
Closing issue following discussion with @rmccar & @alessioventuriniAND. The params mentioned are not optional so the changes are not necessary.
