### ISSUE TITLE
Have external-link component use the icon component rather than hard-coding the svg

### ISSUE THREAD

**Issue by kruncher** [ONSdigital/design-system#2088]
To workaround some sort of spacing issue the `external-link` component has the icon hard-coded as an svg directly into the template:

```
{# Icon needed to be directly put here instead of calling macro to solve an issue with extra space on the end of links being underlined #}
```

Instead the `icon` component should be used and adjusted as needed so that it works in this situation.

## Benefits:
- Better quality unit test.
- Avoid duplication of svg data in generated bundle.
- One source of truth for the "external-link" icon.

**Comment by kruncher** [comment]
The macro tests should be updated to use the new `templateFaker().spy('icons')` functionality (see macro tests in button for an example on how to do this).

**Comment by yatesn** [comment]
This issue needs to be solved first https://github.com/ONSdigital/design-system/issues/2873
