### ISSUE TITLE
Runner error panel spacing issue

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#2092]
![image](https://user-images.githubusercontent.com/42928680/160380288-8851becd-8d95-4756-9f7f-98b5db1cb015.png)

**Comment by jrbarnes9** [comment]
@rmccar This looks like a dupe of #1896?

**Comment by rmccar** [comment]
> @rmccar This looks like a dupe of #1896?

Yeah looks like it, do you want me to close it and link my PR to the other one?
