### ISSUE TITLE
Invalid attribute `name` on message body `div` when `messageName` is provided for `message` component

### ISSUE THREAD

**Issue by kruncher** [ONSdigital/design-system#2108]
The `message` component outputs an invalid attribute `name` on a `div` element:

> Error: Attribute name not allowed on element dl at this point.

This occurs in rendered output when the documented parameter `messageName` is provided.

**Comment by kruncher** [comment]
No test added for this parameter since output is invalid and usage isn't clear.

**Comment by jrbarnes9** [comment]
`name` is also an invalid attribute on `dl` element set by `params.name`
