### ISSUE TITLE
`selectAllChildren` in the revealed checkboxes variant of `onsCheckboxes` doesn't work when multiple instances are present

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2113]
### What happened?

When more than one checkbox contains an `"'otherType": 'checkboxes'`, `selectAllChildren` only works for the first group of checkboxes.

### What was the expected outcome?

Multiple instances of revealed checkboxes should work independently with `selectAllChildren`.

### How is this problem impacting your service?

Unable to complete build of DAC prototype 

### What list of steps can be followed to reproduce the bug or issue?

1. Add at least 2 checkboxes with revealed `otherType: checkboxes` both with `selectAllChildren: true`.
2. Select the second parent checkbox
3. Children are not selected

### Example

https://user-images.githubusercontent.com/43346934/161251687-e3096340-08be-4521-b1cc-de94d0c7543b.mp4

### What version of the ONS Design System are you using?

47.0.0

### What devices are you seeing the problem on?

- [X] Desktop
- [X] Mobile
- [X] Tablet

### What operating systems are you seeing the problem on?

- [ ] Windows
- [X] macOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Operating system details

10.14.6

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer
- [ ] Other

### Browser details

Version 99.0.4844.83 (Official Build) (x86_64)

**Comment by jrbarnes9** [comment]
@yatesn I need this one in current Sprint backlog please. It needs to be fixed for DAC test proto.

**Comment by kruncher** [comment]
My initial thought on this one was that each group of checkboxes need to be initialised inside "checkboxes.dom.js" (atm it seems like they are all treated as a single group).

I added the following to grab all checkbox elements and then group them by fieldset; and then to initialise the checkboxes of each fieldset:

```javascript
  const checkboxesByFieldset = [...document.querySelectorAll('.ons-js-checkbox')]
    .map(checkbox => [
      checkbox,
      checkbox.closest('.ons-fieldset'),
    ]);

  const fieldsets = new Set(checkboxesByFieldset.map(entry => entry[1]));
  for (let fieldset of fieldsets) {
    const checkboxes = checkboxesByFieldset
      .filter(entry => entry[1] === fieldset)
      .map(entry => entry[0]);
```

**Comment by boxadesign** [comment]
@kruncher Whats the current status of this? Do you have this work on a branch?

**Comment by kruncher** [comment]
@boxadesign there is no branch, I was experimenting locally to diagnose/fix the issue but my changes didn't have much impact to the problem. I pasted in a comment above the most significant part which I think might contribute to a solution.
