### ISSUE TITLE
[Bug]: Sticky Table of Contents active link state is inconsistent

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2121]
### What happened?

When using the 'sticky' variant of the table of contents component, the 'active' state of the link to show which section is in view, doesn't always work. It seems to only work when the subsequent section is also in the viewport.

### What was the expected outcome?

The active state should always show which section you are reading

### How is this problem impacting your service?

Affecting DAC proto for May 2022

### What list of steps can be followed to reproduce the bug or issue?

1. Build a page using the sticky variant of the Table of Contents component
2. Create sections that are longer than the viewport
3. Observe the link list for active state bold styling when the relating section hits the top of the viewport.

### Example

https://user-images.githubusercontent.com/43346934/161253018-ae38a6aa-541e-4e37-bd06-d8061aa07905.mp4

### What version of the ONS Design System are you using?

47.0.0

### What devices are you seeing the problem on?

- [X] Desktop
- [ ] Mobile
- [ ] Tablet

### What operating systems are you seeing the problem on?

- [ ] Windows
- [X] macOS
- [ ] Android
- [ ] iOS
- [ ] Other

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer
- [ ] Other

**Comment by kruncher** [comment]
With this one I think it might be worth fetching all heading elements with `document.querySelector` and then enumerating over them in reverse order to pick the one closest to the top pixel of the view area.

It might be necessary to cap the rate at which this takes place for performance reasons... perhaps `setTimeout` for 100 if a timeout hasn't already been scheduled.
