### ISSUE TITLE
Access code input width should automatically adapt according to the `maxlength`, `groupSize` and `type` parameters

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2127]
Access code input width should automatically adapt according to the `maxlength`, `groupSize` and `type` parameters

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/1360#discussioncomment-2507055_

**Comment by precious-onyenaucheya-ons** [comment]
This component is rather complex as the width  to be set is being overridden by existing css classes, one of which is the ons-input class, modifying this class will do a lot of damage  so I will close this ticket for now.
