### ISSUE TITLE
Simplify button macro

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2128]
Currently there's a mix of `buttonStyle`, `type`, `submitType` and `variants` params, which could be aligned so all correct attributes and classes are applied when just the variant is set.

Can `buttonContext` and `newWindowDescription` also be merged? No (19/07)

**Comment by yatesn** [comment]
Needs to be done before REACT work

**Comment by jrbarnes9** [comment]
Includes #2047
