### ISSUE TITLE
Add Mutually Exclusive User Research

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2155]
## Mutually Exclusive User Research
tested as part of eQ usability testing 7 March 2022

* Participants clear that if they selected a top answer, then subsequently selected an answer from the ‘or’ section, their other answers would be removed when testing with Multiple Exclusive Answer Options
* Participants clear when only one mutually exclusive answer present, however this became less clear when the question asked for contact details, and the OR read 'I do not wish to be contacted' - participants related this to you are collecting my details but I don't want you to contact me in any way. It was less obvious in this scenario that the 'or' answer would clear previously entered contact details

_Originally posted by @Al-Davies in https://github.com/ONSdigital/design-system/discussions/29#discussioncomment-2331452_

**Comment by OscarJackson** [comment]
Going to be doing some work on this component changing it to a variant of each of the radios, input etc. so will add this in then
