### ISSUE TITLE
Add a default value to Mutually Exclusive and radios 'or' parameter

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2156]
The label will always be 'or' so unless the service is translated, it shouldn't need to set this parameter.

**Comment by yatesn** [comment]
Hard code text content

**Comment by precious-onyenaucheya-ons** [comment]
Adding a default value to the radio component would force users to have the parameter even when its is not required.  In my opinion,  Users should add the "or" parameter based on usage/requirement.

So default value can be added only to the mutually-exclusive component where it is required.
