### ISSUE TITLE
Update legacy 'type' parameters to align with 'variants'

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2159]
Some components use parameters such as 'type' to set the different variants. This ticket is to update those so all components use the 'variants' parameter. 

Components include:
- Input (`params.type` - sets `type` attr. but “text” is used for number type)
- Panel (`params.type` & `params.spacious`)
- Status (`params.type` & `params.size`)
- Character check limit (`params.type`)

**Comment by precious-onyenaucheya-ons** [comment]
Additional clarification and a technical discussion are needed for the implementation of this change in the Panel and Status components. Each of these components currently employs parameters with two different use cases.

**Comment by yatesn** [comment]
Consider breaking down per component

**Comment by daniellecorke** [comment]
To be started after the unnecessary conditionals work.
