### ISSUE TITLE
Remove conditional checks surrounding required parameters since they are required and should always be present

### ISSUE THREAD

**Issue by kruncher** [ONSdigital/design-system#2161]
As an example, in the following scenario the `autosuggestData` is a required parameter (as per documentation):

```nunjucks
{% if params.autosuggestData is defined and params.autosuggestData %}data-autosuggest-data="{{ params.autosuggestData }}"{% endif %}
```

Instead this should just be:

```nunjucks
data-autosuggest-data="{{ params.autosuggestData }}"
```

**Comment by willcAND** [comment]
autosuggestData parameter is only required when not using the address index api.

**Comment by yatesn** [comment]
Check other components for similar issues

**Comment by balibirchlee** [comment]
I have explored all components for similar issues and created tickets for each instance to investigate further and rectify any issues; a total of 14 tickets have been created to this end.

The original instance cited and similar instances (i.e. where something is required unless provided elsewhere) need to retain their conditionals given that whilst the content is required the parameter itself is not.
