### ISSUE TITLE
Password enhancements

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2166]
Consider applying the lessons learned by gov uk on the password component: https://technology.blog.gov.uk/2021/04/19/simple-things-are-complicated-making-a-show-password-option/

- Read the article
- Identify potential for additional documentation and recommendations

**Comment by daniellecorke** [comment]
Read the article, identify potential for additional documentation and recommendations. Speak to Tech Leads re. consistency in password setting.

**Comment by daniellecorke** [comment]
Passwords not used in eQ - contact Author or RASRM instead.
