### ISSUE TITLE
Promo banner should allow setting of background image graphic and use white text by default

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2167]
Promo banner should allow setting of background image graphic and use white text by default

The background gradient is made up of the branded colour variables, so the text should always be white. `darkTheme` parameter can be removed. 

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/730#discussioncomment-2688306_

**Comment by yatesn** [comment]
Component has been removed
