### ISSUE TITLE
Autosuggest - allow all available params to be passed to the `onsInput` macro

### ISSUE THREAD

**Issue by boxadesign** [ONSdigital/design-system#2172]
The autosuggest uses the input macro but only passes in a selection of params. I don't think these have been hand picked they're probably based on some old version of it and seems to be a bit arbitrary. 

I think we should probably create a new param object `input: params.input ` and allow all available input params to be passed into it. 

It would also make the macro options cleaner as we could just reference the input macro and link to it (as we do with other components) (edited)

**Comment by yatesn** [comment]
Refactor after React is built
