### ISSUE TITLE
Add Pagination variant where number of pages is unknown

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2178]
Rather than using primary buttons as this service below is doing, we should adapt the pagination component to allow display of only next/prev links. 

![Screenshot 2022-04-12 at 15 08 08](https://user-images.githubusercontent.com/15887464/162981166-bb8f14a6-679e-428d-ad3d-23c0551ad9da.png)

I  don't think we would need to allow the select component to be called within the pagination links. It would make more sense to left-align the next/prev pagination links and right-align  the select component as per ons.gov.uk search results:

![Screenshot 2022-05-10 at 10 30 52](https://user-images.githubusercontent.com/43346934/167597298-cbb56732-4578-48b4-9cb0-f64d0d73c91b.png)

_Originally posted by @JoelClemence in https://github.com/ONSdigital/design-system/discussions/1385#discussioncomment-2552463_

**Comment by yatesn** [comment]
Not doing as select can be used as a separate component
