### ISSUE TITLE
Select.js doesn't handle multiple instances of the component on the same page

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2181]
Select.js doesn't handle multiple instances of the component on the same page

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/1385#discussioncomment-2721905_

**Comment by yatesn** [comment]
Component is/was specific to census, raise ticket to remove access help in multiple languages pattern and associated code to be removed
