### ISSUE TITLE
[Feature]: Allow onsCheckboxes (and other components) in onsTables

### ISSUE THREAD

**Issue by mfcrocker** [ONSdigital/design-system#2184]
### What feature would you like to add to the ONS Design System?

It should be possible to allow onsCheckbox components to be displayed in an onsTable, especially as part of the form. There are a couple of ways this could be done, but in my opinion it might be best to change the `form.button` attribute to allow a number of different DS components to be added to cells (probably limited to a particular list; you likely don't want people putting onsTables inside onsTable cells!)

### Why should this new feature be added to the Design System?

This is the current bit of design that requires the functionality:

![image](https://user-images.githubusercontent.com/6749550/167827103-67ca7c74-80e8-4273-a7a0-607637c5b78d.png)

This design has been worked on by our UX and UR people and agreed throughout. 

I've checked in with @rmccar to see if there's anything in the design system that would help us and he couldn't think of anything. I think this would be best served as an enhancement to onsTable rather than as an entirely new component

### Supporting material

If you can get on our Figma, its here: https://www.figma.com/file/ddcNwp4TK6CwPqBkOEfDY4/rOps---Role-based-access?node-id=329%3A6454

### Contacts

Developer: Matt Crocker
Designer: Dina Poku
User Researcher: Promise Michael
Product Manager: Alina Tarnawska
Tech Lead: Mark Price

**Comment by jrbarnes9** [comment]
For full context, the user case is for selecting a users account permissions

![Screenshot 2022-05-11 at 16 35 03](https://user-images.githubusercontent.com/43346934/167890264-698cb3a5-409e-48b5-acec-59eb9f4d7a81.png)
