### ISSUE TITLE
Document list component - Featured item config and logic improvements

### ISSUE THREAD

**Issue by boxadesign** [ONSdigital/design-system#2196]
For a document list item to be set as "featured" there is the property `featured: true` this adds a class that handles the styling of that item. There is also the optional parameters `fullWidth: bool` and `wide: bool`. 

The documentation and macro options state that these should be used only when `featured: true`. Also, the check for `wide` is only made inside the check for `fullWidth`. You can set `fullWidth` without setting `featured` which would break layout.

This could be improved by creating something like a `featured` object (that also accepts a boolean value) and then nest the two additional properties and use better key naming such as `fullBleedBackground: bool` and `wideContainer1280: bool`  or something to that effect.

**Comment by yatesn** [comment]
Split featured article into own component. Part of BEM work/React component work
