### ISSUE TITLE
Dates

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#22]
Use this issue to discuss the [Dates pattern](https://ons-design-system.netlify.com/patterns/dates) in the ONS Design System

**Comment by bameyrick** [comment]
It would be good to be able to set attributes on each input element to add things like autocomplete parameters.

**Comment by bameyrick** [comment]
The date input example should have a mode to render it as a question, where the legend is a H1 and the description is 1rem with the margin moved to below the description rather than between the legend and description. The individual field labels should also be bold.

**Comment by bameyrick** [comment]
The date input component wraps itself in a fieldset even if it's only configured to ask for one field (e.g. just the year field)

**Comment by bameyrick** [comment]
When the date component is configured to only show one field, the fields are incorrectly wrapped in a `field-group`

![Screenshot 2019-07-16 at 15 14 32](https://user-images.githubusercontent.com/8447446/61301737-6fb09d00-a7dc-11e9-9035-ce6996bc4105.png)

**Comment by jrbarnes9** [comment]
Users have fed back frustrations around the ability to add more than two or four characters in the date inputs.  This is especially frustrating for users who expect auto-tabbing, because they end up entering everything into the first input (which is too small to easily edit/delete)
