### ISSUE TITLE
Additional `attributes` parameter are added to both the `<select>` and `<option>` elements on the `select` component

### ISSUE THREAD

**Issue by kruncher** [ONSdigital/design-system#2203]
![Image](https://user-images.githubusercontent.com/554215/169816286-05070b13-862c-4d05-b914-c4fe4d86ca9b.png)

If additional `attributes` are needed on a per-option basis then it should be `option.attributes` rather than `params.attributes` which currently would produce an odd output.

**Comment by yatesn** [comment]
Breaking changes?
