### ISSUE TITLE
[Bug]: Section navigation shows both links as active

### ISSUE THREAD

**Issue by JoelClemence** [ONSdigital/design-system#2206]
### What happened?

We have the following section navigation:

```
{{
        onsSectionNavigation({
            "id": "results-navigation",
            "currentPath": path,
            "itemsList": [
                {
                    "title": "Results Runs",
                    "url": "/results"
                },
                {
                    "title": "Finalisation Dashboard",
                    "url": "/results/dashboards/finalisation"
                }
            ]
        })
    }}
```

Expecting the Finalisation dashboard to be the only active section when the user has navigated to the finalisation dashboard however, both sections are shown as active
![Screenshot 2022-05-23 at 17 22 25](https://user-images.githubusercontent.com/15887464/169864028-da3ee5f8-3f78-47f9-ab7a-1644f22227df.png)

I believe the problematic line is https://github.com/ONSdigital/design-system/blob/c09a5ca64384b9bb0ce5c02506087de155a87a77/src/components/section-navigation/_macro.njk#L5 where it checks whether the url is in the current url

### What was the expected outcome?

When on the First section the 'Results' section to be marked as active and when on the 'Finalisation Dashboard' the finalisation dashboard is the only section which is active

### How is this problem impacting your service?

Confusing to the users which section they are on.

This is currently not yet released to users

### What list of steps can be followed to reproduce the bug or issue?

Create a section nav whereby one of the sections is at a higher level in the url chain i.e. 

```
{{
        onsSectionNavigation({
            "id": "results-navigation",
            "currentPath": params.path,
            "itemsList": [
                {
                    "title": "Results Runs",
                    "url": "/results"
                },
                {
                    "title": "Finalisation Dashboard",
                    "url": "/results/dashboards/finalisation"
                }
            ]
        })
    }}
```

### Example

![Screenshot 2022-05-23 at 17 22 25](https://user-images.githubusercontent.com/15887464/169864767-347e1f91-216d-4f65-a508-a2485fa1d3a8.png)

### What version of the ONS Design System are you using?

49.2.0

### What devices are you seeing the problem on?

- [X] Desktop
- [ ] Mobile
- [ ] Tablet

### What operating systems are you seeing the problem on?

- [ ] Windows
- [X] macOS
- [ ] Android
- [ ] iOS
- [ ] Other

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer
- [X] Other

### Browser details

Brave (chromium)

**Comment by kruncher** [comment]
This issue is caused by `item.url in params.currentPath` in the following (for visual style):
```nunjucks
{{ ' ons-section-nav__item--active' if (item.url == params.currentPath) or (item.url in params.currentPath) or (params.tabQuery == item.title|lower) }}
```
and (for aria-current)
```nunjucks
{% if (item.url == params.currentPath) or (item.url in params.currentPath) or (params.tabQuery == item.title|lower) %}
```
