### ISSUE TITLE
Invalid output:`table` component outputs `name` attribute for `tr`/`td` entries when `tr.name`/`td.name` is provided

### ISSUE THREAD

**Issue by kruncher** [ONSdigital/design-system#2222]
The following usage causes a `name` attribute to be rendered:
```nunjucks
{{
  onsTable({
    ths: [
      { value: 'Column 1' },
    ],
    trs: [
      {
        name: 'test-row',
        tds: [
          {
            value: 'Row 1 Cell 1',
            name: 'test-cell',
          },
        ],
      },
    ],
  })
}}
```

It is not valid HTML to have a `name` attribute on `<tr>` or `<td>` elements.

**Comment by alec-hamilton-ons** [comment]
@rmccar 

Hi Richard, 
I am going to remove the ability for the Table component to set `name` attributes to `<tr>` & `<td>` elements as it is invalid html.
Is your team using the Table component and if so can you forsee this change being an issue for you?
Thank you

**Comment by rmccar** [comment]
> @rmccar
> 
> Hi Richard, I am going to remove the ability for the Table component to set `name` attributes to `<tr>` & `<td>` elements as it is invalid html. Is your team using the Table component and if so can you forsee this change being an issue for you? Thank you

Hi Alec, sounds like a good change to me. But my team doesn't use the table component. I do think the RAS/RM team does use the table component though if you did want to get in touch with a team that does use it.

**Comment by alec-hamilton-ons** [comment]
Thanks Richard, could you suggest someone to reach out to because I do not know anyone from that team.

**Comment by rmccar** [comment]
> Thanks Richard, could you suggest someone to reach out to because I do not know anyone from that team.

Mark Price is the Tech Lead on RASRM so he's probably the best person to speak to

**Comment by alec-hamilton-ons** [comment]
Thanks Richard & Hi Mark @pricem14pc ,
As per Richard and I's conversation above, I am going to make changes to the Table component by removing the option to add name attributes. As your team is using the component, I wanted to check to see if this is going to be a significantly impactful breaking change for you?
