### ISSUE TITLE
[Feature]: Multi-header tables

### ISSUE THREAD

**Issue by JoelClemence** [ONSdigital/design-system#2224]
### What feature would you like to add to the ONS Design System?

We have the requirement to display two column headings (one with a col span over several columns) to achieve something like:

```html
<table>
    <thead>
        <tr>
            <th colspan=1></th>
            <th colspan=2>Period: 1</th>
            <th colspan=2>Period: 2</th>
        </tr>
        <tr>
            <th>identifier</th>
            <th>Sum</th>
            <th>Count</th>
            <th>Sum</th>
            <th>Count</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>123</th>
            <td>2</td>
            <td>2</td>
            <td>2</td>
            <td>2</td>
         </tr>
    </tbody>
</table>
```

### Why should this new feature be added to the Design System?

We are displaying a table showing the comparison between periods i.e. illustrating how businesses have changed month on month over different attributes. The users require this in order to analyse the data held in the Statistical Production Platform in order to carry out their day to day activities.

### Supporting material

We have a modified ONS Design system table: https://github.com/ONSdigital/spp-results-ui/blob/main/src/spp_results_ui/ui/templates/results_components/table/_macro.njk in order for us to achieve this

### Contacts

Joel Clemence (@JoelClemence, Software Engineer)
Mike Candlin (@kingmushroom, Software Engineer)
Ab Day (Delivery Manager)
Holly Putnam (Business Analyst)
Product Manager (vacant)

**Comment by JoelClemence** [comment]
We also have a related requirement to apply column shading over colgroups and we have acheived this using the following nunjucks:
```
             {%- if params.colgroup is defined and params.colgroup -%}
                    <colgroup>
                        {%- for colgroup in params.colgroup -%}
                            <col {{ 'span="' ~ colgroup.span ~ '" ' if colgroup.span is defined and colgroup.span }} {{'class="' ~ colgroup.classes ~'" ' if colgroup.classes is defined and colgroup.classes}}>
                        {%- endfor -%}
                    </colgroup>
                {%- endif -%}
```

**Comment by yatesn** [comment]
Closing due to #2352
