### ISSUE TITLE
Improve button usage guidance

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2227]
We've seen many services recently using multiple primary buttons on the same page.  Perhaps the current guidance ("Avoid using multiple primary buttons on the same page because it will reduce the impact and make it hard for users to know what to do next." ) isn't clear enough? 
Or do we need to make the secondary style the "default", so they have to actively choose which button to make the primary call to action?

**Comment by OscarJackson** [comment]
I'm not sure that this is needed now.

We've changed the documentation so the guidance is in an information panel so it's really hard to miss:



![Image](https://github.com/ONSdigital/design-system/assets/115987412/f4ebc010-6954-4f0d-abd8-eae8c7d36063)


Also, if we create a pattern of what not to do, we run the risk of people not reading documentation at all and then using what they see in the example.
