### ISSUE TITLE
Hide `submitButton` when question macro is used in component examples

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2228]
In component examples (like checkboxes), we just want to show the question heading (for context) and the answer component. However, because some component examples are using the Question macro, which renders `submitButton` by default, it's showing up in these component examples.

We should consider using the `dsExample` flag to remove the button when not required in component examples.

![Screenshot 2022-06-08 at 14 25 26](https://user-images.githubusercontent.com/43346934/172628826-dd30e555-b156-4e08-b8c4-30bd5633be30.png)

**Comment by yatesn** [comment]
Done - #2286
