### ISSUE TITLE
Section navigation menu items are not uniquely named (WCAG Level AA)

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2244]
From Page 60 of the June 2022 DAC DS report...

---

## Non-Descriptive Names
Elements are present that do not contain a descriptive name.

WCAG Reference:
2.4.6 Headings and Labels (Level AA)
Understanding Headings and Labels |How to Meet Headings and Labels

### Issue ID: DAC_Non_Descriptive_Names_01

URL: https://ons-sub-nav-prototypes.netlify.app/prototypes/sub-navigation/service-manual/design-system/guidance/install-with-npm/
Page title: Install with npm
Journey: Journey 4, Step 5

Screenshot:
![Screenshot 2022-06-16 at 14 54 30](https://user-images.githubusercontent.com/43346934/174085773-32648376-9f42-440d-a72e-a0fcb8efdc4b.png)

There are three navigation regions next to the main content of the page. These navigation regions begin with the headings ‘Installing the design system’, ‘Testing your service’, and ‘Design guides’. The navigation regions contain an aria-label with a value of sub menu, meaning that they’re not uniquely named. This could be problematic to screen reader users, as it could be difficult to understand the differences of the navigation regions. Additionally, the unordered lists within the navigation regions also share the same accessible name.

### Current code ref(s):

#section-navigation 
```
<nav class="ons-section-nav ons-section-nav--vertical" id="section-navigation" aria-label="Sub menu"> <ul class="ons-section-nav__list" aria-label="Child menu"> […] </nav>
```
#section-navigation 
```
<nav class="ons-section-nav ons-section-nav--vertical" id="section-navigation" aria-label="Sub menu"> <ul class="ons-section-nav__list" aria-label="Child menu"> […] </nav>
```
#section-navigation 
```
<nav class="ons-section-nav ons-section-nav--vertical" id="section-navigation" aria-label="Sub menu"> <ul class="ons-section-nav__list" aria-label="Child menu"> […] </nav>
```

### Solution:
To make it easier for screen reader users to understand the purpose of the navigation regions on the page, we advise that each navigation region has a unique accessible name. We also advise removing the aria-label from the unordered lists.

For example: 
```
<nav class="ons-section-nav ons-section-nav--vertical" id="section-navigation" aria-label="Installing the Design System"> <ul class="ons-section-nav__list" aria-label="Child menu"> […] </nav>
```

**Comment by boxadesign** [comment]
@jrbarnes9 Just to not that this is an implementation issue in the DS. In `_page.njk` we provide this value inside a loop so just need to exchange the string 'Sub menu' with `group.title` variable.
