### ISSUE TITLE
Add padding for when duration fields stack

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2280]
No padding when duration fields stack
![Screenshot 2022-06-27 at 17 15 43](https://user-images.githubusercontent.com/43346934/175987599-32f282fd-307a-4a4e-8e44-fdc5511e469d.png)

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/19#discussioncomment-3032842_

**Comment by rmccar** [comment]
Duplicate 👍

**Comment by rmccar** [comment]
Closed wrong one
