### ISSUE TITLE
Census specific script inside cookies pattern documentation

### ISSUE THREAD

**Issue by kruncher** [ONSdigital/design-system#2306]
I'm not sure if this is intended; but the following is included in the cookies pattern documentation:

```html
    <script>
        if (!navigator.onLine) {
            console.log('You\'re offline');
            const link  = document.createElement('link');
            link.rel  = 'stylesheet';
            link.href = '/css/census.css';

            document.head.appendChild(link);
        }
    </script>
```

**Comment by yatesn** [comment]
Remove all census script? Check when decommissioning is happening

**Comment by alessioventuriniAND** [comment]
The census website has been decommissioned and the above code can now be removed.

**Comment by alessioventuriniAND** [comment]
Looks like this has already been removed. Closing as no action is needed
