### ISSUE TITLE
DS search results unable to be selected on smaller screens

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#2328]
DS search results is put behind the page title on smaller screens and is unable to be clicked on

![Screenshot 2022-07-15 at 10 25 28](https://user-images.githubusercontent.com/42928680/179195855-4d50ce16-4632-4abf-8ecb-a8b03d4214ea.png)

**Comment by boxadesign** [comment]
@rmccar Just to add this only seems to be an issue when the hero is used.
