### ISSUE TITLE
Rebuild Table Macro

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#2352]
Current table macro is over-complicated, to cater for specific needs because using the macro is inflexible by itself. Just providing BEM classes should provide solution for most users.

**Comment by jrbarnes9** [comment]
When this work is done, we should ensure the default table is responsive and all the following issues are resolved:
- #2586 
- #2493 
- #2477 
- #2354 
- #2222 
- #2195 
- #2076

**Comment by willcAND** [comment]
Removed documentation child ticket (#2076) from work associated with table macro as this work is based around wider components.
