### ISSUE TITLE
Only add `tabindex` to `ons-table-scrollable__content` if the table doesn't fit in the viewport. When it doesn't need to be scrolled, the user shouldn't be able to give focus to the table content.

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2354]
Only add `tabindex` to `ons-table-scrollable__content` if the table doesn't fit in the viewport. When it doesn't need to be scrolled, the user shouldn't be able to give focus to the table content.

![Screenshot 2022-07-25 at 16 29 36](https://user-images.githubusercontent.com/43346934/180816926-24fe30e2-2077-4355-8ff4-501cd7512ec9.png)

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/102#discussioncomment-3223610_

**Comment by yatesn** [comment]
Table component/macro likely to be removed
