### ISSUE TITLE
Document that Jinja2 projects should configure `undefined` to use `ChainedUndefined`

### ISSUE THREAD

**Issue by kruncher** [ONSdigital/design-system#2358]
Further information regarding this can be found in the Jinja2 docs: https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.Undefined

Add the following import:
```python
from jinja2 import ChainableUndefined
```

and the following configuration change:
```python
jinja_env.undefined = ChainableUndefined
```

**Comment by kruncher** [comment]
Relates to https://github.com/ONSdigital/eq-questionnaire-runner/pull/909

**Comment by jrbarnes9** [comment]
@kruncher Is this linked to #1931?

**Comment by kruncher** [comment]
> @kruncher Is this linked to #1931?

Yes, there should be less to document overall in terms if Jinja2 support if the chainable undefined config works in eQ when testing the PR #2359 

There is a separate piece about documenting how iterables should be provided to things like itemsList parameters such that the DS doesn't need to know python app specifics.
