### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by bameyrick** [ONSdigital/design-system#236]
Use this issue to discuss the [Feedback pattern](https://ons-design-system.netlify.com/patterns/feedback) in the [ONS Design System](https://ons-design-system.netlify.com)

**Comment by jrbarnes9** [comment]
Feedback Mailto link contains a full stop so invalid when copied and pasted.

**Comment by rmccar** [comment]
https://github.com/ONSdigital/design-system/blob/3fbea5e0371e96926ef7e1fa06f02a893773bde7/src/tests/spec/feedback/feedback.spec.js#L89 Test needs looking at as always passes. I needs to test that the message is visible not if it exists
