### ISSUE TITLE
[Bug]: Inline select controls have differing margins

### ISSUE THREAD

**Issue by JoelClemence** [ONSdigital/design-system#2369]
### What happened?

We have two/three select controls that are in line with each other using the grid `ons-grid__col ons-col-2@m`, however the first always has a margin top of 1.25em where as others have a margin top of 1.5em therefore they are not aligned.

![Screenshot 2022-08-04 at 09 04 36](https://user-images.githubusercontent.com/15887464/182796393-af76e815-4b25-428b-aaa2-cb9fd3b6c174.png)

### What was the expected outcome?

The two selects to be inline with eachother

### How is this problem impacting your service?

We have had to introduce a class to our first select which corrects its margin and handle the case where there are two selects on a page we have added these styling here too

### What list of steps can be followed to reproduce the bug or issue?

Nunjucks/Jinja template:
```
<section id="data_controls" class="ons-container--full-width" aria-label="Data controls">
{% set select_one_options = ... %}
{% set select_two_options = ... %}
{{
                onsSelect({
                    "id": "question_identifier",
                    "name": "question_identifier",
                    "classes": "ons-input--block",
                    "fieldClases": "ons-grid__col ons-col-2@m",
                    "label": {
                        "text": "Question Number",
                    },
                    "options": select_one_options
                })
            }}

   {{
        onsSelect({
        "id":"selectid",
        "name": "name",
        "classes": "ons-input--block",
        "fieldClases": "ons-grid__col ons-col-2@m",
        "label": {
            "text": "label",
        },
        "options": select_two_options
    })
    }}
</section>
```

### Example

![Screenshot 2022-08-04 at 09 04 36](https://user-images.githubusercontent.com/15887464/182796393-af76e815-4b25-428b-aaa2-cb9fd3b6c174.png)

### What version of the ONS Design System are you using?

48.0.3

### What devices are you seeing the problem on?

- [X] Desktop
- [ ] Mobile
- [ ] Tablet

### Device details

Brave

### What operating systems are you seeing the problem on?

- [ ] Windows
- [X] macOS
- [ ] Android
- [ ] iOS
- [ ] Other

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer
- [ ] Other

**Comment by jrbarnes9** [comment]
@JoelClemence If you use divs for the grid layout rather than adding the grid classes to the component's field, you shouldn't get this problem. The space is added to allow multiple fields to be stacked vertically in a form.

```
{% from "components/select/_macro.njk" import onsSelect %}
<div class="ons-grid__col ons-col-2@m">
    {{
        onsSelect({
            "id": "question_identifier",
            "name": "question_identifier",
            "classes": "ons-input--block",
            "label": {
                "text": "Question Number"
            },
            "options": [
                {
                    "value": "",
                    "text": "Select an option",
                    "disabled": true,
                    "selected": true
                },
                {
                    "value": 1,
                    "text": "General"
                }
            ]
        })
    }}
</div>
<div class="ons-grid__col ons-col-2@m">
    {{
        onsSelect({
            "id": "question_identifier",
            "name": "question_identifier",
            "classes": "ons-input--block",
            "label": {
                "text": "Question Number"
            },
            "options": [
                {
                    "value": "",
                    "text": "Select an option",
                    "disabled": true,
                    "selected": true
                },
                {
                    "value": 1,
                    "text": "General"
                }
            ]
        })
    }}
```

**Comment by boxadesign** [comment]
@JoelClemence I would suggest removing `classes` and `fieldClasses` from your configuration and implenting some flex BEM classes such as below:

```
<div class="ons-grid ons-grid--gutterless ons-grid--flex">
    <div class="ons-grid__col ons-u-mr-s@m ons-u-mb-s">
        {{
            onsSelect({ ... })
        }}
    </div>
    <div class="ons-grid__col">
        {{
            onsSelect({ ... })
       }}
    </div>
</div>
```

This would give you something shown in this video...

[Screen recording 2022-08-04 13.14.08.webm](https://user-images.githubusercontent.com/1015442/182846182-6bab763a-28c9-4a86-9e87-af97133ed598.webm)

**Comment by JoelClemence** [comment]
Thanks @jrbarnes9 / @boxadesign - I have added a ticket to our jira to investigate a fix as suggested by yourselves.
