### ISSUE TITLE
Bug: Cookie banner Jinja params issue

### ISSUE THREAD

**Issue by Paul-Joel** [ONSdigital/design-system#2385]
Bug: Revised cookie banner code in 54.0.1 errors when used in Jinja if no params are provided. Params are not being tested they exist before trying to use them, a common issue between nunjucks and jinja code

_Originally posted by @Paul-Joel in https://github.com/ONSdigital/design-system/discussions/715#discussioncomment-3364613_

**Comment by boxadesign** [comment]
@Paul-Joel We have updated the guidance for using Jinja2 as we found a helpful package that stops this kind of issue ->
https://ons-design-system.netlify.app/guidance/using-nunjucks/
