### ISSUE TITLE
Fix hero element for use with Jinja.

### ISSUE THREAD

**Issue by BenLatham** [ONSdigital/design-system#2386]
The hero element as implemented is not compatible with jinja, causing any pages where it is imported to fail to render. This is due to the use of the replace filter with a regex. The regex is not recognised by Jinja, and is interpreted as a syntactical error. As a consequence the failure occurs even if the if block containing the regex is not executed.

**Comment by boxadesign** [comment]
Hi @BenLatham Do you need to use the prop `preTitleImage`? I imagine that jinja is throwing the error regardless when rendering the nunjucks. Either way, looking at the code its unnecessary to have the regex and can be removed and replaced with something more simple.

**Comment by boxadesign** [comment]
@BenLatham I have created a PR to fix the issue -> https://github.com/ONSdigital/design-system/pull/2388
