### ISSUE TITLE
Adding support for GTM to modals

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#2403]
On eQ we need to have GTM events fired for:
- When the modal is opened 
- When the modal is closed
- The type of modal (timeout / regular)
- If it is a timeout one, when the user clicks the button to extend the session

So we would like support added for GTM events for these so this information can be passed to GTM/GA.

**Comment by yatesn** [comment]
@rmccar could you advise when you need this done please?

**Comment by rmccar** [comment]
> @rmccar could you advise when you need this done please?

As soon as possible really because we are currently missing the analytics for this
