### ISSUE TITLE
Use `background-image` for "opens in new window" icon in the `external-link` component

### ISSUE THREAD

**Issue by kruncher** [ONSdigital/design-system#2440]
At the moment the icon is embedded as an `<svg>` inside each occurrence of the `external-link` component which adds a lot of weight to information pages.

**Comment by boxadesign** [comment]
I'm not convinced we should jump on to this one just yet. I don't like using bg images that have to have hover/focus states. 

With inline svg this is simple and effective as we have access to the `:fill` property. With bg svgs we have to create colour versions of each svg and swap them out on hover/focus where you get the dreaded flash before the first image swap and also the burden of creating multiple colour variations for wherever it needs to be applied e.g. branded heros, promos, etc.

This I think is interesting: https://css-tricks.com/change-color-of-svg-on-hover/#aa-svg-symbol-use

But this would require the svg to be available somewhere in the page (only once so not using the macro) and then reference it. This would help keep the page weight down.
