### ISSUE TITLE
Timeout modal remaining time is inaccurate to screen reader users

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2442]
When testing the timeout modal with a screenreader (NVDA) I noticed it by the time it read out `countdownText`, the time announced was ~5 seconds behind the time visible on the page. So the user would be signed out sooner than expected.

Is there a way to ensure the time read out is exactly as displayed, rather than at the end of the long `countdownText` string?

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/1771#discussioncomment-3626267_

**Comment by boxadesign** [comment]
Closing this issue as in reality its probably not an issue for real users who speed up the read out and there is a long timeframe to decide what to do
