### ISSUE TITLE
Document the `siteSearchAutosuggest` option of the page template

### ISSUE THREAD

**Issue by kruncher** [ONSdigital/design-system#2453]
This feature was exposed for the PR #2452 

This would also be a good opportunity to review naming, etc of this option.

**Comment by rmccar** [comment]
Review the documentation around this param in the header component and see what we need to add. To the params table and/or service manual

**Comment by SriHV** [comment]
This was already checked in  #3112 where it was decided that as 'siteSearchAutosuggest' is only used through 'autosuggest' component, it is not need to add it here.
