### ISSUE TITLE
Related content component can't be used within the `block aside` in the base page template, because it currently uses `aside` itself.

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2457]
Related content component can't be used within the `block aside` in the base page template, because it currently uses `aside` itself.

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/1283#discussioncomment-3736021_

**Comment by yatesn** [comment]
Is this a notable issue? If not, should not be changed
