### ISSUE TITLE
Phase banner: Review most semantically appropriate and accessible tag for badge

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2462]
Looking at the HTML for this component, the BETA itself is wrapped in a H3 tag. Given its position on the page, this means (from what I could make out on Voiceover) that it appears as the first heading. Would this potentially be confusing for users flicking through the headers to just hear 'Beta' and nothing else? 
Within the GOV.UK Design System, they seem to use a strong tag instead. Consequently it's not read out when navigating through the various headers on the page.

_Originally posted by @LaurenDowling in https://github.com/ONSdigital/design-system/discussions/8#discussioncomment-3753862_

**Comment by boxadesign** [comment]
Waiting for advice from DAC to see if we need to add aria attributes the wrapping element

**Comment by yatesn** [comment]
Still waiting for response from DAC

**Comment by jrbarnes9** [comment]
Response from DAC:

> "I discussed this with my colleagues, and we concluded that adding an alert could be too intrusive. Since users move through a webpage linearly, they’ll see the banner on each new page. As you mentioned, the user may skip the phase banner. Although, this most likely happens if the user has seen the page before."

**Comment by emilymaylawes** [comment]
Based on the comment above, is it best to change this to a `<strong>` tag, considering users may skip over the phase banner after reading it once?
At the moment, having it as a `<h3>` does not make explicit sense as to why this level was selected, as it does not sit underneath any other content, and there is a question as to why it isn't even a `<h2>`. It is the only semantic heading inside the `<header>`> as well which grants it significant important as the first heading on the page.
My recommendation would be to make it a `<strong>` element as proposed, and as GDS do.
