### ISSUE TITLE
Formatting issues with macro options table

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#2477]
![Screenshot 2022-10-06 at 13 06 12](https://user-images.githubusercontent.com/42928680/194308327-28d8e82e-8ec0-4eb3-a99f-fd9ba5a28ad9.png)

Macro options table content currently starts overflowing its container when the page with is reduced to around 820px

**Comment by alessioventuriniAND** [comment]
this is an issue related to the service manual and it has been fixed with this PR https://github.com/ONSdigital/ons-service-manual-website/pull/271
