### ISSUE TITLE
[Bug]: sortable table variant sort icon not active

### ISSUE THREAD

**Issue by bambrp** [ONSdigital/design-system#2493]
### What happened?

When using the sortable table variant, the SVG "double arrow" icon in the column header does nothing when clicked, as opposed to the text of the column header, which performs the sort action.

### What was the expected outcome?

That it would perform the sort action, same as clicking on the column text.

### How is this problem impacting your service?

Users assessing the platform raised it as a bug with us, it is their belief visitors to the site may be confused. I'm really just the messenger here.

### What list of steps can be followed to reproduce the bug or issue?

Visit documentation at https://ons-design-system.netlify.app/components/table/#sortable-table and try to click the icons in the provided example.

### What version of the ONS Design System are you using?

55.1.0 (although exists in current version too)

### What devices are you seeing the problem on?

- [X] Desktop
- [ ] Mobile
- [ ] Tablet

### What operating systems are you seeing the problem on?

- [X] Windows
- [X] macOS
- [ ] Android
- [ ] iOS
- [ ] Other

### What browsers are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [ ] Safari
- [X] Microsoft Edge
- [ ] Microsoft Internet Explorer
- [ ] Other

**Comment by jrbarnes9** [comment]
The icon is part of the `<button>` but doesn't activate the sort on click.
