### ISSUE TITLE
`.ons-summary__spacer` does not match the height of the action links

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2506]
`.ons-summary__spacer` does not match the height of the action links
![Screenshot 2022-10-24 at 10 00 40](https://user-images.githubusercontent.com/43346934/197489127-4c868f1e-99a0-45f7-bef8-40fbc4b8f81e.png)

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/1386#discussioncomment-3948792_

**Comment by yatesn** [comment]
@rmccar can you look at this please?

**Comment by rmccar** [comment]
> @rmccar can you look at this please?

Yeah I can look into this, Ill need to make some changes soon to the summary anyway
