### ISSUE TITLE
iFrame resizer doesn't resize after feedback component closes.

### ISSUE THREAD

**Issue by boxadesign** [ONSdigital/design-system#253]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: (e.g. iOS)
- Browser (e.g. chrome, safari)
- Version (e.g. 22)

**Smartphone (please complete the following information):**

- Device: (e.g. iPhone6)
- OS: (e.g. iOS8.1)
- Browser (e.g. stock browser, safari)
- Version (e.g. 22)

**Additional context**

**Comment by bameyrick** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [iFrame resizer](https://trello.com/c/FdS0PzPF/198-iframe-resizer)
