### ISSUE TITLE
Change language pattern documentation

### ISSUE THREAD

**Issue by boxadesign** [ONSdigital/design-system#2551]
The change language pattern https://ons-design-system.netlify.app/patterns/change-language/ shows examples where there are more than 2 available languages. 

There's some broken logic for small screen widths and as we don't have any real world use of more than English/Welsh we should just remove the pattern example showing more than 2 langs and re wriet the documentation.

The docs state that the language would be displayed in the footer on small screen widths but this isn't true and was updated so that the language toggle is retained in the header.

**Comment by jrbarnes9** [comment]
New content for review: https://trello.com/c/kfKRboYi/530-review-content-for-change-language-pattern
