### ISSUE TITLE
"Metadata" does not accurately describe the component

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2558]
We've received feedback from our users that they expected to find something different under the documentation of the 'metadata' component. Users expected to find a way to add `<meta>` tags to the template `<head>` rather than a component for description lists.

Content design has suggested we rename the component to 'Description list' to better reflect the component and underlying html element.

**Comment by jrbarnes9** [comment]
Instead of doing this, @kruncher has agreed to raise a ticket to remove this as a component, and document as a class only style, ensuring all the issues he encountered trying to use this component in IDS are resolved.

**Comment by kruncher** [comment]
Ticket raised #2570

**Comment by kruncher** [comment]
Issue will be handled as a part of #2570
