### ISSUE TITLE
Header on a different page to content when printing

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#2584]
When printing a page that is longer that what would fit onto one side of A4 the header is being put onto a separate page to the content

<img width="1262" alt="Screenshot 2023-01-18 at 14 31 56" src="https://user-images.githubusercontent.com/42928680/214045634-4041080d-3161-430b-845b-a8000b93f3c4.png">
<img width="1263" alt="Screenshot 2023-01-18 at 14 32 14" src="https://user-images.githubusercontent.com/42928680/214045651-11582c58-2445-4491-b9ef-cc5c59f98fb7.png">

**Comment by jrbarnes9** [comment]
Seems to only affect Chrome
