### ISSUE TITLE
Summary card

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2590]
eQ recently encountered new use cases with list collectors within grouped summaries. It would be worth reviewing the recent enhancement to the gov.uk design system ('summary card') as a possible solution: https://github.com/alphagov/govuk-design-system-backlog/issues/210

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/1386#discussioncomment-4798726_

**Comment by yatesn** [comment]
Awaiting eQ designer

**Comment by Majsol** [comment]
...maybe chat with the IxD community
