### ISSUE TITLE
Page URL link is dead

### ISSUE THREAD

**Issue by JNATION85** [ONSdigital/design-system#2660]
Need to investigate where this URL is: https://service-manual.ons.gov.uk/design-system/guidance/page-titles-and-urls/#page-titles

![Image](https://user-images.githubusercontent.com/41283876/239497081-d94c7b69-8a6d-4005-b47e-06b51a89131a.PNG)

**Comment by willcAND** [comment]
Guidance page for `page-titles-and-urls` no longer exists - which is why link is not working.
