### ISSUE TITLE
Add 'ONS' to titles

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#2701]
Would it useful to add ‘ONS’ to the title on the home page (and elsewhere) to differentiate it from, say, the [government service manual](https://www.gov.uk/service-manual)? (As we’re using similar looks & feel)

From an internal ONS user, 23/06/2023

**Comment by yatesn** [comment]
@JNATION85 Thoughts?

**Comment by Majsol** [comment]
The logo is already there so I don't think it is needed, but it doesn't do any harm either

**Comment by OscarJackson** [comment]
I think this is more of a nice to have and shouldn't make too much difference either way.

Echo what Dina says about and in SERPs we have it as: 

![Image](https://github.com/ONSdigital/design-system/assets/115987412/68388900-bd7f-48d9-a017-432b5b79b162)

The title and the favicon differentiate it from other service manuals, so no concerns there.

In summary, lets add it in if it's easy, but if not I wouldn't bother.

**Comment by OscarJackson** [comment]
Side note: just noticed 'ages' is linked from the homepage with a cookies summary. Not sure what's going on there.
