### ISSUE TITLE
[Service Manual] Style guide inaccuracies following first release

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#2703]
Some inaccuracies to make you aware of in the content style guide within the service manual. 

[Measurements and units](https://service-manual.ons.gov.uk/content/numbers/measurements-and-units)

This section mentions “Use metric units of measurement, except in specific cases where imperial units are still used as standard” and shows “acres (for land registration)”
In fact acres are no longer permitted for land registration and have been replaced by hectares (source: https://ukma.org.uk/the-case-for-change/policy-areas/land-and-property-policy/)

The abbreviation ‘kph’ for kilometres per hour is shown. In fact the internationally accepted abbreviation is ‘km/h’ (source: https://en.wikipedia.org/wiki/Kilometres_per_hour).  

[Countries and regions](https://service-manual.ons.gov.uk/content/language/countries-and-regions)

In the section Subnational areas there are references to ‘health geographies’ – this is a term no longer used, ‘clinical commissioning groups’ and ‘Birmingham Local Authority’. The CCG health geography has now been replaced by ‘sub integrated care board locations’. The example provided ‘NHS Richmond Clinical Commissioning Group’ no longer exists and didn’t show the correct statutory name anyway, so I suggest this reference is deleted. 

When referring to specific local authorities, the correct council name should be used, so ‘Birmingham City Council’ rather than ‘Birmingham Local Authority’ (and when referring to the geographical area covered by a local authority, then just show the local authority name eg ‘Birmingham’).

**Comment by elidakirigo** [comment]
hi, I'd like to contribute to the documentation of this project.

**Comment by yatesn** [comment]
Passed to Style guide team (DP) for action
