### ISSUE TITLE
Select all that apply cannot be a label or legend

### ISSUE THREAD

**Issue by will-madebymoon** [ONSdigital/design-system#271]
Select all that apply cannot be a label or legend. 
In runner we include 'Select all that apply' as default for all checkbox lists. 
The legend would be Pizza toppings or Passports
The styling is also incorrect. See screenshot

<img width="418" alt="screenshot 2019-03-01 at 15 17 12" src="https://user-images.githubusercontent.com/8184622/53647629-dec69400-3c35-11e9-8f1d-4bc6c37a75ab.png">
<img width="472" alt="screenshot 2019-03-01 at 15 17 45" src="https://user-images.githubusercontent.com/8184622/53647612-d66e5900-3c35-11e9-9b4f-510db212eb08.png">

**Comment by bameyrick** [comment]
I'll update it so that the legend is the question and the "Select all that apply" is the "description"
