### ISSUE TITLE
[Bug] titleTag levels above tabs needs to be audited for heading level, as should not all be <h4>

### ISSUE THREAD

**Issue by emilymaylawes** [ONSdigital/design-system#2710]
In relation to https://github.com/ONSdigital/ons-service-manual-website/issues/281, I think a little bit more work needs to be done to audit through all pages of the design system and set the `titleTag` of the tab components displaying the individual component to get the right heading level. On some pages, there are multiple different requirements for heading levels. Some need to be `<h4>` if they are in variants, some need to be `<h3>` if they are under a subheading, some need to be `<h2>` if they are directly under the main page heading.

Probably a bit of spike/investigation/audit work to go through all pages to make sure the `titleTag` (hidden heading above the tabs, which then displays on mobile) the right heading level.

We want to avoid ever skipping heading levels to make the page structure correct and screen reader users able to navigate through in a more accurate manner.

**Comment by yatesn** [comment]
@alessioventuriniAND to start/investigate
