### ISSUE TITLE
Document new Survey Interstitial Page pattern

### ISSUE THREAD

**Issue by alec-hamilton-ons** [ONSdigital/design-system#2720]
A new pattern has been added to the DS - #1644 

We need to add documentation /content for it. There is a lot already in the original ticket linked above

**Comment by Majsol** [comment]
I have added a ticket to the Content design board https://trello.com/c/lFtZb43i

**Comment by Majsol** [comment]
Oscar has added a first draft of this and is going to run it past eQ to make sure it’s ok.

**Comment by Majsol** [comment]
Oscar says that it is all good with eQ, just a few minor changes that have been updated in draft 2. Should be ready to draft into the CMS/for the example component to be built...

**Comment by OscarJackson** [comment]
I have drafted this but it needs review by eQ in RAD session this Friday.

**Comment by OscarJackson** [comment]
This is all good now and ready to go live
