### ISSUE TITLE
Update Error Status page examples to reflect recommended content change

### ISSUE THREAD

**Issue by emilymaylawes** [ONSdigital/design-system#2746]
https://trello.com/c/5f1Gp1Ht/635-design-system-error-status-pages

![Image](https://github.com/ONSdigital/design-system/assets/131370908/4d6f8508-68c1-4e02-8ec8-362d2fc85610)

**Comment by yatesn** [comment]
Investigate to see if there are live patterns available

**Comment by Majsol** [comment]
https://trello.com/c/5f1Gp1Ht

**Comment by Majsol** [comment]
![Image](https://github.com/ONSdigital/design-system/assets/98104925/ca6eb390-ceb2-4b84-bd65-356ab7a87f37)
