### ISSUE TITLE
Create new Error Status page example

### ISSUE THREAD

**Issue by emilymaylawes** [ONSdigital/design-system#2747]
New example proposed looking like the GDS version

https://design-system.service.gov.uk/patterns/service-unavailable-pages/

![Image](https://github.com/ONSdigital/design-system/assets/131370908/b825f8b5-1bfc-481e-a155-a7b92040542d)

**Comment by yatesn** [comment]
Links to https://github.com/ONSdigital/design-system/issues/2746

**Comment by Majsol** [comment]
https://service-manual.ons.gov.uk/design-system/patterns/error-status-pages

Do we need at change all the Error pages in the DS and move the link to the end of the sentence? Or do we just add a new example to list of examples?

**Comment by Majsol** [comment]
![Image](https://github.com/ONSdigital/design-system/assets/98104925/067f0f5b-f5a5-4b73-8b02-2f2763e7ffd3)
