### ISSUE TITLE
Service Manual - Community Pages

### ISSUE THREAD

**Issue by emilymaylawes** [ONSdigital/design-system#2767]
To match the new community pages we need templates for proposing something new, suggesting an enhancement/change and raising a bug.
https://service-manual-en-preview-preprod.gcp.onsdigital.uk/design-system/community

**Comment by JNATION85** [comment]
Working with Oscar for the content changes. Have started implementing them into the pre-prod site. Will need to get UR to test the site. Tree Jack testing would be best

**Comment by JNATION85** [comment]
Content has been uploaded. Need to UR the page
