### ISSUE TITLE
Inputs should have a sensible default width class

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#278]
Inputs should have a sensible default width class (that can be overridden) for certain input types (that have a known max length e.g. postcode) so authors do not need to provide a width each time.

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/163#issuecomment-470497884_

**Comment by bameyrick** [comment]
I think they have a max width for tablet and above (19.5rem), and then anything below that they're 100% width. That was the existing functionality before we added the width modifiers, so I don't think this is something we'd want to change

**Comment by rmccar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #278: Add guidance about the width classes you should apply to specific text inputs like postcode](https://trello.com/c/FPMQfSos/701-issue-278-add-guidance-about-the-width-classes-you-should-apply-to-specific-text-inputs-like-postcode)

**Comment by jrbarnes9** [comment]
This has been documented as guidance for applicable input types: postcode, phone number and numeric values.
