### ISSUE TITLE
Investigate prototype kit requirements

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#2785]
Initially investigate gaps/issues/requirements for the prototype kit, by consulting the immediate community (Rich, Oscar, Dina...)
- Identify themes
- Identify scope
- Review documentation
- Create tickets where possible
- Prepare to approach wider community

**Comment by yatesn** [comment]
Share findings with team > create tickets

**Comment by precious-onyenaucheya-ons** [comment]
From the investigation,

Users make use of the prototype kit template for user testing.

The main issues faced by users are
- inability to link multiple template files to a Javascript file (this causes repetition as javascript is written per template)
- inability to upload json for the autosuggest component
- inability to upload images such as png and jpg 
- documentation not detailing all use case of components

Users also suggested that patterns can be created for
- Sign up and Sign In
- Filtering
