### ISSUE TITLE
Numeric values

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#279]
Use this issue to discuss the [Numeric values pattern](https://ons-design-system.netlify.com/patterns/numeric-values) in the [ONS Design System](https://ons-design-system.netlify.com)

**Comment by saedwards** [comment]
@will-madebymoon Symbols for different numeric value types in the pattern library aren't clickable. Is this expected? When you click the field, the focus surrounds the symbol as well as the field. We could make this clickable, which would really help on mobiles & tablets.

**Comment by armstrongb** [comment]
I don't think that this has been confirmed as an issue.
Suggest that if we want to check if clicking on the 'symbols' is an issue for users that we gather metrics via GTM for clicks on the `<abbr>` element.
