### ISSUE TITLE
Update Documentation 

### ISSUE THREAD

**Issue by precious-onyenaucheya-ons** [ONSdigital/design-system#2814]
Documentation should be updated to detail the entire use case of each component

**Comment by alessioventuriniAND** [comment]
Reach out to community to give us examples of instances where the documentation was not clear or complete for them. We could use the monthly forum to address this question.

**Comment by OscarJackson** [comment]
@alessioventuriniAND @precious-onyenaucheya-ons Is there anything I need to do on this one yet? or is it a case of waiting to see if there's anything people say isn't clear?

**Comment by alessioventuriniAND** [comment]
We have released the new community pages that can be used to provide feedback and raise issue with the team. We also have the monthly forum meeting where the community can raise queries and issue with the team directly.
