### ISSUE TITLE
Allow more than one masthead logo to be set

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#2829]
In some surveys in eQ we need to be able to use two masthead logos next to eachother.
![Screenshot 2023-10-09 at 11 48 36](https://github.com/ONSdigital/design-system/assets/42928680/7a929c01-7dc1-4882-844e-5e4296a07e18)

We currently do this by concatenating the two svgs together and passing them into the `mastheadLogo` param on the header component. This works fine as it is but we now need to use the ONS logo as one of the logos which would be good if we were able to use the ONS logo from the Icon macro but this is complicated within eQ because we concatenate and pass them within python which is then passed to the component.

It would be good if we were able to set more than one masthead logo and we could use logos from the Icons macros if needed or a mixture of passed in SVG and ones from the Icons macro and if we were able to set the order of these logos too.

**Comment by yatesn** [comment]
Spike - investigate whether more than one logo is a good way forward

**Comment by Majsol** [comment]
The reason why there is a need for more than one logo is that ONS are doing a specific survey for more than one department and they potentially both have the same importance. Richard is investigating the need for 2-3 logos in the header a bit more, but it is a requirement from the business.

At the moment eq are making the logo's into one SVG file but that will be an issue if we use the ONS logo in that same way as it wont automatically be updated if there are any changes to the logo. 

I will set up meeting with the Graphic designers to investigate if there is any issues from a brand perspective.

**Comment by Majsol** [comment]
there has not been any UR on this - is it needed?

**Comment by Majsol** [comment]
@JNATION85, Donna mentioned that you might have done some work for EQ where you helped adding 2 logos to an svg file for them? - Were there potentially any research done at that time? Does it work on mobile ect. ?

**Comment by JNATION85** [comment]
I don't remember there being any UR done and I'm not sure I was part of that design process. Seems to me like we'd need to mock it up and see how it looks especially on mobile. From a branding point of view I would be happy to take Andy's advice there. 

We could use the IDS as a reference point but would still need to see 3 logos across the top.

**Comment by rmccar** [comment]
If you want to see how it looks, this is how it currently looks in eQ with the 3 logos. And below is when it starts wrapping when the width goes below 528px. It could definitely be improved on.

<img width="1746" alt="Screenshot 2023-10-27 at 14 53 52" src="https://github.com/ONSdigital/design-system/assets/42928680/2e50d66d-d309-4aeb-a8ec-e1e73dbe00d2">

<img width="498" alt="Screenshot 2023-10-27 at 14 59 57" src="https://github.com/ONSdigital/design-system/assets/42928680/4fd3f0cf-6e00-4299-b6f7-707d38d8f77f">

**Comment by Majsol** [comment]
Donna also mentioned no UR was done, I was more thinking if any accessibility research were done or if it any mockups were done at the time. I do appreciate it might be a long time ago.

**Comment by JNATION85** [comment]
Yeah that looks awful. May need to redesign the header col width at mobile size to span the full width but again this will push everything down. I don't think there will be any accessibility issues, just a really bloated header. 

I'm still not sure If I've ever seen any mockups in this case

**Comment by Majsol** [comment]
There is a need for more logos placed next to each other, so we do need to allow for more than one masthead logo to be set. However the maximum logos should be defined (I suggest 3 as the maximum) and we need to make sure that when there is no space for both the logos and the menu, that the menu is pushed to a new line instead of one of the logos as it is now.
