### ISSUE TITLE
Google Analytics not working needs updating to be compatible with GA4

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#2830]
The Google Analytics event that we are sending in the DS (analytics.js) are no longer working. We need to update it to work with GA4 which is the latest version of GA.

Currently we attempt to send 3 attributes to GA (`data-ga-category`, `data-ga-action` and `data-ga-label`). These are set as custom html attributes on elements we want to track and are then picked up by the js in `analytics.js` and are sent to GA. But currently are not being picked up by GA due to the `ga()` function we use to send them being deprecated and now shut off by Google. We now need to use the `gtag()` function instead.

This new function gives us a bit more scope to make what we send more generic and not stick rigidly to the 3 attributes above. In this new function you can send the data in an object that contains key value pairs.

The proposed solution is to convert the js to use the new function but also remove the hardcoded attributes and instead introduce a new structure that will grab any attributes that start with `data-ga-` remove the `data-ga-` part of the name and add the name and value to the object to be sent to GA with that new name and its value. So for example `data-ga-category` will become just `category`. We do also have an attribute that is called just `data-ga` and this will now be added to the object as `event-name`.

The documentation on using the `gtag()` function is [here](https://developers.google.com/analytics/devguides/collection/ga4/events?client_type=gtag)

All this should also be documented and although we are giving users more of a generic way of setting these things we should outline a suggested structure so that services can all use the same one.

**Comment by alessioventuriniAND** [comment]
I have looked into this and it looks we currently use universal analytics in the DS. I have found this guide that explains how to enable universal analytics support in GA4 which is done through the GA dashboard that Ian Oliver manage : 
https://www.vakulski-group.com/blog/post/analytics-js-ga4-its-possible/#:~:text=Yes%2C%20it's%20possible%20to%20migrate,Analytics%20events%E2%80%9D%20feature%20in%20GA4.

I have had a chat with Ian and he has enabled this option in the Service Manual and he is going to enable it for the rest of the websites. 

I have also shared a guid with him to confirm that this UA is now read by GA4 : 
https://support.google.com/analytics/answer/13342757?hl=en&ref_topic=10737980&sjid=341287973298155195-EU

**Comment by yatesn** [comment]
Now a priority - Precious to pick up

**Comment by precious-onyenaucheya-ons** [comment]
We have set up an environment on EQ using CDN to test this, Just waiting for Ian to run this on the dashboard

But he is currently on leave
