### ISSUE TITLE
Error and status pages - text changes and example component for new use case

### ISSUE THREAD

**Issue by OscarJackson** [ONSdigital/design-system#2832]
https://service-manual.ons.gov.uk/design-system/patterns/error-status-pages#maintenance-notice

The text on the error status pages currently has the link in the middle/at the beginning of a line of text. In order to comply with the style guide, we need to change this so the link appears at the end.

For example, on the page not found error:

If the web address is correct or you selected a link or button, <a href="example">contact us</a> for more help.

Needs to be changed to:

If the web address is correct, or you selected a link or button, <a href="example">contact us</a>.

And on the service unavailable (unexpected error):

<a href="example">Contact us</a> if you need to speak to someone about your survey.

Will need to be changed to:

If you need to speak to someone about your survey, <a href="example">contact us</a>.

This applies to:

- page not found errors
- page not found with reference code
- session timed out errors
- session timed out errors where user is not signed in
- service unavailable error (unexpected error)
- maintenance notice
- browser incompatibility error

Let me know if you need further info on each individual change.

There is also the need for a new example to be created for when we don't know when the service will be available again. This is similar to the GOV.UK 'General page' example here: https://design-system.service.gov.uk/patterns/service-unavailable-pages/

The text on this should say:

<h1>Sorry, this service is unavailable.</h1>

Check back at a later date for more information.

**Comment by precious-onyenaucheya-ons** [comment]
We can ignore adding the service unavailable page for now as we don't have a use case for this. There is a similar example for this in the design system (example-server-error)
