### ISSUE TITLE
[Bug]: Non-Descriptive Labels (Level AA - Accessibility)

### ISSUE THREAD

**Issue by joepercival** [ONSdigital/design-system#2841]
### What happened?

This ticket was raised on the Statistical Methods Library static website: [Link to Non-Descriptive Labels ticket](https://jira.ons.gov.uk/browse/SPP-9452)

### What was the expected outcome?

See ticket

### How is this problem impacting your service?

See ticket

### What list of steps can be followed to reproduce the bug or issue?

See ticket

### What version of the ONS Design System are you using?

62.0.0

### What devices are you seeing the problem on?

- [X] Desktop
- [ ] Mobile
- [ ] Tablet

### What operating systems are you seeing the problem on?

- [ ] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Other

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer
- [ ] Other

**Comment by yatesn** [comment]
Potentially needs to be resolved in SPP, may be some documentation work for DS

**Comment by adi-unni** [comment]
@adi-unni
