### ISSUE TITLE
[Bug]: Contrast Enhanced (Level AAA - Accessibility)

### ISSUE THREAD

**Issue by joepercival** [ONSdigital/design-system#2842]
### What happened?

This issue was raised on the Statistical Methods Library static website: [Link to Contrast Enhanced ticket](https://jira.ons.gov.uk/browse/SPP-9528)

### What was the expected outcome?

See ticket

### How is this problem impacting your service?

See ticket

### What list of steps can be followed to reproduce the bug or issue?

See ticket

### What version of the ONS Design System are you using?

62.0.0

### What devices are you seeing the problem on?

- [X] Desktop
- [ ] Mobile
- [ ] Tablet

### What operating systems are you seeing the problem on?

- [ ] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Other

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer
- [ ] Other

**Comment by Majsol** [comment]
I can't access the ticket - I don't have the right permissions

**Comment by alessioventuriniAND** [comment]
Once Design approach has been decided we can implement the suggested change.

**Comment by JNATION85** [comment]
Linked with https://github.com/orgs/ONSdigital/projects/21/views/1?pane=issue&itemId=5976674

**Comment by Majsol** [comment]
If we make the current link colour (Ocean blue #206095) 4% darker it will pass AAA accessibility. So change the colour to #1F5C8F with the contrast ratio 7.03:1 (the minimum is 7:1)

**Comment by JNATION85** [comment]
Link colour contrast issue as per https://github.com/orgs/ONSdigital/projects/21/views/1?pane=issue&itemId=5976674
