### ISSUE TITLE
[Bug]: Illogical Heading structure (Level AAA - Accessibility)

### ISSUE THREAD

**Issue by joepercival** [ONSdigital/design-system#2845]
### What happened?

This issue was raised on the Statistical Methods Library static website: [Link to Illogical Heading Structure ticket](https://jira.ons.gov.uk/browse/SPP-9556)

### What was the expected outcome?

See ticket

### How is this problem impacting your service?

See ticket

### What list of steps can be followed to reproduce the bug or issue?

See ticket

### What version of the ONS Design System are you using?

62.0.0

### What devices are you seeing the problem on?

- [X] Desktop
- [ ] Mobile
- [ ] Tablet

### What operating systems are you seeing the problem on?

- [ ] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Other

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer
- [ ] Other

**Comment by yatesn** [comment]
May be a SPP issue, not for DS - investigate further

**Comment by precious-onyenaucheya-ons** [comment]
So this is as SPP issue, They need to set the title tag of the details component so it matches the heading level of the page.

The DS currents sets a default of h2 for this component, But it is the user's responsibility to set the correct heading level based on use case.

**Comment by JNATION85** [comment]
@adi-unni

**Comment by adi-unni** [comment]
Fixed on SPP
