### ISSUE TITLE
[Bug]: High Contrast: usability (Level AAA - Accessibility)

### ISSUE THREAD

**Issue by joepercival** [ONSdigital/design-system#2848]
### What happened?

This issue was raised on the Statistical Methods Library static website: [Link to High Contrast; usability ticket](https://jira.ons.gov.uk/browse/SPP-9558)

### What was the expected outcome?

See ticket

### How is this problem impacting your service?

See ticket

### What list of steps can be followed to reproduce the bug or issue?

See ticket

### What version of the ONS Design System are you using?

62.0.0

### What devices are you seeing the problem on?

- [X] Desktop
- [ ] Mobile
- [ ] Tablet

### What operating systems are you seeing the problem on?

- [ ] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Other

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer
- [ ] Other

**Comment by rmccar** [comment]
I think we need Dina to look at this and decide what the hover states should look like and what colours we should use for them. Also should we change the hover states for when high contrast mode is turned on and off or should we just change the hover states when high contrast is on? Im assuming the second option and if thats the case then we can use the `forced-colors` CSS media query to specifically target when high contrast mode is on.

**Comment by alessioventuriniAND** [comment]
@JNATION85 Has highlighted that GDS currently faces the same issue with colours in high contrast mode. A conversation with GDS needs to be started to understand how they would like to approach this or if they are aware of this issue. 

This is not just a design choice but more of a brand choice.

**Comment by JNATION85** [comment]
Need to check the button use but also need to understand the colour choice too. Agree the primary buttons don't have a great deal of contrast on hover.
