### ISSUE TITLE
[Bug]: High Contrast: identifying sort (Level AAA - Accessibility)

### ISSUE THREAD

**Issue by joepercival** [ONSdigital/design-system#2849]
### What happened?

This issue was raised on the Statistical Methods Library static website: [Link to High Contrast: identifying sort ticket](https://jira.ons.gov.uk/browse/SPP-9560)

### What was the expected outcome?

See ticket

### How is this problem impacting your service?

See ticket

### What list of steps can be followed to reproduce the bug or issue?

See ticket

### What version of the ONS Design System are you using?

62.0.0

### What devices are you seeing the problem on?

- [X] Desktop
- [ ] Mobile
- [ ] Tablet

### What operating systems are you seeing the problem on?

- [ ] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Other

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer
- [ ] Other

**Comment by alessioventuriniAND** [comment]
potentially a new colour for the sort svg icon needs to be provided to the devs so that we can update the current svg. 
@JNATION85 @Majsol

**Comment by JNATION85** [comment]
Need to see the SVG icon bigger. Need to check the colour against what we have in the SM
