### ISSUE TITLE
Service Manual query

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#2860]
Hi ONS Design,

I am looking for some guidance in the service manual, but I can’t find it.

I am writing a bulletin and want to know when we can use the word “most”. Does it refer to the most popular option (which may be less than 50%), does it refer to anything over 50% or does it refer to a clear majority (over 70%)?

For example, if 37% of adults prefer Dairy Milk and that is the highest number of votes for any chocolate, can we say “Most adults prefer Diary Milk”?

On a related note, I seem to remember seeing government guidance somewhere about which words to use for different levels of confidence, such as possible (20-30%), “likely” (50-60%), “probably” (60-70%) or something like that (I made up those numbers). Can this be found in or added to the style guide?

Thanks,

Fast Stream Social Researcher | Public Services Analysis Team | Analytical Hub | Public Policy Analysis
Office for National Statistics | Swyddfa Ystadegau Gwladol

**Comment by OscarJackson** [comment]
I'm not sure I've ever seen us be quite this prescriptive with language but it might have been before my time. I'll ask DP to see if anyone knows. 

My worry with this would be that we could document 'most', 'likely', etc. which would help us with their use but a user isn't going to know the background when these phrases are used (e.g. that 'most' is a majority or the most popular) so it'll still be as subjective as if we let people use their own judgement.

We could also end up going down a rabbit hole of defining words in the style guide which would drown out some of the more important points in the style guide and make it a laborious nightmare to write anything.

**Comment by OscarJackson** [comment]
If the person still needs the info though, DP would advise using brackets after the word "most" with the percentage in. For example, 'most (37%) of adults prefer Dairy Milk'
