### ISSUE TITLE
Call Request

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#2863]
Good afternoon,

Please I can arrange a call between someone in the design system team and a software engineer on my team? He has a query about why something isn’t pulling through correctly on the project’s UI. Please see a summary of the issue below and supporting screenshots attached. 

“Using the Nunjucks template without alteration does not display any rows.  They are simply not present in the rendered HTML source, completely missing from the <div>, as seen in the dev console screenshot.”

Any help would be much appreciated.

Thanks

Emma
Emma Haysom | Product Manager | Statistical Production Platform
Office for National Statistics | Swyddfa Ystadegau Gwladol

![Screenshot1](https://github.com/ONSdigital/design-system/assets/97620554/837de4e4-654c-41bd-8ce8-498b8f1505e3)
![Screenshot2](https://github.com/ONSdigital/design-system/assets/97620554/1e022177-bdb8-4b99-b7e3-e6e30d404877)
ital/design-system/assets/97620554/837de4e4-654c-41bd-8ce8-498b8f1505e3)

![Screenshot3](https://github.com/ONSdigital/design-system/assets/97620554/28d18387-4079-46ea-a71f-ad2de8fe625b)

**Comment by rmccar** [comment]
Had call with developer, he needed to update his DS macros to a later version. This fixed his issue.
