### ISSUE TITLE
Details components not showing contents when printed

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#2869]
On eQ currently when using details components to hold some text that text is not being printed unless the details component is already open when printing.

I have already tested one solution of opening all the print dialogs when the print dialog is opened (https://github.com/ONSdigital/design-system/pull/2791) but there is issues with this solution as they would then stay open unless you close them all when the print dialog is closed, which would close any ones that were already open. It would be complicated to fix that. 

The proposed solution is to revert the details components to their original implementation of using js to open and close them. A lot of the work done in this PR (https://github.com/ONSdigital/design-system/pull/2013) would need to be reverted. This should allow us to use the print.css to show/hide the contents on print instead of having the functionality hidden behind the html details element. For non js users the contents would be displayed on the page as paragraphs that couldn't be closed as was before this PR change went in. We need to make sure we take into account any accessibility issues brought up in the PRs. And this will need DAC testing again.

**Comment by JNATION85** [comment]
Is this good enough to add the the print.css file

@media print {
  details {
    open: true;
  }
}

**Comment by rmccar** [comment]
> Is this good enough to add the the print.css file
> 
> @media print { details { open: true; } }

Nah unfortunately it isn't that simple, needs some js to get it to work
