### ISSUE TITLE
Implement component search in the DS front end

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#2872]
Since moving the documentation out of the DS and into craft CMS the front end for the DS is now a bare bones list of links. Would make it a lot quicker to use for devs if we enabled the search functionality of the service manual to get to components more quickly. And removing the padding around full page examples in this front end would make it easier to compare examples.

- The search will work the same as the one on the service manual front page and return suggestions based on what you type in.
- Search will need to work for components, patterns and foundations as the one on the service manual does.
- The autosuggest will return the link to the component page that has the list of example links.
- The search box will need to be added either next to or underneath the Design System title on the root page of the DS.

**Comment by alessioventuriniAND** [comment]
1. Where does the search component need to sit? Inside the pages of each section or at the root? 
2. Is this really needed? 

AV :)

**Comment by rmccar** [comment]
I would put it at the root.
It isn't necessarily needed, this is low priority. But for me I think it would just make my life easier and make it quicker for me to find components/patterns when making changes or testing changes locally on the DS. Before the DS website was broken out into the service manual I found the search really useful and I miss it now.
