### ISSUE TITLE
Allow more than one masthead logo to be set - part 1

### ISSUE THREAD

**Issue by Majsol** [ONSdigital/design-system#2890]
Allow for more than one masthead logo to be set based on the request below. But a maximum 3 logos.

- Allow the ability to set a mixture of the services own svgs passed and ones from the DS icon component.
- Maximum number of icons to be able to be set is 3
- If more than one logo is passed in then we use the stacked or small variant of any logos used from the icon component
- Consider the current way the component is used and decide between two approaches:
1. enable the ability to pass in an array of logos as well as the current implementation of passing one svg in.
2. add extra params for example `mastheadLogo2` and `mastheadLogo3` to enable adding the two extra logos

rmccar
on Oct 9
In some surveys in eQ we need to be able to use two masthead logos next to eachother.

![Image](https://github.com/ONSdigital/design-system/assets/98104925/1a157dca-bab5-4995-a5ad-7c27eccebbc7)

We currently do this by concatenating the two svgs together and passing them into the mastheadLogo param on the header component. This works fine as it is but we now need to use the ONS logo as one of the logos which would be good if we were able to use the ONS logo from the Icon macro but this is complicated within eQ because we concatenate and pass them within python which is then passed to the component.

It would be good if we were able to set more than one masthead logo and we could use logos from the Icons macros if needed or a mixture of passed in SVG and ones from the Icons macro and if we were able to set the order of these logos too.

**Comment by Majsol** [comment]
https://github.com/ONSdigital/design-system/issues/2829

**Comment by balibirchlee** [comment]
started having a look at this to understand the existing code and consider the options for implementation - but not started any proper coding yet
