### ISSUE TITLE
Tests failing locally

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#2941]
At the moment when running `yarn test` there are a number of tests that fail due to importing modules. Needs some investigation into why this is failing.

<img width="766" alt="Screenshot 2023-11-16 at 10 48 39" src="https://github.com/ONSdigital/design-system/assets/42928680/a5354b06-b504-43b7-a5cd-f3c37cd30057">

**Comment by yatesn** [comment]
Working for Alessio, not for Rich

**Comment by rmccar** [comment]
Issue local to my machine doesnt need to be on the board

**Comment by rmccar** [comment]
Have reopened as I have found the cause of this issue now, it requires some changes in the DS repo and could be a problem for others in future
