### ISSUE TITLE
Show tooltip when hovering over input with prefix/suffix

### ISSUE THREAD

**Issue by adi-unni** [ONSdigital/design-system#2946]
Showing the tooltip of an input when they are selected (if is title applicable) would also help the discoverability of the full form label for mobile/sighted users. Currently tooltip is only visible when the user hovers over the `<abbr>` tag using a mouse, however this functionality would not override, but compliment it by displaying the tooltip when the input is selected. Originally from ticket #2411

**Comment by precious-onyenaucheya-ons** [comment]
Closed as not relevant
