### ISSUE TITLE
Importing CSS elements from stylesheets

### ISSUE THREAD

**Issue by adi-unni** [ONSdigital/design-system#2962]
Message from Dr Chris Johnston:

Thanks again for the chat a couple of weeks ago about using the CSS files from the ONS Design System in my RMarkdown HTML outputs.

I just wanted to follow up on that and what we discussed. I’ve managed to get the document to import the formatting from the CDN, so for the most part the formatting is working, but there are some elements I’d like to adjust that don’t seem to work well with the CDN, such as the contents section. We discussed how using formatting for individual elements would require specifying their use specifically in the HTML output. Upon reflection, given our HTML files are relatively lightweight, that would seem to me to be a good solution in our case, as we can customise the elements to our needs and then save them in a template to be used across our documents.

I was wondering if there was a way to do that with the CDN or if I would need to download the CSS elements via node.js? If the former, how do I do this and if the latter, how can I get node.js on my ONS laptop? For reference, this is how I’m importing the CDN into my current RMarkdown outputs:

```
<style type="text/css">

     @import url(https://cdn.ons.gov.uk/sdc/design-system/66.0.1/css/main.css);
</style>
```
Thanks
,
 Chris

Dr Christopher Johnston (he/him)

Public Services Analyst, Public Services Analysis Team, Analytical Hub Division, Public Policy Analysis Directorate

Office for National Statistics | Swyddfa Ystadegau Gwladol

[chris.johnston@ons.gov.uk](mailto:chris.johnston@ons.gov.uk) | [www.ons.gov.uk](http://www.ons.gov.uk/) | [@ONS](http://twitter.com/ONS)

**Comment by alessioventuriniAND** [comment]
I have booked a meeting for Friday 26/01 to talk about this query.

**Comment by alessioventuriniAND** [comment]
I have had a meeting with Christopher and I have advised that to be able to use our components a Jinja or Nunjucks templating environment will need to be set. Christopher will look into this and decide on steps forward.
