### ISSUE TITLE
User journey mapping

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#2963]
Look at the stuff in the red square - https://miro.com/app/board/uXjVPZJcmX4=/?share_link_id=629815664175

Review user stories 
Map out journeys/processes
Gather feedback from users
Identify pain points
Raise tickets accordingly

Priority order:
- Service Manual
- Design System
- Prototype kit

Secondary piece of work relates to stakeholder mapping

**Comment by MagdalenaLarge** [comment]
This epic is no longer required - activities took place in the past.
