### ISSUE TITLE
Investigate using the new html search element

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#2966]
There is a new search element in html which we should investigate and potentially look to implement in the search component on the DS. This looks like it will have some accessibility improvements for us.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/search

**Comment by alessioventuriniAND** [comment]
@rmccar  Looking at the compatible browsers table it looks like two browsers don't support this new search tag. I believe we have to alway use html or css elements that are supported by all browsers or am I wrong? 

What are the support criteria that we have to adhere to?

**Comment by rmccar** [comment]
> @rmccar Looking at the compatible browsers table it looks like two browsers don't support this new search tag. I believe we have to alway use html or css elements that are supported by all browsers or am I wrong?
> 
> What are the support criteria that we have to adhere to?

You're right, we don't support Opera but we do support Samsung Internet. If we can find a Samsung device we could test this on that to see how it responds though.
The list of browsers we support is here:
https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices
Linked from this page on the service manual
https://service-manual.ons.gov.uk/design-system/guidance/browser-testing
