### ISSUE TITLE
Mock up summary card from GOV DS into ONS prototype kit

### ISSUE THREAD

**Issue by JNATION85** [ONSdigital/design-system#2968]
https://trello.com/c/ozBz9HKI/43-mock-up-summary-card-from-gov-ds-into-ons-prototype-kit

Add a new summary variant where the groups are rendered in a card layout as shown in this prototype: https://eq-runner-prototypes.netlify.app/prototypes/summary-card/

- Visual tests will need to be added.
- Add and document the new variant param.
- Add a new example to the summary page that renders the grouped example (https://service-manual.ons.gov.uk/design-system/components/summary/example-summary-grouped) like cards in the prototype.
- Check with Joe if this needs to be documented in the service manual yet or will we just add it to the DS while we are waiting for it to be user researched.

**Comment by alessioventuriniAND** [comment]
@JNATION85 Can you expand a little more on the request here? Are we looking to introduce a new variant to the summary component ? Or do we literally need to create some hardcoded examples in the prototype kit?

**Comment by JNATION85** [comment]
Need to speak with EQ regarding research. The prototype has been mocked up. IxD to be involved

**Comment by alessioventuriniAND** [comment]
We need to create a variant of the summary component to introduce a card variant. The card variant will only be available to the grouped variant of the summary component : 

https://service-manual.ons.gov.uk/design-system/components/summary/example-summary-grouped

This is an experimental approach.

**Comment by JNATION85** [comment]
Reference for guidance https://design-system.service.gov.uk/components/summary-list/#summary-cards
