### ISSUE TITLE
Class ons-grid__col--sticky needs documentation

### ISSUE THREAD

**Issue by adi-unni** [ONSdigital/design-system#2969]
There is a class ons-grid__col--sticky in the design system grid which allows a column of a grid to be sticky whilst the page is scrolled. There is no documentation around this in the grid section of the service manual and a mention is there in the table of contents page. There is a new VR example that can be used example-page-table-of-contents-stick-full-page for creating this documentation.

Links to fix: #2960

**Comment by alessioventuriniAND** [comment]
@OscarJackson Can we take you through this change so you understand more about this and then implement the relevant documentation?

**Comment by alessioventuriniAND** [comment]
this is the path to the example /components/table-of-contents/example-table-of-contents-sticky-full-page.njk
