### ISSUE TITLE
Longer titles too close to button

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#2988]
When using the header component if the header is particularly long and has words that have a space after a certain number of characters so that the title wraps at that point then its possible for the title to be too close to the button

<img width="1089" alt="Screenshot 2024-01-08 at 12 46 56" src="https://github.com/ONSdigital/design-system/assets/42928680/88e11a49-89ef-409e-b98e-2f09c57355a6">

**Comment by JNATION85** [comment]
![Image](https://github.com/ONSdigital/design-system/assets/41283876/f271ee2c-5ba5-4b33-8093-d1eeddf4c5c4)

**Comment by rmccar** [comment]
Technical implementation of this would be to remove the `ons-grid--gutterless` class from the header container grid on 172 in the header macro if there is a exit button specified.
