### ISSUE TITLE
[Bug]: Misalignment of Summary values with long strings during resizing

### ISSUE THREAD

**Issue by JamesT-CTS-ONS** [ONSdigital/design-system#2995]
### What happened?

Using the Summary DS component, if one (or more) of the column values are long continuous strings (such as text with underscores or in this case a long email address) when the page is resized, these values do not move at the same rate as short strings or sections of text split by spaces.

### What was the expected outcome?

All values should move at the same rate when the page is resized.

### How is this problem impacting your service?

Cosmetic.

### What list of steps can be followed to reproduce the bug or issue?

1. Navigate to the IDS Hub Admin site
2. Click 'View Admin Users'.
3. Here you'll see a summary page of users with emails displayed. Choose the user(s) with the longest emails and click change.
4. Drag the page size down and up and observe the different rates the lines move at and how the email address values become misaligned.

### Example

<img width="1792" alt="Screenshot 2024-01-15 at 10 43 34" src="https://github.com/ONSdigital/design-system/assets/112964732/f2c82d35-136e-4dc6-997c-422620854be5">

### What version of the ONS Design System are you using?

62.0.0

### What devices are you seeing the problem on?

Desktop

### Device details

Having discussed with Alessio Venturini he suggested it would affect tablet too.

### What operating systems are you seeing the problem on?

macOS

### What browsers are you seeing the problem on?

Chrome

**Comment by JamesT-CTS-ONS** [comment]
Having spoken to Mitchell, it seems the team was under the impression this should show as fixed automatically at my end, but it hasn't. Additional detail determined since is that the bug manifests on the summary screen when the Change link appears on the right hand side, ie it occurs when the long email is the second column of three, not when the long email is the second column of two. Contact me if you need to see it in action.

**Comment by alessioventuriniAND** [comment]
I have reached out to James and looks like the Design system version needed updating to include this fix. Once that has been done he can confirm if this fix works for him or if anything needs doing after that.
