### ISSUE TITLE
Exploring Unnecessary Conditionals: Checkboxes

### ISSUE THREAD

**Issue by balibirchlee** [ONSdigital/design-system#3014]
Component contains a reference to 'params.borderlessParent' which is not in the markdown file.

Actions
- [ ] Establish if this is legacy code or else is created elsewhere - double bracket to see if the param has a value.
- [ ] Remove if not necessary.
- [ ] Ensure testing remains intact / update as required.

**Comment by adi-unni** [comment]
The reference to `params.borderlessParent` is a param that is called by the parent macro for checkboxes in cases where there is a checkbox field set within a checkbox. In this scenario, the child checkbox is set to borderless and so is the parent. The param that is set by the user `borderless` is documented and therefore no changes need to be made whilst the `params.borderlessParent` is an internal one, same as other `set` parameter and can remain undocumented. No other conditionals can be seen as unnecessary. Marking this ticket as completed.
