### ISSUE TITLE
Exploring Unnecessary Conditionals: Date-Input

### ISSUE THREAD

**Issue by balibirchlee** [ONSdigital/design-system#3015]
Component contains conditionals around the 'month' parameter - which is a required parameter. However, simply removing it leads to failing tests. 

Actions

- [ ] Establish if this is superfluous or necessary code.
- [ ] Remove if not necessary.
- [ ] Ensure testing remains intact / update testing as required.

**Comment by SriHV** [comment]
Based on the chat with Joe , Month being set to true is a legacy requirement and is dependant on the various scenarios. Hence, keeping it as a required parameter
