### ISSUE TITLE
Exploring Unnecessary Conditionals: Input

### ISSUE THREAD

**Issue by balibirchlee** [ONSdigital/design-system#3020]
Component contains conditionals around the .charCheckLimit.limit parameter on line 161 - which is a required parameter. 

Actions
- [ ] Establish if this is superfluous or necessary code.
- [ ] Remove if not necessary.
- [ ] Ensure testing remains intact / update testing as required.

**Comment by SriHV** [comment]
Closing this ticket as .charCheckLimit.limit param should be stayed as required parameter.
