### ISSUE TITLE
Exploring Unnecessary Conditionals: List

### ISSUE THREAD

**Issue by balibirchlee** [ONSdigital/design-system#3024]
Component contains conditionals around the item.text parameter - which is a required parameter. 

Actions
- [ ] Establish if this is superfluous or necessary code.
- [ ] Remove if not necessary.
- [ ] Ensure testing remains intact / update testing as required.

**Comment by SriHV** [comment]
Removing item.text from the examples breaks the component. This param should be left as required parameter
