### ISSUE TITLE
Label in name: visible labels not contained within accessible names (WCAG 2.2 Level A - Accessibility)

### ISSUE THREAD

**Issue by daniellecorke** [ONSdigital/design-system#3029]
### Background
The eQ service identified this issue within the ONS Design System following their DAC audit report (18/01/2024).

### Issue
The visible labels of interactive elements were not contained within their accessible names.

![Image](https://github.com/ONSdigital/design-system/assets/102512949/160fef4b-579c-42dc-a35e-7c151ab50a1d)

The ‘Start section’ links on this page are not fully accessible to voice activation users, as **visible labels of these links are not contained within their accessible names**. This issue occurs as the visible labels have been hidden from assistive technology using the ‘aria-hidden’ attribute. 
For example, the first link’s accessible name is ‘Start Household bills section’, provided through visually hidden text, but this name does not exactly contain its visible label of ‘Start section’. As a result, it may be difficult or time consuming for voice activation users to select these links by their visible name, as stating ‘Click section’ will not function, and the links will need to be manually navigated to.
This issue also applies to these links when the section is not completed, where they read as ‘Continue with section’.

### Suggested solution
Ensure that the visible labels of interactive controls are contained within their accessible names so that voice activation users can more efficiently interact with page content. In this instance, the links could be adjusted to follow the format of ‘Start section: Household bills’, to ensure that the visible text of ‘Start section’ is contained within the accessible name.

### Tasks
- Investigate whether the change can be made and any impacts
- Decide the best solution
- Implement the solution
- Update eQ with progress

### Info
- [eQ DAC reports/docs](https://confluence.ons.gov.uk/display/SDC/eQ+DAC+Reports)
- Issue ID: DAC_Label_In_Name_01
- DAC report pages: 22 to 24
- WCAG Reference: 2.5.3 Label in Name (Level A)
  - [Understanding Label in Name](https://www.w3.org/WAI/WCAG22/Understanding/label-in-name.html)
  - [How to Meet Label in Name](https://www.w3.org/WAI/WCAG22/quickref/#label-in-name)

**Comment by rmccar** [comment]
Change hidden text in eQ to be eg "Start section: Household bills"
