### ISSUE TITLE
Investigate the use of markuplint

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#3041]
We need a nunjucks/html linter to keep our code correctly formatted, we have already investigated djlint (https://github.com/ONSdigital/design-system/issues/2760) which doesn't seem to be an option for us at the moment but markuplint seems to be another option.

This card is to investigate the use of markuplint in the DS to see if it meets our needs, it looks like there is a nunjucks plugin that would need to be installed alongside it to get it to work.
- does it lint the .njk files correctly?
- are we able to implement this out of the box?
- if not is there any configuration changes we can make?
- does it work well with vscode?
- can it be used with husky for automated linting?

[markuplint.dev](https://markuplint.dev/)

**Comment by alessioventuriniAND** [comment]
After investigating this tool I can confirm that the nunjucks parser made available to this linter is not working for our repo and unfortunately there isn't any detailed documentation on how to configure this parser.
