### ISSUE TITLE
Add documentation to the new variant created in summary component

### ISSUE THREAD

**Issue by SriHV** [ONSdigital/design-system#3046]
A new card variant is added to the summary component #3009 . Documentation is required for the new example created in this component. 

The new example is stored in this path which can be used in the service manual example block :
design-system/components/summary/example-summary-card-grouped.njk

We have added a new parameter called variant which accepts hub or card. 

By setting the parameter to card the user will have access to the new card layout displayed in the example.

**Comment by alessioventuriniAND** [comment]
The new variant doc has been added to the service manual. It will go live with the next release. https://service-manual-en-preview-prod.gcp.onsdigital.uk/design-system/components/summary#card-grouped
