### ISSUE TITLE
Add padding between checkbox list and label

### ISSUE THREAD

**Issue by Majsol** [ONSdigital/design-system#3055]
Checkbox: in the design system there is less space between the checkbox list and the label than in the the bulleted list. 
Make the space larger between the label and the check box list. See pic.

https://service-manual.ons.gov.uk/design-system/components/accordion#:~:text=To%20use%20this%20variant%20include%20the%20parameter%20%27open%27%3A%20true%20in%20your%20implementation.

https://service-manual.ons.gov.uk/design-system/foundations/typography#:~:text=Bulleted%20list%20(default)

![Image](https://github.com/ONSdigital/design-system/assets/98104925/b558245c-b019-4fb2-8a06-97e59073943e)

**Comment by rmccar** [comment]
More space needed to the bottom of the "show only" label in the example
