### ISSUE TITLE
The icon set doesn't have a parent page

### ISSUE THREAD

**Issue by Majsol** [ONSdigital/design-system#3056]
Icon set: When I search for icon set in the service manual I get this page… 
https://service-manual.ons.gov.uk/icons

I cant really see how to get to this page if I don’t search for it - The Icon set page don’t have a parent page

**Comment by rmccar** [comment]
More information needed on where to link to this page from. Possibly a job for a content designer

**Comment by daniellecorke** [comment]
Speak to the Brand Design team - Rachel Price/Andy Budd.

**Comment by Majsol** [comment]
I have reached out the Andy and Rachel - waiting to hear from them.

**Comment by Majsol** [comment]
I got an answer from A & R
They have always been unsure of where it sits best as it was useful for both the brand guidelines and the design system, and both of these pages link to it 
https://service-manual.ons.gov.uk/design-system/foundations/icons, 
https://service-manual.ons.gov.uk/brand-guidelines/brand-elements/iconography.

**Comment by Majsol** [comment]
Something to consider... : The reason the "Icon Set" page is separate, is because it uses the left hand navigation structure differently to all of the other pages. So the page pattern is unique. Structurally it fits as a child page of "Design System" but semantically it works better as a child page of "Foundations". I don't mind where it sits, but the flow to and from the page needs to make sense, so we might want to add a "back to Foundations" link to the top of the page or something like that.

**Comment by alessioventuriniAND** [comment]
This is from Rachel :

- Firstly, we'd like to move the [icon set](https://service-manual.ons.gov.uk/icons) into the main [brand guidelines page](https://service-manual.ons.gov.uk/brand-guidelines), with the description "View our icons and download them for different formats and sizes."
- Secondly, the table of contents for the main icon set page is in the old format down the left side. This is slightly confusing as all the icons are separate pages down the left too. Could the contents be changed to the newer format above the main content, with an overview heading?


I will look into this and see if more changes need to happen :)
