### ISSUE TITLE
[Feature]: Add ONS Design Principles to the Service Manual

### ISSUE THREAD

**Issue by Majsol** [ONSdigital/design-system#3063]
### What feature would you like to add to the ONS Design System?

https://onsdigital.github.io/design/principles.html needs to be added to the Service Manual based on discussion in Slack : https://surveydatacollection.slack.com/archives/CR7LXCA81/p1709203711154949

Suggested location: Community pages

### Why should this new feature be added to the Design System?

Great work that describes our Design Principles, but isn't easily accessible at the moment. 

### Supporting material

https://onsdigital.github.io/design/principles.html

### Contacts

Grace Ellins

**Comment by daniellecorke** [comment]
Joe has completed this work in pre-prod and will copy it to prod for release.
