### ISSUE TITLE
Standardise size params: Button component

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#3064]
In [this issue](https://github.com/ONSdigital/design-system/issues/2159) It was suggested that adding the size params to variants would standardise variants across all components. But the decision has been made to keep the size ones separate due to the fact it could be confusing about which variants could be set together and which ones couldn't.

The [Button component](https://service-manual.ons.gov.uk/design-system/components/button) uses size params that need standardisation. 

To do this we need a common way of setting the size of these components, some are currently using variants some are not. This would mean that the variant params on the ones that do use them would need to be changed so that they only accept a string and not an array as only one variant would now be able to be set, other than button.

**Comment by alessioventuriniAND** [comment]
This cannot be applied to this component
