### ISSUE TITLE
Highlight documentation needs updating to suggest strong tag

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#3065]
The highlight example has been updated in [this PR](https://github.com/ONSdigital/design-system/pull/2766) to use `<stong>` tags. This has not been reflected in the documentation

![Screenshot 2024-02-29 at 15 46 10](https://github.com/ONSdigital/design-system/assets/42928680/afc5ed76-eb9f-44f6-bdca-8a902b9bee62)

**Comment by rmccar** [comment]
[This PR](https://github.com/ONSdigital/design-system/pull/3068) being merged has changed the implementation slightly. So the documentation will need to be updated to take into account this.

**Comment by alessioventuriniAND** [comment]
Docs updated on Service manual.
