### ISSUE TITLE
Embed tab contents not wrapping on video example

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#3121]
On [this example](https://service-manual.ons.gov.uk/design-system/components/tabs/example-tabs-details#video-embed) in the DS, on the embed tab the code isn't wrapping. We should look to see if there is a way of getting this to wrap so that the user doesn't have to sideways scroll on smaller screens.

<img width="466" alt="Screenshot 2024-04-05 at 09 08 28" src="https://github.com/ONSdigital/design-system/assets/42928680/cef4e277-41aa-4b8c-81a8-c6cde4ef388d">

**Comment by alessioventuriniAND** [comment]
This is something that needs addressing from the service manual.
