### ISSUE TITLE
Investigate new VR tools

### ISSUE THREAD

**Issue by adi-unni** [ONSdigital/design-system#3124]
Both the performance and stability of BackstopJS are significantly hindering the productivity and speed of delivery for the design system team. Attempts to improve the performance have been unsuccessful and no fixes have improved the stability in CI either, suggesting the need for a new tool. Investigate new tools for VR testing focussing on stability and performance especially in CI for node projects.

**Comment by daniellecorke** [comment]
Investigate free tools that are available, create a report including the pros and cons, and present to the team.

**Comment by adi-unni** [comment]
Improvement have been made to backstopJS. Demoting to medium priority.

**Comment by precious-onyenaucheya-ons** [comment]
1. BackstopJS:

- Pricing: 100% free.
- Compatibility with Nunjucks: Can be customized to work with Nunjucks.
- Performance: Slower compared to some other tools.
- Integration with GitHub/CI Tools: Integrates well.
- Active Community and Library Updates: Has an active community.

2. Percy:

- Pricing: Free for up to 5,000 snapshots.
- Compatibility with Nunjucks: Can be customized to work with Nunjucks.
- Performance: Scales very well.
- Integration with GitHub/CI Tools: Excellent integration.
- Active Community and Library Updates: Also has an active community.

3. Jest Image Snapshot:

- Pricing: Free.
- Compatibility with Nunjucks: Can be customized to work with Nunjucks.
- Performance: High performance.
- Integration with GitHub/CI Tools: Excellent integration.
- Active Community and Library Updates: Maintains an active community.

4. Chromatic:

- Pricing: Paid subscription based on usage.
- Compatibility with Nunjucks: Can be customized.
- Performance: High performance.
- Integration with GitHub/CI Tools: Excellent integration.
- Active Community and Library Updates: Supported by an active community.

5. Applitools:

- Pricing: Paid subscription based on usage.
- Compatibility with Nunjucks: Can be customized.
- Performance: High performance.
- Integration with GitHub/CI Tools: Excellent integration.
- Active Community and Library Updates: Also backed by an active community.



From the above findings, the team decided to continue with Backstop.js.
