### ISSUE TITLE
[Spike] Show a tooltip when hovering over an image

### ISSUE THREAD

**Issue by yatesn** [ONSdigital/design-system#3142]
### Background
The user initially contacted the team via the mailbox:

> Hi,
> I’ve recently been converting a project I’m working on to use the design system over Bootstrap 5 and I was wondering if there is or are plans to include an alternative for Bootstrap 5’s tooltips? I’d like to be able to show some extra information when hovering over an element and I’d like to do this in a standardised way if possible.
> 
> Thanks,
> Kieran
> 
> Kieran Pritchard 
> 
I contacted the user for more information. They are working on a Github policy plan within the Digital Innovation team. They are using the Design System to develop an app to clean up the ONS Github. 

Within the UI, they would like to use a tooltip to show how many contributions an individual contributor has made to a repo, when hovering. 

### Examples
**Before hover:**

![Image](https://github.com/ONSdigital/design-system/assets/102512949/d7d24efa-a962-4d03-bc93-5815dcba761b)

**While hovering:**

![Image](https://github.com/ONSdigital/design-system/assets/102512949/b2c62f24-2c26-4152-b73b-b73533b4bdf5)

The idea is, hover over a `div` or `img` and show the tooltip.

**Here's a snippet of my UI. I want the tooltip to show when hovering over the image:**

![Image](https://github.com/ONSdigital/design-system/assets/102512949/80ee9e11-d1e8-45ab-8742-10eb50078dd1)

The user is aware this may have accessibility implications. If we cannot incorporate this into the Design System, please can we answer the following question for them:

> If it can't be incorporated into the design system, would I be ok to just use bootstrap for tooltips? Or is that poor practice?

### User Story
AS A developer
I WANT a tooltip to show when I hover over the image in my UI
SO THAT I can see how many contributions a contributor has made to a repo

### Tasks

1. Investigate the feasibility of adding this functionality to the Design System, considering any usability and accessibility implications.
2. If we decide this is something we can do, add new ticket(s) to cover the work required, inform the user and provide links to the new ticket(s). 
3. If we cannot do this, inform the user and provide an answer to their question above and advise on best practice.

**Comment by daniellecorke** [comment]
I will contact the user for more information.

**Comment by daniellecorke** [comment]
Sent a message to the user via Teams to try to set up a call.

**Comment by daniellecorke** [comment]
Contact the user to provide advice.

**Comment by precious-onyenaucheya-ons** [comment]
### Accessibility Requirements for Adding Tooltips

**Implementing accessible tooltips** involves using appropriate ARIA roles and attributes, ensuring keyboard accessibility, and maintaining adequate visibility and contrast. Here are the key considerations:

1. **Role Attribute**
   - Use `role="tooltip"` to define the element as a tooltip for assistive technologies.

2. **ARIA-Describedby Attribute**
   - Use `aria-describedby` to link the tooltip with the element it describes, providing context for screen readers.

3. **Focus State**
   - Ensure the element associated with the tooltip is focusable to support both hover and keyboard focus for navigation.

4. **Color Contrast**
   - Ensure sufficient contrast between the tooltip text and its background for readability.

5. **Placement and Readability**
   - Position tooltips to avoid obscuring important content and to ensure they are easy to read.

**Comment by precious-onyenaucheya-ons** [comment]
This is a bespoke functionality and we don't see the usability for other users. The issue identified can be solved by adding column to display the information you want to add to the tooltip.

Else, you can go ahead to add the tooltip using bootstrap, but you can make reference to the Accessibility requirement added in the previous comment [this article](https://www.nngroup.com/articles/tooltip-guidelines/)
