### ISSUE TITLE
[Spike] Identify components without examples and/or macro options file

### ISSUE THREAD

**Issue by daniellecorke** [ONSdigital/design-system#3158]
### Background
Following a review of #2076, it was identified that several components do not have examples and/or macro options files.

The following components have already been identified as not including a _macro-options.md file:
- error
- field
- fieldset
- icons

However, due to the age of the previous ticket, we should check all components again. 

### Tasks
1. Look at each component and list any that do not have an example and/or a macro options file. 
2. Raise further tickets to add examples and/or macro options files to these components.

**Comment by SriHV** [comment]
Based on the inputs from prev tech session,I have recorded components that might/ might not require an example so we can discuss in next tech session 
List of Components that have examples in Foundation:
1. Address-output 
2. Icon
3. List
4. Quote

List of components that can have a example
1. Modal 
2. Message
3. Message list

**Comment by SriHV** [comment]
Based on conversation from tech session, I will create a new ticket to to move the list examples from foundation to its component.
