### ISSUE TITLE
Release breaking changes

### ISSUE THREAD

**Issue by daniellecorke** [ONSdigital/design-system#3162]
### Background

This ticket has been created to cover all small tasks that will result in breaking changes. Please list them here and we can complete and release them in one release rather than individually. 

### Tasks

- [ ] #3180 
- [ ] #3143 
- [ ] #3111 
- [ ] #3268 
- [ ] #3188 
- [ ] #3275 
- [ ] #3153

**Comment by rmccar** [comment]
Released
