### ISSUE TITLE
enhance utility classes

### ISSUE THREAD

**Issue by adi-unni** [ONSdigital/design-system#3172]
Enhance the utility classes by adding !important to them all and removing the mentioned classes from the ticket #3138

**Comment by rmccar** [comment]
Research into whether adding !important to all the utility classes is best practice in this case

**Comment by precious-onyenaucheya-ons** [comment]
Summary of Findings
Using !important can help override specificity and ensure certain styles are applied consistently. It is particularly useful for utility-first CSS frameworks where specific styles need to take precedence. However, overusing !important can lead to maintenance challenges, specificity conflicts, and reduced predictability in styling.

Advice
For utility classes that perform a single task (e.g., setting a color, margin, or padding), using the !important tag can be beneficial to ensure these styles take precedence and are applied as intended.

However, for utility classes that combine multiple styles, avoid using !important(e.g grid). This will help maintain the cascading nature of CSS, keep the codebase more manageable, and prevent specificity conflicts.

Best Practices
Use !important sparingly: Only for single-purpose utility classes.
Avoid !important in multi-style classes: Keep CSS predictable and maintainable.
Document usage: Clearly indicate where and why !important is used to aid future maintenance.
