### ISSUE TITLE
Deploy and test the address index API

### ISSUE THREAD

**Issue by daniellecorke** [ONSdigital/design-system#3176]
### Background

Following investigations into user feedback #3032, we need to deploy and test the Address Index API. 

### Tasks

1. Deploy a dockerised smaller version of the Address Index API - [this repo](https://github.com/ONSdigital/address-index-api/blob/develop/README.md#how-do-i-get-a-sneek-peak-of-the-api) contains the API.
2. Add rate limiting and allow requests from the service manual domain.
3. Testing.
4. If required - ask the Address Index Matching Service (AIMS) team to review our deployment and give feedback.
5. Update #3032 and move out of the blocked column.

### Acceptance Criteria
1. The Address Index API has been deployed and tested.
2. Our deployment has been reviewed by the AIMS team (if required). 
3. Ticket #3032 is unblocked.

**Comment by alessioventuriniAND** [comment]
This api has now been deployed and will need testing once the relevant examples have been updated.
