### ISSUE TITLE
Cards broken on iOS 10 and under:

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#319]
Cards broken on iOS 10 and under:
![Screenshot 2019-04-24 at 12 13 37](https://user-images.githubusercontent.com/43346934/56655657-5095e980-668b-11e9-97bc-be1238ee922e.png)

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/48#issuecomment-486181727_

**Comment by bameyrick** [comment]
This appears to be more of an issue with the [grid](#72) than the cards themselves.
