### ISSUE TITLE
[Bug]: Icon set links are pointing to an empty page

### ISSUE THREAD

**Issue by daniellecorke** [ONSdigital/design-system#3225]
### What happened?

A user reported that the links to the icon set on [this page](https://service-manual.ons.gov.uk/design-system/foundations/icons) are taking them to 'page not found'. This is likely due to a recent change to the parent page for the icon set. 

In addition to this, on the correct [icon set page](https://service-manual.ons.gov.uk/brand-guidelines/icon-set) there is link that doesn't work in the info panel. 

### What was the expected outcome?

The user expected the links to take them to the icon set pages. The user expected the link in the info panel to take them to a working page. 

### How is this problem impacting your service?

Any user trying to view the icon set page or website user interface icons by following these links will not be taken to the correct page. 

### What list of steps can be followed to reproduce the bug or issue?

1. Go to [this page](https://service-manual.ons.gov.uk/design-system/foundations/icons).
2. Under 'Use recognisable icons' and 'Icon type' try clicking the link to "our icon set". 

1. Go to [this page](https://service-manual.ons.gov.uk/brand-guidelines/icon-set).
2. In the info panel, try clicking the external link to "website user interface icons".

### Example

![Image](https://github.com/ONSdigital/design-system/assets/102512949/f8c6e20e-a400-4a95-b1b1-98e587157dbf)

### What version of the ONS Design System are you using?

Latest

### What devices are you seeing the problem on?

Desktop

### Device details

All devices

### What operating systems are you seeing the problem on?

Windows

### Operating system details

All operating systems

### What browsers are you seeing the problem on?

Chrome

### Browser details

All browsers

**Comment by alessioventuriniAND** [comment]
I have fixed the above links and they are going to be updated with the next service manual release which will take place this Wednesday.  The updated links can be verified on this link https://service-manual-en-preview-prod.gcp.onsdigital.uk/
