### ISSUE TITLE
Move Lists examples from Typography to Components

### ISSUE THREAD

**Issue by MagdalenaLarge** [ONSdigital/design-system#3241]
As Software Developer
I want to have a list examples in Components section rather than in Typography
So that I can easily find the examples of Lists 

#### Description
Currently all the examples of the list we have under Foundations => Typography.
Users would like to have all the examples of Lists moved to the Components section.
We need to add the following examples of the Lists:

- Bulleted list 
- Numbered list
- Bare list
- Dashed list
- Prefixed list
- Suffixed list
- Inline list
- Lists with icons
- List with icon prefix
- List with icon suffix
- Inline list with social media icon prefix

All above Lists need to be removed from Typography section.

#### Acceptance Criteria

1. User can find the link to Lists in Component tab
2. User can select the Lists Component by clicking on it
3. User can see different examples of the Lists
4. User can use any example 
5. User no longer can find Lists examples in Typography

#### Visualisation/Input from UCD
Current location of the Lists examples [Typography => Lists](https://service-manual.ons.gov.uk/design-system/foundations/typography#links)

Expected location of the Lists examples [Components](https://service-manual.ons.gov.uk/design-system/components)

#### Linked User stories/epics
[#3158](https://github.com/ONSdigital/design-system/issues/3158)

Technical details (optional)

MVP (optional)

**Comment by e-livingstone** [comment]
Having spoken to Joe, the view is that this is a style over component consideration. There isn't a reported reason, based on user need, to move lists out of the Foundations section; the suggestion came out of a Tech Session.

We now have the ticket to add the nunjucks macro to components in the [Foundations section](https://service-manual.ons.gov.uk/design-system/foundations) of the Design System.

Therefore closing this ticket. If this becomes a user need in future, it can be re-assessed at that stage.
