### ISSUE TITLE
[Bug] Day input field not aligned on Date pattern page

### ISSUE THREAD

**Issue by e-livingstone** [ONSdigital/design-system#3249]
### Summary
On the Date Pattern page all of the Day input fields are misaligned 

### Steps to reproduce
1. Head to https://service-manual.ons.gov.uk/design-system/patterns/dates

### Expected behaviour
Day, Month and Year input fields should be in line with each other

### Actual behaviour
See attached screenshot:

![Image](https://github.com/ONSdigital/design-system/assets/170529923/52f4f3e3-5b5b-4c95-8373-d4cf17f7f087)

### Type of the device, operating system, browser

**Comment by alessioventuriniAND** [comment]
This has now been fixed and is currently in prod : https://service-manual-en-preview-prod.gcp.onsdigital.uk/design-system/patterns/dates

I will do a release today at 15:00
