### ISSUE TITLE
Latest release information on the Design system website

### ISSUE THREAD

**Issue by MagdalenaLarge** [ONSdigital/design-system#3250]
As a Design System user
I want access the list of items included in the latest release directly from the Design System website
So that I don't have to use any other sources

**Description**
Currently we only provide the release information in the slack channel with the link to GitHub.
Users from outside of ONS can't easily access the release details which would include:

- release number
- release date
- link to GitHub release note

Other Design systems are including the detail of latest release on the main page.
It would be a good practise to do the same.

**Acceptance Criteria**

1. User can open Design System website
2. User can see release number
3. User can see release date
4. User can see link to GitHub release note

**Visualisation/Input from UCD**
Ticket added to UCD board for design to follow similar format to GDS:

![Image](https://github.com/ONSdigital/design-system/assets/169145384/d49c6ee3-1727-458c-8704-d27356452c96)

Unlike GDS, our release information will be contained within the header banner.

**Technical details (optional)**
[Link to the latest release](https://github.com/ONSdigital/design-system/releases/tag/70.0.8)

**MVP (optional)**
For V1, content will be manually added via CraftCMS. We can look to automate content alongside future releases.

**Comment by e-livingstone** [comment]
UCD team to be consulted

**Comment by e-livingstone** [comment]
Ticket added to UCD board for design: https://jira.ons.gov.uk/browse/CU-121

**Comment by MagdalenaLarge** [comment]
I'm closing this ticket as we cover it in ticket [#204](https://github.com/ONSdigital/design-team/issues/204)
