### ISSUE TITLE
List of the previous releases

### ISSUE THREAD

**Issue by MagdalenaLarge** [ONSdigital/design-system#3251]
As User of the Design System
I want to access list of previous releases done in Design System
So that I can see changes done in the past

**Description**
Currently user can only access list of releases in GitHub.
This list is not available to the public on the Design System website.
As a good practise this information should be accessible for all the users.

**Acceptance Criteria**

1.  User can access Design System website
2. User can find a link to the releases done in the past
3. User can click on the link which will take them to the Release list in GitHub

**Visualisation/Input from UCD**
How should the components look like?

**Linked User stories/epics**

**Technical details (optional)**
[List of the previous releases](https://github.com/ONSdigital/design-system/releases)

MVP (optional)

**Comment by e-livingstone** [comment]
UCD to be consulted

**Comment by MagdalenaLarge** [comment]
We decided to give users access to the list of releases in our GitHub repository. This way user can see what is the latest release and what were the previous releases, including their content.
User will have a link to this repository available on the Design System home page and work related to it is covered by the ticket [#204](https://github.com/ONSdigital/design-team/issues/204)
