### ISSUE TITLE
Performance: Better separate concerns in components

### ISSUE THREAD

**Issue by saedwards** [ONSdigital/design-system#326]
Items:
- domready subscriptions to all be put in one file for application initialisation. To decouple from class definition files and better controls the initialisation of all components. This convention decouples logic and better follows SRP.
- Component and module level classes should be separated - better testing (component and modules are not the same thing. In a pattern library this will be mainly down to their multiplicity of instances).
- Generally putting logic in constructor methods makes it hard to control the lifecycle of a component. This is a problem commonly solved in frameworks like Angular and React via onNgInit & componentDidMount. We’re already using a high-order function (domready) that controls the initialisation of modules. Making this change will help with better controlling how components are created, making them more adaptable for future reuse. Logic put in constructor methods should be constrained to validation and dependency management/assignment such as assigning a component context or a service dependency. Then an initialise function can be called later to do more stuff. This will also allow you to unit test the default state of a component.
- Inconsistency with how we select elements from the DOM, getElementByClassName, querySelectorAll are used. How elements are retrieved should be abstracted so that there is one definitive way of selecting elements should this need to change rather than hard-code to browser APIs. This will allow you to code branch for browsers that may not now or in future support the current implementation.
- We should build abstractions for more references to native browser APIs, which will make it easier change, fix and also easier to test.

**Comment by rmccar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #326: Performance: Better separate concerns in components](https://trello.com/c/Psi203NR/694-issue-326-performance-better-separate-concerns-in-components)

**Comment by rmccar** [comment]
Decided not to do this
