### ISSUE TITLE
abortable-fetch

### ISSUE THREAD

**Issue by saedwards** [ONSdigital/design-system#327]
Items:
- Using custom ‘then’ & ‘catch’ method for AbortableFetch isn’t great, if it’s trying to resemble a promise, should just use or extend a promise (prefer composition of a separate promise rather than it being a promise).
- Would be good to test with ‘options’ variants when unit testing.

**Comment by yatesn** [comment]
Mini spike - need to look at existing code. Potential that ticket is older than current code - may not be an issue

**Comment by kruncher** [comment]
It seems that the implementation inside 'src/js/abortable-fetch.js' could use a little spring clean; I propose the following refactor but I am currently unable to test that this works.

Matt is getting a JWT token to test against the address API and then hopefully we will be able to verify whether the refactor works. Without that I have no real way of testing that this change works. Obviously I do not want to create a PR which breaks this functionality for those using the address component.

```js
class AbortableFetch {
  constructor(url, options) {
    this.url = url;
    this.options = options;
    this.controller = new window.AbortController();
    this.status = 'UNSENT';
  }

  async send() {
    this.status = 'LOADING';
    try {
      const response = await window.fetch(this.url, { signal: this.controller.signal, ...this.options });
      const isResponseOK = response.status >= 200 && response.status < 300 || response.status >= 400;
      if (!isResponseOK) {
        const error = new Error(`HTTP error! status: ${response.status}`);
        error.response = response;
        throw error;
      }
      return response;
    }
    finally {
      this.status = 'DONE';
    }
  }

  abort() {
    this.controller.abort();
  }
}

export default (url, options) => new AbortableFetch(url, options);
```
