### ISSUE TITLE
Details/Accordion sharing of Collapsible.js

### ISSUE THREAD

**Issue by saedwards** [ONSdigital/design-system#328]
Items:
- Doesn’t feel quite right to pull in CollapsibleGroup into Collapsible and bootstrap it in this module--feels like there's too much going on here. CollapsibleGroup instances unavoidably get created when you only want to create Collapsible instances. I think we are missing a CollapsibleModule and CollapsibleGroupModule that can be pulled out into a separate file to better control instantiation.
- No dependency between CollapsibleGroup and Collapsible in the collapsible class.
- When creating accordions (collapsible groups), all collapsible in the document are passed to the CollapsibleGroup constructor and filtered by group id to scope the relevant ones to this group. Is there a better way of doings this? You have potential here for scope leak between CollapsilbeGroup instances maybe relying too much on developer discipline.

**Comment by bameyrick** [comment]
Relates to #148
