### ISSUE TITLE
[3 days SPIKE] Increase number of characters in the search field

### ISSUE THREAD

**Issue by MagdalenaLarge** [ONSdigital/design-system#3282]
**Goal**
In our Community backlog, user raised a concern about the number of characters in the list which can be searched.
We need to investigate if it is possible to increase this number.

**Background**

Community backlog comment [link](https://github.com/ONSdigital/design-system/discussions/894#discussioncomment-10134657)

**Context**
Currently we only use 30 characters string. We will have to investigate if it is possible to increase it.

**Consideration**
We are using Fuse library, so we need to check if it is feasible to do the change.

**Output**
TBC

**Comment by precious-onyenaucheya-ons** [comment]
We use Fuse.js library to support search functionality in the Design System. In the configuration of the search functionality , we have limited the search threshold to 20%. This effectively restricts the search to the first 20 characters. While increasing this threshold would allow more characters to be searched, it would also raise the likelihood of irrelevant results being returned.

Suggestion:
To address this, we could introduce a parameter within the autosuggest feature that enables extended search. If the user opts for extended search, we could raise the threshold to 40%, allowing the search to cover the first 40 characters(Documentation would need to be updated for this). However, there is a limitation to this approach, as it is unclear how many characters users may need to search for in different cases.

**Comment by MagdalenaLarge** [comment]
As per the discussion with the IDS team we will enable users to control number of characters in the Autosuggest component. Parameter can be set up between 0-1. New user story has been created: [#3347](https://github.com/ONSdigital/design-system/issues/3347).

As the next step we will also look into new version of Autosuggest which would use substring match rather than fuzzy search. [#214](https://github.com/ONSdigital/design-team/issues/214)
