### ISSUE TITLE
Feedback improvement suggestions

### ISSUE THREAD

**Issue by saedwards** [ONSdigital/design-system#330]
Items:
- handleSubmit doesn’t need to be asynchronous.
- Design only allows for one feedback component on a page. Components should be reusable within the same page. There is no scope to selecting elements within the same component instance from the DOM and currently taken from document level. We should stick to the convention of having one component instance per top-level element (‘const buttons’ & ‘this.details’ are chosen differently).

**Comment by bameyrick** [comment]
Relates to #236
