### ISSUE TITLE
language

### ISSUE THREAD

**Issue by saedwards** [ONSdigital/design-system#332]
Items:
- Only one component instance is allowed, not reusable at page level.
- Using ‘throttle’ is causing bugs to occur within the UI (a sign of missing tests). Holding the mouse down on an item in the dropdown for more than 200ms will cause the menu to disappear as seen here: https://ons-design-system.netlify.com/patterns/language-selection/
- 'throttle' not needed for this component, see https://deploy-preview-104--eq-prototypes.netlify.com/language-switcher/index-en/?language-switcher=true

**Comment by bameyrick** [comment]
Due to the dropdown [failing DAC testing](#338) we'll be removing this JS so we shouldn't do any work on this.
