### ISSUE TITLE
Table arrows not showing in IE11

### ISSUE THREAD

**Issue by saedwards** [ONSdigital/design-system#335]
Display issues in IE11 for sortable table arrows not showing correctly.

**Comment by bameyrick** [comment]
Relates to #102

**Comment by bameyrick** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Table arrows not showing in IE11](https://trello.com/c/PIsFcdSF/303-table-arrows-not-showing-in-ie11)
