### ISSUE TITLE
Tabs - Separation of Concerns

### ISSUE THREAD

**Issue by saedwards** [ONSdigital/design-system#336]
Feels like there’s more than one component in this file. Would look at separating out into something like tabs-view, tabs-list-view and tabs-details, and organising components in a container/controller (tabs-container). The container can then control the type of view component based not the viewport size etc. It would be easier to add more types if needed and easier to test.

**Comment by bameyrick** [comment]
Relates to #82

**Comment by rmccar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #336: Tabs Refactor](https://trello.com/c/u9gQa9wv/693-issue-336-tabs-refactor)

**Comment by rmccar** [comment]
Decided not to do it
