### ISSUE TITLE
Investigate and align textareas with the grid

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#3394]
**As a** user, 
**I want** the textareas to have consistent padding and margins, 
**so that** they align properly with the grid and are whole pixels in size, providing a clean and precise layout.

**Acceptance Criteria:**

1. Investigate the current padding and margin settings for textareas.
2. Identify any discrepancies or misalignments with the grid.
3. Adjust the padding and margin settings to ensure that textareas sit correctly on the grid and are whole pixels in size.
4. Verify that the changes are consistent across different screen sizes and devices.
5. Ensure that the visual appearance of the textareas is improved and aligns with the overall design guidelines.

**Visualisation**
<img width="649" alt="Screenshot 2024-10-08 at 16 33 29" src="https://github.com/user-attachments/assets/a409aea4-5ebd-4aac-84bf-1f328e98bccb">

**Link to the issue on Figma** https://www.figma.com/design/Wr9b6pK35euFoA6xq3G9Ld/Grid-review?node-id=0-1&node-type=canvas&m=dev

**Comment by MagdalenaLarge** [comment]
@rmccar will check if this ticket needs further work

**Comment by rmccar** [comment]
This one does seem to be no longer an issue
