### ISSUE TITLE
Vertical section navigation active element is a header that behaves like a link

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#3400]
****Summary**
The active page element on the vertical variant of the section navigation component is a header that seems to behave like a link when hovered over with an underline. This needs to be changed so that it is no longer a header, it should be a link like the links to other pages. This will provide a more consistent experience for users as it will behave like the links for other pages.

**Expected behaviour** 
The active page element on the section navigation component should behave like the links to the other pages, should be able to be clicked, focused and when hovered over adds a underline. 
See comments from @Majsol 

**Actual behaviour**
The vertical section navigation headers have an underline added when hovered as if they are a link when they aren't and aren't clickable or focusable. As can be seen here on the "section 6" item header.

**Screenshots/Examples****
<img width="198" alt="Screenshot 2024-10-10 at 10 20 21" src="https://github.com/user-attachments/assets/4a9584bd-bc5e-4f51-a8dd-134c0971e9ba">

**Comment by Majsol** [comment]
Richard and I had a chat about this ticket. We have decided to change the functionality of the section header so it behaves like a link even when it is already selected.
