### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by bameyrick** [ONSdigital/design-system#367]
Use this issue to discuss the [Question pattern](https://ons-design-system.netlify.com/patterns/question) in the [ONS Design System](https://ons-design-system.netlify.com)

**Comment by bameyrick** [comment]
Classes parameter does not work as its not just `classes` in the macro template, not `params.classes`

**Comment by bameyrick** [comment]
When the question component is in fieldset mode and there is no question description, the spacing between the title and the legend is too big.

This is because the legend and the h1 both have a margin bottom.

![Screenshot 2019-05-17 at 11 26 31](https://user-images.githubusercontent.com/8447446/57922035-bd6d5f80-7896-11e9-93a8-af7279c32129.png)

**Comment by bameyrick** [comment]
Question margins are still wrong, when there is a `h1` wrapped in a `legend` followed by `p` tags, the `p` tags aren't effected by the `h1`'s margin bottom:

![Image 28-05-2019 at 14 54](https://user-images.githubusercontent.com/8447446/58483833-ddcfd080-8158-11e9-8667-c1ec06275745.jpg)

**Comment by bameyrick** [comment]
When the `h1` is within the `legend`,  JAWS fails to find the `h1` when navigating by headings.

**Comment by CFryer** [comment]
Number of broken links encountered:

https://ons-design-system.netlify.com/components/radio
https://ons-design-system.netlify.com/components/date
https://ons-design-system.netlify.com/pattern/durations

**Comment by jrbarnes9** [comment]
Ensure consistent vertical spacing
Issues include:
- Vertical spacing is sometimes defined varies between top and bottom margins
- Spacing between a question page button varies depending on last item in question block
