### ISSUE TITLE
Deep levels of breadcrumbs take up too much space on mobile:

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#370]
Deep levels of breadcrumbs take up too much space on mobile:
<img width="349" alt="Screenshot 2019-05-14 at 14 32 54" src="https://user-images.githubusercontent.com/43346934/57702101-3da48280-7655-11e9-9693-5ea7729d7f2d.png">

A solution to display only the parent page link is required for under 500px breakpoint e.g...
<img width="359" alt="Screenshot 2019-05-14 at 14 36 42" src="https://user-images.githubusercontent.com/43346934/57702322-bc99bb00-7655-11e9-8ee0-17a0a17af367.png">

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/43#issuecomment-492240879_

**Comment by bameyrick** [comment]
Relates to #43

**Comment by bameyrick** [comment]
@jrbarnes9 Did we ever come to a decision as to whether this was actually an issue?
