### ISSUE TITLE
When a details component is open, it's button text does not change to 'Close'

### ISSUE THREAD

**Issue by bameyrick** [ONSdigital/design-system#402]
When a [details](#18) component is open, it's button text does not change to 'Close'

_Originally posted by @bameyrick in https://github.com/ONSdigital/design-system/issues/81#issuecomment-498696648_

**Comment by rmccar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accordion component show/hide button not changing label to "hide" when implemented](https://trello.com/c/lwgWPcld/395-accordion-component-show-hide-button-not-changing-label-to-hide-when-implemented)
