### ISSUE TITLE
Address Input

### ISSUE THREAD

**Issue by bameyrick** [ONSdigital/design-system#412]
Use this issue to discuss the [Address Input Pattern](https://ons-design-system.netlify.com/patterns/addresses) in the [ONS Design System](https://ons-design-system.netlify.com)

**Comment by bameyrick** [comment]
The address input needs to be made more configurable to allow only some fields being used. The current conditions used in the macro aren't compatible with Jinja so these need to be checked also.

**Comment by bameyrick** [comment]
We haven't considered validation for the address input with its multiple fields. We need to look into how we will handle mandatory field errors on this input.

**Comment by jrbarnes9** [comment]
Typo in `legendClasses` on 'Asking for an organisation or company’s address' example.

**Comment by jrbarnes9** [comment]
Add documentation about the use of the footer variant with 'OS address data terms and conditions' when using this pattern.
