### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by bameyrick** [ONSdigital/design-system#45]
Use this issue to discuss the [button component](https://ons-design-system.netlify.com/components/button) in the [ONS Design System](https://ons-design-system.netlify.com)

**Comment by bameyrick** [comment]
The ability to use the button component as anything other than a `<button>` element should be removed as this is bad practice.

**Comment by bameyrick** [comment]
Secondary button font colour is still blue, this should be black (#22222). This appears to be lost during a merge.

**Comment by bameyrick** [comment]
Small button variant is too tall since underline change has gone in. Its currently 45px tall where as it should be 35px tall.

**Comment by jrbarnes9** [comment]
I think `btn--small` could do with a bit more left/right padding.

**Comment by bameyrick** [comment]
I agree... First screenshot is current and second is with horizontal padding set to `0.7em`:

<img width="73" alt="Screenshot 2019-05-24 at 15 56 21" src="https://user-images.githubusercontent.com/8447446/58336979-b4ebca80-7e3c-11e9-98ab-98920359b0be.png">
<img width="77" alt="Screenshot 2019-05-24 at 15 57 06" src="https://user-images.githubusercontent.com/8447446/58336984-b87f5180-7e3c-11e9-94ed-59d4ae0a461d.png">

Fancy chiming in @will-madebymoon ?

**Comment by jrbarnes9** [comment]
LGTM. I think @will-madebymoon agrees.

**Comment by will-madebymoon** [comment]
I prefer the second one with a little bit wider... 

Sent whilst on the move

**Comment by jrbarnes9** [comment]
Ghost button variant doesn't have a background colour when viewed in a new window: https://ons-design-system.netlify.com/components/button/examples/button-ghost/

**Comment by bameyrick** [comment]
Pointer events need to be sent to none on `button__inner` to allow click events to be captured correctly

**Comment by rmccar** [comment]
Need to add a parameter to pass in URL to button component so that it can be used as a link

**Comment by jrbarnes9** [comment]
Focus state shouldn't change when the element is hovered.

**Comment by trevorsaint** [comment]
I think we need a button that looks like a link. I also would expect `.btn--link` to be a modifier to do exactly that.

However we are using the modifier `.btn--link` to make links look like buttons. Do we really need to do this? Can’t we just assume that if an `<a>`, `<button>` has a class of `.btn` it will look like a button.

I do feel this is a much better approach, and we can use the modifier to have a `<button>` that looks like a link.

**GDS** do it this way and it does make more sense. 
https://design-system.service.gov.uk/components/button/

**Comment by jrbarnes9** [comment]
Do we need a loader and timer button? This should probably be default behaviour for a `submit` button, as you'd never want user to double-click it, and you'd alway need to show user feedback (spinner) if the process takes longer than a certain delay.

**Comment by rmccar** [comment]
It is linked to setting the button type to be a submit button but I suppose we could change the logic a little bit so that it doesn't allow you to have a submit button without setting a submit type?

**Comment by jrbarnes9** [comment]
Macro table has created a button when trying to document the `<button>` tag - missing code markdown markup around it

<img width="591" alt="Screenshot 2021-01-08 at 15 38 43" src="https://user-images.githubusercontent.com/43346934/104033671-bdd31080-51c7-11eb-916b-4db4b653a248.png">
