### ISSUE TITLE
Details chevron hidden when screen colours inverted (using v12 ZoomFusion)

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#453]
Details chevron hidden when screen colours inverted (using v12 ZoomFusion)

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/148#issuecomment-503955512_

**Comment by bameyrick** [comment]
I haven't been able to recreate this using ZoomText 2019 so I believe this may only be an issue with older versions of ZoomText.

**Comment by bameyrick** [comment]
Closing due to this not being recreatable
