### ISSUE TITLE
Breadcrumbs chevrons hidden when screen colours inverted (using v12 ZoomFusion)

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#454]
Breadcrumbs chevrons hidden when screen colours inverted (using v12 ZoomFusion)

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/43#issuecomment-503955836_

**Comment by bameyrick** [comment]
Closing due to this not being recreatable
