### ISSUE TITLE
Relationships

### ISSUE THREAD

**Issue by bameyrick** [ONSdigital/design-system#464]
Use this issue to discuss the [Relationships pattern/component](https://ons-design-system.netlify.com/patterns/relationships) in the [ONS Design System](https://ons-design-system.netlify.com)

**Comment by bameyrick** [comment]
The JavaScript to change the question, legend, and playback needs to be run on page load for when a user returns to a the page with their option preselected.

**Comment by jrbarnes9** [comment]
Typos in relationships pattern documentation...
> Help users select define relationships between household memebers.
