### ISSUE TITLE
Panel

### ISSUE THREAD

**Issue by bameyrick** [ONSdigital/design-system#49]
Use this issue to discuss the [panel component](https://ons-design-system.netlify.com/components/panel) in the [ONS Design System](https://ons-design-system.netlify.com)

**Comment by bameyrick** [comment]
Links within panels should not have their colour modified. Links should always be the same blue everywhere.

**Comment by jrbarnes9** [comment]
Panels need a default bottom margin parameter

**Comment by bameyrick** [comment]
Maybe we should address all all of these issues when we look at spacing: https://trello.com/c/h0RbO4UV/99-spacing

**Comment by bameyrick** [comment]
Theres no classes parameter so adding custom spacing via utility classes isn't possible

**Comment by bameyrick** [comment]
We need a parameter to customise the tag used within the header element, e.g. to use a `h1` for the title.

**Comment by jrbarnes9** [comment]
Reintroduce a 'warning' panel when the consequences of the users action could have a negative effect.  e.g. The EQ 'remove person' confirmation message: 

<img width="795" alt="Screenshot 2019-11-08 at 15 49 13" src="https://user-images.githubusercontent.com/43346934/68489605-5aee8e00-023f-11ea-8969-e1bdd58d21ea.png">

**Comment by jrbarnes9** [comment]
Remove `border-left` from warning panel

**Comment by trevorsaint** [comment]
> Remove `border-left` from warning panel

Yeah I’ve spotted this bug and need it removed.

![image](https://user-images.githubusercontent.com/4989027/86143792-cba72b00-baec-11ea-9eb5-174a56ad07b9.png)

**Comment by jrbarnes9** [comment]
Warning panel text should be bold by default
![Screenshot 2020-07-09 at 16 06 29](https://user-images.githubusercontent.com/43346934/87056917-2c75e800-c1fe-11ea-8c2b-7548bcaa338c.png)

**Comment by jrbarnes9** [comment]
Wrapping issue with error summary panel

![Screenshot 2020-07-30 at 10 08 23](https://user-images.githubusercontent.com/43346934/88904247-bf79cf00-d24c-11ea-94d0-bc40b3f8e9f9.png)

**Comment by jrbarnes9** [comment]
Need to be able to define a panel icon size

<img width="721" alt="Screenshot 2020-08-05 at 15 51 45" src="https://user-images.githubusercontent.com/43346934/89427971-c2d0f700-d733-11ea-8bbe-96ce17922f7d.png">

**Comment by jrbarnes9** [comment]
Wrapping issue in error summary panel...
 
![image](https://user-images.githubusercontent.com/43346934/93993532-c4f42100-fd86-11ea-9132-720f3c37d168.png)

**Comment by jrbarnes9** [comment]
Remove `border-left` from `panel--bare`

`panel--bare` should have no left border, so e.g. icons in these panels can be left-aligned with the page container.
![Screenshot 2020-10-09 at 16 39 35](https://user-images.githubusercontent.com/43346934/95603345-0b67a200-0a4e-11eb-9d53-e8d30aa21933.png)

**Comment by jrbarnes9** [comment]
Remove top and bottom padding from `panel--bare` so spacing is dictated by bottom margins

**Comment by jrbarnes9** [comment]
Adjust panel icon vertical alignment

![Screenshot 2020-10-29 at 09 35 09](https://user-images.githubusercontent.com/43346934/97550993-4ebc8d00-19ca-11eb-95e7-525188f765aa.png)

**Comment by jrbarnes9** [comment]
Remove unnecessary padding from `panel--warn`

<img width="975" alt="Screenshot 2020-11-27 at 08 24 55" src="https://user-images.githubusercontent.com/43346934/100427492-70bd3400-308a-11eb-8791-091756e6f518.png">
