### ISSUE TITLE
Typeahead examples not working

### ISSUE THREAD

**Issue by armstrongb** [ONSdigital/design-system#588]
**Describe the bug**

**Examples not working**
Console errors cause by blocking of fetch due to CORS policy.

> `Access to fetch at 'https://ons-typeahead-prototypes.herokuapp.com/country-of-birth?query=fr&lang=en' from origin 'https://ons-design-system.netlify.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**To Reproduce**

1. Go to https://ons-design-system.netlify.com/components/typeahead/examples/country-of-birth/
2. Click on the input field and start entering a country name
3. See error listed in console.

**Expected behavior**
On typing in the input field suggested matches are returned as a selectable list

**Desktop (please complete the following information):**

- OS: *All*
- Browser (e.g. chrome, safari) - not browser dependant
- Version (e.g. 22) n/a

**Comment by rmccar** [comment]
No longer an issue
