### ISSUE TITLE
`details__title` should use a semantically appropriate heading tag (not a `<span>`) when no js

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#615]
`details__title` should use a semantically appropriate heading tag (not a `<span>`)

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/148#issuecomment-535917302_

**Comment by rmccar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Details & Accordions: `details__title` should use a semantically appropriate heading tag #615](https://trello.com/c/slGf6Oft/422-details-accordions-detailstitle-should-use-a-semantically-appropriate-heading-tag-615)
