### ISSUE TITLE
Add `maxlength` to date inputs

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#672]
Users have fed back frustrations around the ability to add more than two or four characters in the date inputs.  This is especially frustrating for users who expect auto-tabbing, because they end up entering everything into the first input (which is too small to easily edit/delete)

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/22#issuecomment-562507566_

**Comment by rmccar** [comment]
Done
