### ISSUE TITLE
Inconsistent borders in household collector summaries...

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#686]
Inconsistent borders in household collector summaries...
<img width="712" alt="Screenshot 2020-01-22 at 16 42 49" src="https://user-images.githubusercontent.com/43346934/72914519-b3a9cf00-3d36-11ea-9dd4-ac5c76d285da.png">
...proposing to always display a bottom border on a summary if a link follows...
<img width="742" alt="Screenshot 2020-01-22 at 16 47 21" src="https://user-images.githubusercontent.com/43346934/72914681-f2d82000-3d36-11ea-871f-c9328fed66fe.png">
<img width="717" alt="Screenshot 2020-01-22 at 16 47 37" src="https://user-images.githubusercontent.com/43346934/72914682-f2d82000-3d36-11ea-99f3-245d3460b9e7.png">

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/84#issuecomment-577277643_

**Comment by rmccar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #686: Inconsistent borders in household collector summaries](https://trello.com/c/wZp3cxSf/699-issue-686-inconsistent-borders-in-household-collector-summaries)
