### ISSUE TITLE
Width and height of svgs lost when rendered in the browser

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#694]
**Tasks for this ticket:**

1. Investigate whether the issue outlined in this ticket is still relevant. 
2. If so, try to identify a fix for the bug and implement it. 

Width and height of svgs lost when rendered in the browser
<img width="773" alt="Screenshot 2020-02-11 at 14 13 54" src="https://user-images.githubusercontent.com/43346934/74244126-dea19600-4cd8-11ea-8306-6f6b8be50eb3.png">

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/195#issuecomment-584655441_

**Comment by rmccar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #694: Width and height of svgs lost when rendered in the browser](https://trello.com/c/nXYAaM0e/700-issue-694-width-and-height-of-svgs-lost-when-rendered-in-the-browser)

**Comment by precious-onyenaucheya-ons** [comment]
This is not relevant anymore
