### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by bameyrick** [ONSdigital/design-system#70]
Use this issue to discuss the [Pagination component](https://ons-design-system.netlify.com/components/pagination) in the [ONS Design System](https://ons-design-system.netlify.com)

**Comment by bameyrick** [comment]
Some debugging variables have been left in the macro (https://github.com/ONSdigital/design-system/commit/b0fad430b71627150a96cb768780dbf3794c945f#diff-782048d2b2591ff1b22c6c6ebaf74303R17) and should be removed

**Comment by jrbarnes9** [comment]
Pager pagination would benefit from a bit more breathing space between itself and the content (IMHO)...

<img width="563" alt="Screenshot 2019-06-26 at 13 52 49" src="https://user-images.githubusercontent.com/43346934/60181375-f4ca1700-9819-11e9-955c-01cf51f53b5d.png">

**Comment by trevorsaint** [comment]
We need to remove the underline when the pager is in focus.
![image](https://user-images.githubusercontent.com/4989027/87150686-74eadf80-c2aa-11ea-8bc1-39306b16890f.png)

**Comment by jrbarnes9** [comment]
Long pagination examples are broken

**Comment by trevorsaint** [comment]
We don’t need to specify 'false' on all items in the example docs.
Just add 'true' when required.
