### ISSUE TITLE
Update focus colour and align highlight

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#704]
Focus colour is out of date. And highlight should use the same shade of yellow as the new focus colour.

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/232#issuecomment-589638931_

**Comment by rmccar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update focus colour and differentiate highlight #704](https://trello.com/c/k6BLByRQ/474-update-focus-colour-and-differentiate-highlight-704)

**Comment by rmccar** [comment]
Done
