### ISSUE TITLE
Control cookies

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-system#715]
Use this issue to discuss [Control cookies](https://ons-design-system.netlify.com//patterns/cookie-settings/) in the [ONS Design System](https://ons-design-system.netlify.com)

**Comment by jrbarnes9** [comment]
Cookie banner buttons spacing lost on overlapping 500px breakpoint
![Screenshot 2020-07-09 at 13 51 17](https://user-images.githubusercontent.com/43346934/87042746-fe87a800-c1eb-11ea-8341-056e045b0ec7.png)

**Comment by jrbarnes9** [comment]
Saving the cookies form in the DS example sends you to the previous page you were on
