### ISSUE TITLE
Remove `border-left` from warning panel

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#747]
Remove `border-left` from warning panel. We want warning icon to left-align with content.

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/49#issuecomment-611524541_

**Comment by jrbarnes9** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #765: Warning panel text alignment with more than one line of text](https://trello.com/c/t6phy5i1/512-issue-765-warning-panel-text-alignment-with-more-than-one-line-of-text)

**Comment by jrbarnes9** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Warning panels within collapsible (Adjust spacing)](https://trello.com/c/55bdLQvf/522-warning-panels-within-collapsible-adjust-spacing)

**Comment by rmccar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Warning panels within collapsible (Adjust spacing)](https://trello.com/c/55bdLQvf/522-warning-panels-within-collapsible-adjust-spacing)
