### ISSUE TITLE
Breadcrumbs not rendering correctly at breakpoint 500px and below.

### ISSUE THREAD

**Issue by trevorsaint** [ONSdigital/design-system#759]
Breadcrumbs not rendering correctly at breakpoint 500px and below.

![image](https://user-images.githubusercontent.com/4989027/83241813-4948e580-a193-11ea-9168-9e817932045b.png)

_Originally posted by @trevorsaint in https://github.com/ONSdigital/design-system/issues/43#issuecomment-635861022_

**Comment by jrbarnes9** [comment]
I'm only seeing this issue at exactly 500px, not below.
