### ISSUE TITLE
Warning panel text alignment with more than one line of text

### ISSUE THREAD

**Issue by ajmaddaford** [ONSdigital/design-system#765]
**Describe the bug**
Text alignment for the warning panel is off when there is more than one line of text.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a warning panel with more than one line of text.

**Expected behaviour**
The text should be aligned with the top of the warning icon.

**Screenshots**
![image](https://user-images.githubusercontent.com/1754822/83647834-44c66780-a5ad-11ea-81a7-533b2048e2c9.png)

**Desktop (please complete the following information):**

- OS: OSX
- Browser Chrome
- Version 83.0.4103.61

**Additional context**
N/A

**Comment by jrbarnes9** [comment]
#842

**Comment by trevorsaint** [comment]
@ajmaddaford I would disagree with you on this point I am afraid. 

Changes were made in a previous PR to fix alignment issues. I see it working correct as illustrated below:

**Multiple lines**
![image](https://user-images.githubusercontent.com/4989027/94026144-3648c980-fdb1-11ea-99f5-85a787cc11f2.png)

**Single line**
![image](https://user-images.githubusercontent.com/4989027/94026231-4cef2080-fdb1-11ea-88cd-9d24d128ada1.png)

Single or multiple lines, no change to the position is correct visually.

GDS do the same

**Multiple lines**
![image](https://user-images.githubusercontent.com/4989027/94026466-9dff1480-fdb1-11ea-84c0-7158dae4114d.png)

**Single line**
![image](https://user-images.githubusercontent.com/4989027/94026392-82940980-fdb1-11ea-9031-bf08e916b9af.png)
