### ISSUE TITLE
Reduce $color-amber lightness to make white on amber colour combination accessible

### ISSUE THREAD

**Issue by JNATION85** [ONSdigital/design-system#798]
Reduce $color-amber lightness to make white on amber colour combination accessible. New HEX colour to change to #FF600A

_Originally posted by @JNATION85 in https://github.com/ONSdigital/design-system/issues/232#issuecomment-650080998_

**Comment by armstrongb** [comment]
This deviates from the agreed ONS colour palette orange.

**Comment by rmccar** [comment]
This has already been implemented in [this PR](https://github.com/ONSdigital/design-system/pull/807)

**Comment by rmccar** [comment]
Because this has already been implemented, i'll close this. If it is an issue though, raise another issue and we will prioritise it and add it to our backlog.
