### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by bameyrick** [ONSdigital/design-system#81]
Use this issue to discuss the [Accordion component](https://ons-design-system.netlify.com/components/accordion) in the [ONS Design System](https://ons-design-system.netlify.com)

**Comment by dudelmeister** [comment]
Accordion needs bottom padding on the content div

**Comment by jrbarnes9** [comment]
> Accordion needs bottom padding on the content div

PR -> https://github.com/ONSdigital/pattern-library-v2/pull/112

**Comment by bameyrick** [comment]
When a [details](#18) component is open, it's button text does not change to 'Close'

**Comment by rmccar** [comment]
Possible issue when implementing the accordion the show/hide buttons don't change label when clicked, example:https://sdc-prototypes.netlify.com/prototypes/sic/

**Comment by rmccar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accordion component show/hide button not changing label to "hide" when implemented](https://trello.com/c/lwgWPcld/395-accordion-component-show-hide-button-not-changing-label-to-hide-when-implemented)

**Comment by jrbarnes9** [comment]
Accordions alignment broken on small breakpoint
![Screenshot 2020-11-03 at 13 26 39](https://user-images.githubusercontent.com/43346934/97990681-3b4d5f80-1dd8-11eb-8140-421545f80b22.png)

**Comment by trevorsaint** [comment]
> Accordions alignment broken on small breakpoint
> ![Screenshot 2020-11-03 at 13 26 39](https://user-images.githubusercontent.com/43346934/97990681-3b4d5f80-1dd8-11eb-8140-421545f80b22.png)

You just beat me to it :).

**Comment by trevorsaint** [comment]
Accordions break visually if using it without show/hide buttons. I have removed one as an example.

<img width="783" alt="Screenshot 2021-01-18 at 11 52 10" src="https://user-images.githubusercontent.com/4989027/104912215-e73c2b00-5983-11eb-9f3b-e80caa151e78.png">
