### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by boxadesign** [ONSdigital/design-system#82]
Use this issue to discuss the [Tabs](https://ons-design-system.netlify.com/components/tabs) in the [ONS Design System](https://ons-design-system.netlify.com)

**Comment by bameyrick** [comment]
The background of the tabs appears to be to dark:

<img width="363" alt="Screenshot 2019-07-26 at 12 26 06" src="https://user-images.githubusercontent.com/8447446/61948757-9de26980-afa0-11e9-94f3-760379718f50.png">

**Comment by jrbarnes9** [comment]
Typo in tabs attribute...
![Screenshot 2020-06-19 at 11 37 53](https://user-images.githubusercontent.com/43346934/85124398-c8c15600-b221-11ea-937a-8aca319cfa75.png)
