### ISSUE TITLE
Cookie banner buttons spacing lost on overlapping 500px breakpoint

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#823]
Cookie banner buttons spacing lost on overlapping 500px breakpoint
![Screenshot 2020-07-09 at 13 51 17](https://user-images.githubusercontent.com/43346934/87042746-fe87a800-c1eb-11ea-8341-056e045b0ec7.png)

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/715#issuecomment-656110887_

**Comment by rmccar** [comment]
Already fixed
