### ISSUE TITLE
Highlight write-in when input fails validation

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#826]
Highlight write-in when input fails validation
![Screenshot 2020-07-10 at 10 18 20](https://user-images.githubusercontent.com/43346934/87138701-b8d3e980-c296-11ea-9506-7edeb5260c1b.png)

![Screenshot 2020-07-10 at 10 19 09](https://user-images.githubusercontent.com/43346934/87138758-d0ab6d80-c296-11ea-9606-f58f5b28728b.png)

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/30#issuecomment-656577491_

**Comment by armstrongb** [comment]
Is there something 'more accessible' that can be done as the highlight of the input alone may not be enough for colourblind users?
