### ISSUE TITLE
Introduce inline SVGs

### ISSUE THREAD

**Issue by trevorsaint** [ONSdigital/design-system#835]
I think we need to revisit the way we use icons. We should be introduce inline SVGs.

We are using the pseudo after attribute with a background SVG. Zoom is fine. However for something like focus, we are unable to change the colour attribute and have limitations. An inline SVG would provide greater flexibility. Colour could be inherited, we could also change the icon colour without changing the image.

**Resting state**
![image](https://user-images.githubusercontent.com/4989027/87540206-2c129c80-c697-11ea-99e6-c4dd2e3c7ca4.png)

**Focus state**
![image](https://user-images.githubusercontent.com/4989027/87540183-21f09e00-c697-11ea-93ff-aa1217f7097d.png)

The icon should be black on focus.

**Comment by rmccar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #835: Introduce inline SVGs for external links](https://trello.com/c/SVJv66uG/568-issue-835-introduce-inline-svgs-for-external-links)
