### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by bameyrick** [ONSdigital/design-system#84]
Use this issue to discuss the [Summary component](https://ons-design-system.netlify.com/components/summary) in the [ONS Design System](https://ons-design-system.netlify.com)

**Comment by bameyrick** [comment]
The breakpoint for changing from layout to have question, answer, and action all on one row, vs question above answer and action is currently set to > 25 chars for the answer length. This could probably be bumped up to 50 chars.

**Comment by bameyrick** [comment]
As discussed with @will-madebymoon, the answer column needs a greater width bias, but still be flexible for translations/different actions etc.

**Comment by bameyrick** [comment]
As discussed with @will-madebymoon, we should remove the mode for wrapping answers below questions on desktop.

**Comment by will-madebymoon** [comment]
Move the answer over in the summary providing more space to the question and so that the change link is closer to the actual answer
<img width="730" alt="Screenshot 2019-04-02 at 09 34 40" src="https://user-images.githubusercontent.com/8184622/55388150-a7941d00-552a-11e9-999a-8cd4d0080918.png">

**Comment by bameyrick** [comment]
The condition that checks if a rowItem has values does not work in jinja2

**Comment by bameyrick** [comment]
The action spacer element (pipe) is being read by screen readers.

**Comment by bameyrick** [comment]
When the summary is within a question (e.g. household collector), the first row should not have a top border and the last item should not have a bottom border.

**Comment by bameyrick** [comment]
As discussed with @will-madebymoon and @boxadesign we should remove the top border from the first row, and the bottom border from the last row.

**Comment by bameyrick** [comment]
We need to add the top border back on to the first item always so that zoom text users can discover the action links.

**Comment by jrbarnes9** [comment]
The HTML used to emphasise parts of a question title has been included in the aria-label associated with the ‘Change’ link on the summary. This could confuse some users navigating out of
context who may be unaware of the purpose or meaning of the HTML. 
```html
<td class="summary__actions">
<a href="/questionnaire/accommodation-type/#accommodation-type-answer"
class="summary__button" aria-label="Change your answer for: What type of
accommodation is <em>68 Abingdon Road, Goathill</em>?" data-qa="accommodationtype-answer-edit">Change</a>
</td>
```

**Comment by jrbarnes9** [comment]
Inconsistent borders in household collector summaries...
<img width="712" alt="Screenshot 2020-01-22 at 16 42 49" src="https://user-images.githubusercontent.com/43346934/72914519-b3a9cf00-3d36-11ea-9dd4-ac5c76d285da.png">
...proposing to always display a bottom border on a summary if a link follows

**Comment by JNATION85** [comment]
Are we able to increase the green tick on summary page by 1px? I think it needs to be more prominent in the hub

**Comment by jrbarnes9** [comment]
Multiple/grouped summary example is broken

**Comment by jrbarnes9** [comment]
Long words breaking summary

<img width="622" alt="Screenshot 2020-06-08 at 08 58 55" src="https://user-images.githubusercontent.com/43346934/84006290-64231300-a966-11ea-9639-e9ffc37c4fae.png">

**Comment by jrbarnes9** [comment]
All summary values should not be bulleted
<img width="971" alt="Screenshot 2020-08-03 at 11 28 39" src="https://user-images.githubusercontent.com/43346934/89173809-b9e9f500-d57c-11ea-8887-e05968f09f57.png">

**Comment by jrbarnes9** [comment]
Reduce top padding on the link container that follows a summary 

Should be `u-pt-s` not `u-pt-m`

From this...
![Screenshot 2020-10-27 at 08 28 58](https://user-images.githubusercontent.com/43346934/97276176-c48bf180-182e-11eb-8fea-4ade08d85093.png)

To this...
![Screenshot 2020-10-27 at 08 29 11](https://user-images.githubusercontent.com/43346934/97276203-cb1a6900-182e-11eb-95b0-89e19a6b6c2a.png)

This relates to the work done to fix this issue...
> Inconsistent borders in household collector summaries...
> <img alt="Screenshot 2020-01-22 at 16 42 49" width="712" src="https://user-images.githubusercontent.com/43346934/72914519-b3a9cf00-3d36-11ea-9dd4-ac5c76d285da.png">
> ...proposing to always display a bottom border on a summary if a link follows...
> <img alt="Screenshot 2020-01-22 at 16 47 21" width="742" src="https://user-images.githubusercontent.com/43346934/72914681-f2d82000-3d36-11ea-871f-c9328fed66fe.png">
> <img alt="Screenshot 2020-01-22 at 16 47 37" width="717" src="https://user-images.githubusercontent.com/43346934/72914682-f2d82000-3d36-11ea-99f3-245d3460b9e7.png">
