### ISSUE TITLE
I would expect the full area of the radio button to be clickable

### ISSUE THREAD

**Issue by trevorsaint** [ONSdigital/design-system#850]
I would expect the full area of the radio button to be clickable.
![image](https://user-images.githubusercontent.com/4989027/88305945-06723c80-cd02-11ea-8405-2c97ec5a8788.png)
Anything below the highlighted purple marking has no effect on selection.

A user may attempt to click / tap in that area.

_Originally posted by @trevorsaint in https://github.com/ONSdigital/design-system/issues/56#issuecomment-663077008_

**Comment by jrbarnes9** [comment]
> I would expect the full area of the radio button to be clickable.
> ![image](https://user-images.githubusercontent.com/4989027/88305945-06723c80-cd02-11ea-8405-2c97ec5a8788.png)
> Anything below the highlighted purple marking has no effect on selection.
> 
> A user may attempt to click / tap in that area.
> 
> _Originally posted by @trevorsaint in [#56 (comment)](https://github.com/ONSdigital/design-system/issues/56#issuecomment-663077008)_

@rmccar I think this must have changed when you moved the hint text outside the label.
