### ISSUE TITLE
Typography is rendering differently in Firefox than it is in Chrome

### ISSUE THREAD

**Issue by trevorsaint** [ONSdigital/design-system#851]
### Typography is rendering differently in Firefox than it is in Chrome

**We have** 
`-webkit-font-smoothing: antialiased;` 

**Missing** 
`-moz-osx-font-smoothing: grayscale;`

Adding this should fix the issue, ensuring typography consistency.

**Chrome**
![image](https://user-images.githubusercontent.com/4989027/88310178-42f46700-cd07-11ea-844f-4c3b3105e30b.png)

**Firefox rendering thicker**
![image](https://user-images.githubusercontent.com/4989027/88310142-37a13b80-cd07-11ea-8fbd-108eb608cfb2.png)

_Originally posted by @trevorsaint in https://github.com/ONSdigital/design-system/issues/233#issuecomment-663098243_

**Comment by jrbarnes9** [comment]
Resolved in #1372
