### ISSUE TITLE
Download resources

### ISSUE THREAD

**Issue by trevorsaint** [ONSdigital/design-system#888]
Use this issue to discuss the [Download resources](https://ons-design-system.netlify.com/patterns/download-resources) in the [ONS Design System](https://ons-design-system.netlify.com)

**Comment by armstrongb** [comment]
Preview of this in the design system has a page of extreme length and it slowly auto-scrolls upwards back into view. (The scrolling back up in the gif below is not user controlled.)

![320-design-system-download-resources-pattern-scroll](https://user-images.githubusercontent.com/22910336/95750652-5cb5a280-0c95-11eb-8779-1d8a28dda19f.gif)

**Comment by trevorsaint** [comment]
@armstrongb I noticed this also. I thought it was my computer playing funny buggers.

I would suspect this has something to do with the iframe resize, and not the component itself.
