### ISSUE TITLE
Grid examples lost background color

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#924]
Grid examples lost background color
![Screenshot 2020-08-17 at 16 35 30](https://user-images.githubusercontent.com/43346934/90414546-d53e1f80-e0a7-11ea-8a38-3d4d3762e4ab.png)

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/72#issuecomment-674953543_

**Comment by rmccar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #924: Grid examples lost background colour](https://trello.com/c/AO7Kapc2/695-issue-924-grid-examples-lost-background-colour)
