### ISSUE TITLE
Download resources pattern 'show filters' not working when used in a prototype

### ISSUE THREAD

**Issue by trevorsaint** [ONSdigital/design-system#971]
**Describe the bug**
For small screens, we are presented with a show/hide filters button. This functionality works in the ons design system but does not work when used in a prototype.

**To Reproduce**
Shrink the screen and click 'show filters'.  This works as expected in the Design System but not in a prototype. See example:

https://deploy-preview-118--sdc-prototypes.netlify.app/prototypes/census-website-engage/downloadable-resources/

**Comment by armstrongb** [comment]
### Desktop (chrome)
Appears to work on the netlify preview linked on this issue when I tested in Chrome and inspector.
### iPhone 6s
In Safari on a 6S the buttons fail to display (see attached)
![IMG_7208](https://user-images.githubusercontent.com/22910336/93222494-ec376680-f766-11ea-8df4-a93d315fe621.PNG)

**Comment by trevorsaint** [comment]
@armstrongb thanks for this. 

Some other issues exist we are aware of. We’re trying to fix these too.

**Comment by rmccar** [comment]
@armstrongb You must've tested just after I pushed the fix for it

**Comment by armstrongb** [comment]
@rmccar hmm still not playing ball on the iPhone atm.

**Comment by armstrongb** [comment]
Should the pdfs (if these are intended for print only output) have `rel="nofollow"` on the links to the pdf?

**Comment by yatesn** [comment]
Duplicate card #1664
