### ISSUE TITLE
Save and sign out button in footer of page template example ('Customised page template') is missing exit icon

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#996]
Save and sign out button in footer of page template example ('Customised page template') is missing exit icon

<img width="279" alt="Screenshot 2020-09-17 at 09 18 20" src="https://user-images.githubusercontent.com/43346934/93439794-e062b600-f8c6-11ea-9204-f77be5afd905.png">

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/195#issuecomment-694077020_

**Comment by trevorsaint** [comment]
This fix has been merged @jrbarnes9.
